### ISSUE TITLE
[landing page] Add rollover to drop down

### ISSUE THREAD

**Issue by Jacklynn** [18F/crt-portal#578] opened 2020-06-08 22:55 UTC
Having the same roll over as the other darkblue buttons for the "examples" drop down would help it feel more interactive, which the latest user testing said was not as obvious.
![Screen Shot 2020-06-08 at 3.25.45 PM.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/811a9859-149a-446d-8781-c2462c46ae0c)

I would expect the text & icon to **stay white** but the background to change to: `blue-50` `#2378C3`

**Comment by lalitha-jonnalagadda** [comment] 2020-07-21 17:06
@Jacklynn @AvivaOskow can you please UAT this and if all is good, please move them to UAT complete

**Comment by Jacklynn** [comment] 2020-07-21 17:46
@hakhalid11 I'm checking with @AvivaOskow  because there's a discrepancy with the hover color as defined in the style guide and how it is throughout the page. It looks like elsewhere on the page it's using  #1A4480..

But one thing not included in this is that we wanted the icon to stay white on hover.

**Comment by Jacklynn** [comment] 2020-07-21 19:20
I talked to Aviva and the color is correct but the icon **should remain white on rollover.** Thanks!

**Comment by Jacklynn** [comment] 2020-07-21 19:24
I created a second ticket for the other buttons: https://app.zenhub.com/workspaces/doj-crt-intake-scrum-board-5d03bf56c1c8a35d482eca0f/issues/18f/crt-portal/643

**Comment by hakhalid11** [comment] 2020-07-21 19:27
Thanks. Alright I will change the Icon back to white

**Comment by hakhalid11** [comment] 2020-07-21 19:35
Quick question regarding #578 does the Icon need to stay white on hover on both hover states.

![image.png](https://images.zenhubusercontent.com/5efb8164bf9ea016ca6016f2/015f37b6-3d5e-4466-8132-9b34076a921f)

![image.png](https://images.zenhubusercontent.com/5efb8164bf9ea016ca6016f2/660bdcb2-9537-44bc-abd9-aa9b2f0548bb)

**Comment by Jacklynn** [comment] 2020-07-21 19:37
Yes, i would expect it to stay white in both instances. thanks!

**Comment by cantsin** [comment] 2020-07-22 17:52
The white icon tweak above has been updated and pushed to dev. @blaughman Did we want this tweak in for the upcoming release (`07-28-2020`) as well?

**Comment by blaughman** [comment] 2020-07-22 20:24
@cantsin If it's not a problem, let add it to the upcoming release.

**Comment by cantsin** [comment] 2020-07-23 16:21
Thank you @hakhalid11 -- this tweak will be in the next release also.

**Comment by blaughman** [comment] 2020-07-29 14:57
Function works as intended in prod.  Closing card.

**Closed by blaughman** 2020-07-29 14:57 UTC
Labels: Release 7-28-20
