### ISSUE TITLE
View Correspondent Information on Record Detail Page

### ISSUE THREAD

**Issue by alexsoble** [18F/crt-portal#24] opened 2019-07-10 16:03 UTC
## Narrative
As a CRT User,
I want to view information about the complainant about a single record page
so that I can contact the complainant to:
- request further information about their case
- communicate their case outcome to them

## Background
Public users can choose to give their contact information to CRT if they are submitting a complaint for themselves or someone else. They can also opt to report anonymously. Complainant contact information allows CRT sections to follow up with that individual to gather more information about their complaint. It does not prevent them from taking action on a case. If a complainant reports anonymously, CRT will not be able to contact them.

## Assumptions
- From the details page, user can *not* navigate to other complaints (detailed pages of other complaints) using the 'Next' and 'Back' buttons
- Modular boxes are not collapsible or expandable 

## Out of scope
- Changing statuses
- (Re)Routing complaints 
-Viewing complaint details (#)
- Viewing violation summary(#)
- unique ID generation - this is done automatically with primary key on the report model.

## Acceptance criteria 

1) Given a complaint has been submitted to DOJ CRT
When I am viewing that complaint on the view all complaints table
- [ ] Then I notice that I can click on that complaint (row)

2) Given I am viewing a complaint on the view all complaints table
When I click on a complaint (row)
- [ ] Then I am directed to that complaint's record page

3) Given I've clicked on a complaint in the view all table
When I am viewing that complaint's record page
Then  I view in the page header:
- [ ] Page title - Complaint
- [ ] Submission date
AND
I view in the body of the page a modular section called 'Complainant Information' where I can view the following information in the same format as view all table - viewable if submitted by complainant):
- [ ] Complainant Name 
- [ ] Email
- [ ] Phone
AND
I view an button called 'Close'
AND
all the information I view on the records page matches the information of that complaint line item on the view all page.

4) **UPDATED:** Given a complaint has been submitted to DOJ CRT and the complainant did not enter a field value
When I am viewing that complainant's detail page
- [ ] Then I view that each field has an em dash `—`

5) Given I am viewing a complainant's detail page
When I click on the button called 'Close'
Then I am redirected back to the 'view all complaint's table

## Mockups (draft)
![036e3635-119e-4612-b364-de7f3fb7cdcc.png](https://images.zenhubusercontent.com/5d0270ab1c131e09cdccbd7c/733a75cb-f2dd-4ecb-80de-c34058deb24d)

## Technical Notes
- [ ]
- [ ]
- [ ]

**Comment by alexsoble** [comment] 2019-07-10 16:05
Added from the ISL doc via the GitHub API! cc @UchMok

**Comment by UchMok** [comment] 2019-11-21 22:25
@AvivaOskow Assuming these boxes aren't collapsible/expandable

**Comment by lalitha-jonnalagadda** [comment] 2019-11-25 18:49
Notes from the planning meeting: Is there a reusable Django review page that we can repurpose on this page?

**Comment by Jacklynn** [comment] 2019-11-25 18:51
Version with the close button, looks like it didn't save — ![[UPDATED] Complaint details.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/e603aa5c-613c-4c61-a3c6-903458d3c9c0)

**Comment by el-mapache** [comment] 2019-11-27 14:15
@Jacklynn @AvivaOskow I've got a question about AC 1 above!

Do we want to preserve the standard 'browser blue' text and underline for the clickable table rows? Because of the way HTML tables have to be structured, each `td` cell's content has to be wrapped in an `a` tag, so each datum is going to have the link styling applied.

**e.g.**
<img width="481" alt="Screen Shot 2019-11-27 at 9 10 28 AM" src="https://user-images.githubusercontent.com/1421848/69730253-b781f200-10f5-11ea-88c0-32b998b12325.png">

I think the underlines and color make it explicit that the rows are clickable, but it also seems a little noisy? An alternative might be to apply a background on hover to the `tr` element, although that makes it less clear that the rows are clickable; we could also have another column with a call to action button.

I'm probably overthinking this 😄 but I appreciate your input!

**Comment by Jacklynn** [comment] 2019-11-27 23:44
@el-mapache great questions! Let's take out the individual links for each cell. As you mentioned, it looks busy and it's also misleading, it looks like you can click on an individual cell. 

When Aviva and i talked before, we were talking about adding a shadow around the tr to make it look like it was elevated on hover, is that possible/reasonable?

<img width="695" alt="Screen Shot 2019-11-27 at 3 42 26 PM" src="https://user-images.githubusercontent.com/2560618/69766436-d2bc2400-112c-11ea-9aca-b1236f534b51.png">

**Comment by el-mapache** [comment] 2019-12-02 13:12
@Jacklynn We can definitely add the hover shadow style. Unfortunately, we can't make a `tr` element clickable per se; the only valid direct children of a table header or table body are `tr` and `td` elements. So, to make the 'row' clickable, each `td` element has to have an `a` tag as its child.

Given that, will the intent that the rows are clickable be clear with the cursor style change and the hover effect?

**Comment by el-mapache** [comment] 2019-12-02 13:13
@lalitha-jonnalagadda @Jacklynn I'm omitting the `address` section of the table, since we don't ask the user for it.

**Comment by LindsayYoung** [comment] 2019-12-03 15:41
Noting that when we add sort and filter options, we will want to pass that to this template probably something like adding `next={{ page_format.page_args }}&page={{ page_format.page }}` to the url and then adding that to the close record link.

**Comment by LindsayYoung** [comment] 2019-12-03 16:47
Updated the default null behavior in the AC based on feedback from @AvivaOskow and @Jacklynn

**Comment by lalitha-jonnalagadda** [comment] 2019-12-04 17:26
Quick notes from my desk check:

On Chrome and IE - 
- Edit option is out of scope
- Typo in 'Correspondent Details' spelling (My apologies for nitpicking)

On IE 11 specifically - 
- Entire row isn't being highlighted when hovering over a record in IE as it is on Chrome. In IE, the cursor however changes from a pointer to a hand, which is in one way indicating that the row is clickable, but its not the same experience as in Chrome. 

CC @el-mapache @blaughman

**Comment by blaughman** [comment] 2019-12-05 15:19
If the Edit button is out of scope, are we still leaving it on the page for future functionality?  Other than that, the page works as intended in IE 11.  Should the IE experience mirror that on Chrome?  @lalitha-jonnalagadda @el-mapache

**Comment by el-mapache** [comment] 2019-12-05 15:25
@lalitha-jonnalagadda @blaughman  Just wanted to drop an update on the hover state of table rows in IE. I haven't really been able to figure out a way to duplicate the hover `box-shadow` functionality. The only solution I've tried that definitely works would be to rewrite the entire table using `div`s, which removes any of the semantic accessibility benefits the table provides. We should be able to add those back using `aria` roles, but I think the amount of effort is not really worth doing this just so IE 11 admin users can view a drop shadow effect.

**Comment by el-mapache** [comment] 2019-12-05 15:26
@blaughman @lalitha-jonnalagadda I'll remove the `edit` button, I think having it there will be confusing to testers!

**Comment by blaughman** [comment] 2019-12-05 15:29
@el-mapache @lalitha-jonnalagadda Thanks.  I don't want any potential delays in UAT for something that is out of scope.  Appreciate it, and BTW  the page looks great.

**Comment by el-mapache** [comment] 2019-12-05 15:32
@blaughman @lalitha-jonnalagadda One last comment! If either of you two have access to IE Edge, I'd be curious to see if the box shadow behaves properly there. Edge is IE's equivalent to a modern browser like Chrome or FireFox, so the behavior is more likely to be consistent with those browsers.

**Comment by blaughman** [comment] 2019-12-05 15:48
Edge screenshot
![image.png](https://images.zenhubusercontent.com/5d2390b2c408a2441fc2874d/3cdb095c-ec90-4bde-92bf-1d14119054a0)

**Comment by lalitha-jonnalagadda** [comment] 2019-12-05 15:49
@el-mapache Checked in Edge and it behaves similar to IE than Chrome. Let's proceed with the current styling in IE. Functionality is working well.

**Comment by blaughman** [comment] 2019-12-05 15:51
@lalitha-jonnalagadda @el-mapache Should I hold off on moving to UAT until the edit button is removed?

**Comment by lalitha-jonnalagadda** [comment] 2019-12-05 15:52
Yeah, let's wait until we have the edit button removed @blaughman

**Comment by lalitha-jonnalagadda** [comment] 2019-12-05 15:55
CC: @AvivaOskow and @Jacklynn 👆🏼regarding the drop shadow issue on IE and Edge when hovering on a row in the view all table

**Comment by Jacklynn** [comment] 2019-12-05 17:21
@lalitha-jonnalagadda @blaughman Isn't IE the default browser for the majority of CRT users? The change in curser alone is pretty subtle. 

@el-mapache Would it be lower effort to use a color fill for IE/Edge users?

**Comment by el-mapache** [comment] 2019-12-05 18:27
@Jacklynn I agree the change is subtle :/. I sort of faked it by just removing the `td` broders on hover. Additional I specified `border-collapse: separate, border-spacing: 0`, which lets IE render box shadows on the table element itself. Check out this GIF and let me know if you think its workable:

![table-ie-11](https://user-images.githubusercontent.com/1421848/70262756-eab22a00-1762-11ea-9e3d-22d83d7e0bf0.gif)

**Comment by blaughman** [comment] 2019-12-06 14:45
This page functions as intended in IE 11.  Moving to UAT.

**Comment by lalitha-jonnalagadda** [comment] 2019-12-13 14:38
Reviewed with the deep dive group on 12/12 and this card can now be closed.

**Closed by lalitha-jonnalagadda** 2019-12-13 14:38 UTC
Labels: Story
