### ISSUE TITLE
Session data cleared on `GET` request to /report/

### ISSUE THREAD

**Issue by Jkrzy** [18F/crt-portal#791] opened 2020-11-23 14:26 UTC
We've noticed an increase in Report submissions failing the final form step due to required fields missing from the final set of data, particularly `protected_class`. 

As these are required fields and the form itself will not allow you to progress without providing them, we investigated in #784 and found the following. 

A *new* Report is started -- session data is cleared -- when a visitor performs a `GET` request to /report/. If this occurs while a visitor is progressing through the form, in another tab for example, their final submission may not contain all required fields and will generate an error. 

Of note is that [Samsung Internet browser](https://www.samsung.com/us/support/owners/app/samsung-internet) appears to be performing `GET` requests behind the scenes independent of User action (and absent browser network logs which is strange), effectively reseting the Report form as a visitor tries to progress.

> 1. Be a user submitting a report
> 2. Have your session data cleared
>   * Either by refreshing /report/ in another tab or
>   * Samsung’s browser doing this weird background GET thing
> 3. Proceed through the form in your original tab/browser
> 4. Submission will fail when protected_class is absent the session data on final submit.

## Towards remediating the impact of this we will
- [ ] Document the expected behavior for when a visitor, while having already progressed into the Report form, returns to `/report/`, via a  `GET` request.
  * Potential origins include but are not limited to
    * Starting a Report and returning later
    * Starting a Report on a shared/public device and not completing before logging out of the device/closing browser/otherwise clearing session data
    * Navigating to `/report/` in a tab while completing form in another
- [ ] Create a card to implement any changes stemming from the above decision

## Possible Solutions
1 Potentially not clear the session data
2 Explore a more targeted fix for the Samsung behavior with changing how we clear the session data
Improve error handling around this issue.
3 At this time, only affects Samsung browser (can we redirect user to another browser, help text, etc.)

**Comment by timoballard** [comment] 2020-12-03 16:40
Screenshot below captures what the user currently sees when encountering this error. As discussed yesterday, a reasonable starting point for this issue would be to provide the user with a more helpful description of the problem, and perhaps recommend that they try again with a different browser. Thoughts @blaughman ?

![Screen Shot 2020-12-03 at 10.34.52 AM.png](https://images.zenhubusercontent.com/5f6b6d45a696d381a6f600f9/68c5ed8e-ab18-4c1e-91cb-41c35ec4eab5)

**Comment by blaughman** [comment] 2020-12-03 17:18
@timoballard @randyabramson @Jkrzy @ilodidoj @cantsin When we implemented the error pages, did we discuss the issue presented by Tim above?  I thought our belief was to keep the pages fairly basic, but this issue requires a little more help text than we currently offer.  Are there other options we should consider?

**Comment by cantsin** [comment] 2020-12-03 17:29
I think we can detect this particular error when it happens (to be technical: when we pop the `protected_class` from the form data) and render a separate error page instead. It could also be a 500 response code with a separate template (or even the same template but with different wording).

**Comment by randyabramson** [comment] 2020-12-03 17:32
Thanks for brining this up @blaughman and @timoballard .

This error template is a catch all for all errors except for 404 errors, so it might be a big task to write explanations for each possible error code (see https://kinsta.com/blog/http-status-codes/ for a complete list).

I do like the idea of perhaps creating a 'sniffer' script that would present a message to Samsung users and tell them to use a different browser. However, I would ask @timoballard if we might finish this task off more quickly than creating a sniffer script.

**Comment by timoballard** [comment] 2020-12-03 17:34
As @cantsin alluded to, we can target this problem specifically because we have access to the underlying exception at the point where we render the standard `500` error page. So, we could look for the telltale sign of this problem (`protected_class` is missing) and in that case render a different, more detailed error page with help text suggesting that they try a different browser. @randyabramson @blaughman

**Comment by randyabramson** [comment] 2020-12-03 17:40
@timoballard I was under the impression that even non-Samsung users could get this error (I believe @Jkrzy mentioned opening the form in another tab).

If that's the case, then I'm not sure if the suggestion of using another browser would always apply.

Secondly, do you think we can fix this error quicker than the time to come up with a specific error page?

**Comment by timoballard** [comment] 2020-12-03 17:52
@randyabramson it is true that you can run into this error in any browser, but only by deviating from what we would consider a standard traversal of the report submission process, such as having two report submission forms open in different tabs. There isn't an obvious solution to this issue that doesn't include changing the form behavior in other, perhaps equally or more problematic ways. For example, we could opt to not have the form data reset when the user visits the initial report submission page, but that would likely create different issues when users have multiple report submission tabs open, because the form data would effectively be shared between the two tabs.

The idea behind the more detailed error page, at least for now, is to give users of the Samsung browser the information they need to be able to submit forms at all, because currently they are not able to, and nothing about the error being presented to them suggests that it might be browser related (i.e. they have no reason to think that switching browsers would help, it appears that the site just doesn't work).

**Comment by randyabramson** [comment] 2020-12-03 18:23
Hi @timoballard, thanks for this clarification...I'm following what you are saying.

My thoughts are:

1. Are we reaching out to Samsung or posting in their development boards to get clarity on this issue? I assume other people might be having the same issue and there might be a patch to this browser. On that point, we should monitor the number of Samsung users who see this error...perhaps a patch has already been rolled out?

2. Since there's no obvious solution for this, let's move forward with the separate error page for this. Let me know if we should start a new card for this.

(I'm thinking that text such as "Samsung Web Browser is currently not supported. Please visit this form in Chrome, Firefox, Safari or Internet Explorer.")

3. What do you think about the idea of the sniffer? If we think this is going to be a long term problem, I think we should alert the user before they start the form that this browser is not supported.

**Comment by cantsin** [comment] 2020-12-03 19:45
Jumping in here. Regards 1, I looked through [the Samsung Internet support forum](https://forum.developer.samsung.com/c/samsung-internet/25) but did not find anything conclusive (to be fair, there's not much activity). There's also a [deprecated github repository](https://github.com/SamsungInternet/support) which is also of no help. Since Samsung Internet Explorer is a lesser known (and Chromium-derived) browser variant, I don't think we can expect much from them. For the record, I can't reproduce on Chromium (which is distinct from Chrome stable). So it's something Samsung is doing for whatever reason.

**Comment by randyabramson** [comment] 2020-12-04 15:49
Thanks for that insight @cantsin

**Comment by randyabramson** [comment] 2020-12-08 00:12
Closing this since we are starting new tickets for this

**Closed** 2020-12-08 00:13 UTC
