### ISSUE TITLE
Assignee not clearing on Section change for BulkActions

### ISSUE THREAD

**Issue by Jkrzy** [18F/crt-portal#738] opened 2020-10-09 18:37 UTC
In #737 we received a report of 

> I re-routed 5 reports from HCE to other sections. 
> I was expecting the  assignee  would be removed from these reports, but in this instance, it did not.

In https://github.com/usdoj-crt/crt-portal/blob/03ad53591da9a4107e1ddb7a5222b7eb86767fe8/crt_portal/cts_forms/views.py#L457 we implemented the clearing of `Assignee` when `Section` was changed on the individual report form.

This implementation is limited to modifying individual Reports, it is not applied when using the newer `BulkActions` functionality. 

We'll know we're done when:
- [ ] If section is modified via bulk action, assignee is set to `None` for each modified `Report`

cc: @cantsin, @randyabramson, @blaughman

**Comment by cantsin** [comment] 2020-10-13 16:28
@randyabramson @blaughman 

Currently if we change the section for an individual record, we unset the assignee and set the status to new. This is forced, and happens _even_ if the user sets assignee and/or status in the same form submission. Accordingly, I am following similar logic for the bulk action functionality here. I don't think this should be too surprising, but opening this up for discussion.

**Comment by cantsin** [comment] 2020-10-13 16:34
I think the other ticket was a duplicate, so I'm copying and pasting what was there before: 

```
If user changes assigned section without assigning status or assignee, we give them a warning message as we did with the other bulk messaging: "You are about to change the section for xyz records. The status will be set to New and there will not be an assignee."

Button for 'Apply changes to xyz records' is present.

If user changes assigned section with assigning status and/or assignee, we follow the request of the user and update status and/or assignee accordingly.
```

Notes: the logic is different here so we may have to discuss this. I can add messaging, but I think it's better to be consistent between the individual and bulk action form where applicable.

**Comment by blaughman** [comment] 2020-10-13 16:37
@cantsin @randyabramson I would expect the bulk section change to revert status back to 'new' and remove any assignee from the selected records.  I like the message above indicating what will happen once they take action on those records.

**Comment by cantsin** [comment] 2020-10-13 22:46
As per meeting today, we agreed here to:

- Grey out "Judicial district"
- Classification stays in

I'm disabling the widget but it may be easier to remove entirely. Will toss up for review and see what others say.

**Comment by randyabramson** [comment] 2020-10-13 23:50
Sounds good...thanks @cantsin

**Comment by Jkrzy** [comment] 2020-10-19 13:43
https://github.com/usdoj-crt/crt-portal/pull/706 looks good and I'll merge shortly.

@cantsin, I'm +1 for your earlier comment to remove `Judicial District` from the form if it is not a modifiable field for `BulkActions`

> I'm disabling the widget but it may be easier to remove entirely. Will toss up for review and see what others say.

**Comment by blaughman** [comment] 2020-10-23 18:55
Function works as intended in Dev.  Moving to UAT.

**Closed** 2020-10-30 00:17 UTC
Labels: Bug, Release 10-29-2020
