### ISSUE TITLE
View all table lists full "protected class" content instead of abbreviation

### ISSUE THREAD

**Issue by Jacklynn** [18F/crt-portal#224] opened 2019-12-11 22:08 UTC
Problem: 
"disability" is listing full content in the View All tables instead of abbreviation (screenshot below)

Expected:
If a user checks "Disability (including temporary or recovery)" protected class, the View all table should abbreviate as "Disability" -- else this takes up a lot of space. I believe it was working this way previously.

Screenshot: 
![Screen Shot 2019-12-11 at 2.06.20 PM.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/01ffc544-622e-4532-8f51-e4aa342a1591)

**Comment by Jacklynn** [comment] 2019-12-31 18:07
Actually I noticed all of them are listing the full names.

**Comment by LindsayYoung** [comment] 2020-01-06 18:29
We need to use PROTECTED_CLASS_CODES (you can find those in model_variables.py), instead of the classes directly. 

This information already gets passed to the template with additional formatting here:
https://github.com/usdoj-crt/crt-portal/blob/develop/crt_portal/cts_forms/views.py#L64-L84

To fix this, he variable we need to rename the protected_class variable to  report_protected_classes
https://github.com/usdoj-crt/crt-portal/blob/develop/crt_portal/cts_forms/templates/forms/complaint_view/index/complaints_table.html#L64-72

Here is an example of how we implemented this before the regression:
https://github.com/usdoj-crt/crt-portal/blob/release/12-09-19/crt_portal/cts_forms/templates/forms/index.html#L74

**Comment by lalitha-jonnalagadda** [comment] 2020-01-24 17:30
Since we are planning on removing the protected classes column from the view all table to make space for incident date, there is no need to work on this card at this time. Moving this card to done!

**Comment by LindsayYoung** [comment] 2020-02-03 20:09
No estimate, since we are not doing this card.

**Closed by LindsayYoung** 2020-02-03 20:09 UTC
Labels: Bug
