### ISSUE TITLE
Adjusting CRM routing

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#627] opened 2020-07-13 14:52 UTC
## Narrative
As a CRT User, I want to adjust the Criminal Section routing logic so that reports are routed more accurately.

## Problem
Originally, the Criminal Section requested to see all reports where the public answered 'yes' to the hate crime question.  The public's misinterpretation, as well as the formulation of the question, has resulted in nearly 30% of all incoming traffic routed to the Criminal Section.

## Solution
Selecting 'yes' to the hate crime question will not automatically route incoming complaints to the Criminal Section.  Rather, the primary issue and reported reason will route the complaints just as they do if someone indicated their situation is not a hate crime.

**Comment by blaughman** [comment] 2020-11-19 23:42
Reference the 5/19/20 sheet for the most recent routing permutations.

https://docs.google.com/spreadsheets/d/1Ba0617v1wqwf89vYkCQmpNGmi3yI-bfPgXSF8JPqkeQ/edit#gid=706357640

**Comment by Jkrzy** [comment] 2020-11-23 19:31
@blaughman are those permutations updated by you and what we should expect to see from the application after this change OR are we to provide updated permutations after removing the `if HATECRIME then route to CRM` logic?

**Comment by randyabramson** [comment] 2020-11-24 11:22
@Jkrzy - @blaughman is out this week, so let me know if I need to jump in and move this forward.

Also, @emilycryan  it might make sense here to come up with a power search of 'hate crime = yes' + some high priority key words as we work through the language changes, etc.

**Comment by Jkrzy** [comment] 2020-12-01 16:34
@blaughman picking this one up!

I updated the [sheet](https://docs.google.com/spreadsheets/d/1Ba0617v1wqwf89vYkCQmpNGmi3yI-bfPgXSF8JPqkeQ/edit#gid=706357640) you shared with a 12/01/2020 tab to capture the updated routing rules as I understand them.

As I understand, we're removing the hate crime question entirely from the routing logic.

**Comment by blaughman** [comment] 2020-12-01 16:59
@Jkrzy Correct.  The majority of these complaints were misrouted because of the answer to the hate crime question.  This should allow the primary concern and personal characteristics to be the main drivers of the routing.  Thanks.

**Comment by blaughman** [comment] 2020-12-01 18:02
@Jkrzy The updated sheet looks good to me.  Thanks.

**Comment by blaughman** [comment] 2020-12-07 13:55
Complaints are routing as intended.  Moving to UAT.

**Comment by randyabramson** [comment] 2020-12-08 21:57
Verified on staging

**Closed** 2020-12-15 22:38 UTC
