### ISSUE TITLE
View Violation Summary on Complaint Detail Record

### ISSUE THREAD

**Issue by UchMok** [18F/crt-portal#185] opened 2019-11-25 20:05 UTC
## Narrative
As a CRT User,
I want to view complainant's full violation summary of a complaint record
so that I can confirm if the complaint has merit

## Background
The violation summary allows DOJ CRT to determine whether a complaint has merit. Historically, CRT has received violation summaries that are not helpful in determining merit, because they are too verbose (+30 pages) or vague.

A lot of users used to rely on attachments to explain their incident and tell CRT to 'see attached'. This field will direct them to 'use their words' to fully describe their problem.

This user story will allow the CRT user to view the complainant's summary of the discriminatory event beyond the structured form categories.

## Assumptions
- From the details page, user can *not* navigate to other complaints (detailed pages of other complaints) using the 'Next' and 'Back' buttons
- Modular boxes are not collapsible or expandable 
- View complainant information on detail page has been developed

## Out of scope
- Changing statuses
- (Re)Routing complaints 
-Viewing complaint details (#)
- unique ID generation (is this in scope of thin slice?)

## Acceptance criteria 

2) Given I am viewing a complaint on the view all complaints table
When I click on a complaint (row)
- [ ] Then I am directed to that complaint's record page

3) Given I've clicked on a complaint in the view all table
When I am viewing that complaint's record page
Then  I now view a new section under 'Complainant Information' called 'Full Summary'
AND
because Violation Summary is required, I can view that complainant's submitted violation summary in full (up to 500 words) in the section called 'Full Summary'
AND
a subset of the 'Full summary' information I view on that record page matches the 'abridged' information of that complaint line item's 'violation summary' on the view all page.

## Mockups (draft)
![complaint_violation sum.png](https://images.zenhubusercontent.com/5d0270ab1c131e09cdccbd7c/d5ea0be6-91a4-498b-90fb-cf7fcc697909)

## Technical Notes
- [ ]
- [ ]
- [ ]

**Comment by blaughman** [comment] 2019-12-10 15:53
Function works as intended in IE 11.  Moving to UAT.

**Comment by lalitha-jonnalagadda** [comment] 2019-12-13 14:39
Reviewed with the deep dive group on 12/12 and this card can now be closed.

**Closed by lalitha-jonnalagadda** 2019-12-13 14:39 UTC
Labels: Story
