### ISSUE TITLE
Email field filtering with case insensitive contains operator

### ISSUE THREAD

**Issue by Jkrzy** [18F/crt-portal#839] opened 2020-12-16 14:07 UTC
From: https://github.com/usdoj-crt/crt-portal/pull/770#pullrequestreview-552870415

As an intake specialist, I want to be able to search across `contact_emails` without **always** entering the specific email I'd like to filter for so that I can perform more flexible searches of reports in the system.

@Jkrzy  said:
> I'd love to take this opportunity, or at least create a card to consider, to change how we're handling email searching on the backend as well.
> 
> As-is we're doing a [full-text search](https://docs.djangoproject.com/en/2.2/ref/contrib/postgres/search/) on the `contact_email` column but I think something like `__icontains` would be more appropriate.
> 
> Email-like strings are going to be considered a single token by `to_tsvector` which means someone needs to enter the exact email they're trying to filter on. Searches for partial terms like "@gmail.com" will return no results.

Given 4 reports with `contact_email` as follows:
* test@gsa.gov
* test@gsa.gov
* tester@gmail.com
* testing@gmail.com

A user must be able to enter text fragments that return results found in the `contact_email` column. e.g. 
* a filter for "@gmail.com" should return two results
* a filter for "test" should return 4 results
* a filter for "test@gsa.gov" should return 4 results

Currently, a user must input the exact email they wish to filter on.

We'll know we're done when
- [ ] We're using `_icontains` to filter the `contact_email` field

**Comment by blaughman** [comment] 2020-12-22 13:24
Function works as intended on both Chrome and Edge.  Moving to UAT.

**Comment by randyabramson** [comment] 2020-12-22 21:40
Function works as intended on both Chrome and Edge on Staging. Nice work @Jkrzy !

**Comment by blaughman** [comment] 2020-12-29 18:41
Function works as intended in staging prior to production release.

**Comment by randyabramson** [comment] 2020-12-30 00:17
Tested on Prod in CHROME and EDGE. Closing

**Closed** 2020-12-30 00:17 UTC
