### ISSUE TITLE
Assign newly submitted record to ELS

### ISSUE THREAD

**Issue by UchMok** [18F/crt-portal#74] opened 2019-07-23 14:05 UTC
## Narrative
As a DOJ CRT user, I want employment-related complaints to route to ELS so that they can readily address and assess the violation.

## Background
The Employment Litigation Section (ELS) is responsible for enforcing Title VII of the Civil Rights Act against state and local government employers.  This prohibits discrimination in the workplace based upon race, sex (including pregnancy), religion and national origin.  ELS also enforces the Uniformed Services Employment and Reemployment Act (USERRA) which prohibits workplace discrimination because of past, present or future military obligation.
## Assumptions
- Conditional logic questions for workplace are developed

## Out of scope 
- Redirecting to EEOC
## Acceptance criteria
- Given a complainant is submitting a complaint

|WHEN Primary Issue is|(AND)WHEN Conditional logic selection is|(AND) WHEN Protected Class is|THEN 'Routed column' in the View all table as|
|---------------|:-----------------|:--------------------|:-----------------|
|Workplace discrimination or other employment-related problem|Public or Private and any size|Any(other than Immigration/Citizenship, National Origin, Language and Disability)|ELS|

##### Exception
**All responses with hate crime or human trafficking go to CRM**

|WHEN Primary Issue is|(AND)WHEN Conditional logic selection is|(AND) WHEN Protected Class is|THEN 'Routed column' in the View all table as|
|---------------|:-----------------|:--------------------|:-----------------|
|'Workplace discrimination or other employment-related problem|Public or Private AND any size employees|Immigration/Citizenship, National Origin, Language|IER|
|'Workplace discrimination or other employment-related problem|Public OR Private AND any size| Disability|DRS|

## Mockups / Wireframes

https://app.zenhub.com/workspaces/doj-crt-form-design-flows-5d7a67fa86a8cd0001581ea0/issues/18f/crt-django/47

Content Source of Truth:
https://docs.google.com/document/d/1bxSRc9CQOHjQhTaYkHncE4tykUEFeC6RzFtP5IQk0Ic/edit?ts=5de6f69e

## Sign Off
Story Sign off
- [x] PO
- [x] ELS
UAT Sign off
- [ ] PO

**Comment by el-mapache** [comment] 2020-01-07 18:06
@lalitha-jonnalagadda As a small clarification, is the DRS routing out of scope, or should I just include it here? I don't think it will represent a significant increase in the amount of effort.

**Comment by lalitha-jonnalagadda** [comment] 2020-01-07 23:12
@el-mapache - Generally for the routing stories, I include both the use case and the exception as @LindsayYoung wanted. So for this story, its the ELS use case only. @LindsayYoung please correct me if I am wrong.

**Comment by blaughman** [comment] 2020-01-10 16:20
Complaints are routing as intended (aside from the physical harm question) in IE 11 and Chrome.  Moving to UAT.

**Comment by lalitha-jonnalagadda** [comment] 2020-01-10 19:57
Demo'ed this functionality to the deep dive sections on 1/9.

**Closed by lalitha-jonnalagadda** 2020-01-10 19:57 UTC
Labels: Story
