### ISSUE TITLE
Assign a complaint to an individual staff within a section

### ISSUE THREAD

**Issue by Jacklynn** [18F/crt-portal#209] opened 2019-12-04 20:13 UTC
## Narrative
As an intake specialist, I would like to assign a complaint to a specific staff member so that they can assign ownership of processing the complaint

## Background
Sections receive complaints through various digital and non- digital formats. Once received, sections try to distribute complaints amongst members in their departments (by state, but jurisdiction, by type, etc) to allow for faster processing.

## Assumptions
- Assignee list will be populated once a user logs into the portal. If a name is not visible in the portal, it can be remedied by having the user sign into prod. 

## Out of scope
- Filtering complaints by assignee
- Removing an assignee on the complaint

## Acceptance Criteria
1. Given that I'm on the complaint details page
When I am in the activity panel
Then I see a new drop down called 'Assignee'

2. Given that I'm in the actions panel
When I start typing a name in the assignee dropdown, 
Then I see that the names matching the characters I entered will show up in the drop down 
AND
I'm able to select a user from that list and hit apply changes

3. a11y
- [ ] A user can assign someone using keyboard only (guessing arrow keys to move up an down the suggestion list, spacebar/enter/tab to selected, escape to exit the list without saving)
- [ ] Field label is announced when field is active
- [ ] Suggestion list is announced so that a user knows that there are options to choose from when they're typing for a screen reader.  Ex: User types `a` and screen reader announces `six results are available` because there are six names appearing in the suggestion.
- [ ] user is able to confirm selection if they're using a screen reader (field reads input).

[Here is some auto-complete documentation I found](https://haltersweb.github.io/Accessibility/autocomplete.html). 

## Tech notes
- we will try using.a type ahead and test functionality with keyboard only access. If that doesn't work, then we will default to the drop down as in the mocks 

## Mock ups
![image.png](https://images.zenhubusercontent.com/5b34455c5b51b10bd4dd59d6/32f3a0da-47c5-47e9-a43a-67c15ffd59aa)
## Sign off
- [x] PO
UAT 
- [x] PO
- [x] Product Design
- [ ] a11y
[placeholder. We've seen this is an important process to sections towards getting work done and following up.]

**Comment by lalitha-jonnalagadda** [comment] 2020-04-10 21:18
#38 is a duplicate. Closing #38

**Comment by blaughman** [comment] 2020-04-28 12:03
Function works as intended.  Ready for deploy.

**Comment by Jacklynn** [comment] 2020-04-28 18:28
a11y
- I noticed that when I re-enter a field where there's already a name selected it says "mis-spelled" which might be confusing. Is it possible to turn off that announcement? 
- the "successfully assigned to" notification didn't read out for me in Safari + VO after hitting "apply changes". How do I trigger it?

cc @Jkrzy @LindsayYoung

**Comment by LindsayYoung** [comment] 2020-04-28 20:37
- I can't reproduce the "mis-spelled" error, can you screen shot it or show me?
- Missing status updates is tracking in [442](workspaces/doj-crt-intake-scrum-board-5d03bf56c1c8a35d482eca0f/issues/18f/crt-portal/442))

**Comment by Jacklynn** [comment] 2020-04-28 22:25
@LindsayYoung we can watch what happens when terri tests it on friday with JAWS/NVDA too

Steps to repo:
1. VO + Safari (voice over works better with safari than Chrome)
2. select a name
3. Leave the field by clicking somewhere else
4. Click on the assignee field again, hear it say  "misspelled" before reading out the name.

**Closed** 2020-05-05 23:41 UTC
Labels: Must, Story, release 5-5-20
