### ISSUE TITLE
Add Spanish translation for "Submission Complete"

### ISSUE THREAD

**Issue by timoballard** [18F/crt-portal#909] opened 2021-03-17 20:18 UTC
Card [882](https://app.zenhub.com/workspaces/doj-crt-intake-scrum-board-5d03bf56c1c8a35d482eca0f/issues/18f/crt-portal/881) changed the title of the submission confirmation page to "Submission complete".

We need to incorporate the Spanish translation of that text, which is:

Envío completo

**Comment by blaughman** [comment] 2021-03-25 13:19
Function appears as intended in Dev.  Moving to UAT.

**Comment by randyabramson** [comment] 2021-03-31 13:02
Works as expected on staging

**Comment by randyabramson** [comment] 2021-04-06 21:12
I don't see any reports completed in Spanish yet to verify the name change live, but I will continue to monitor

**Closed** 2021-04-06 21:12 UTC
