### ISSUE TITLE
Confirmation print tweaks

### ISSUE THREAD

**Issue by cantsin** [18F/crt-portal#868] opened 2021-01-20 21:48 UTC
# Edits

## Type sizes aren't printing correctly
- I put a saved PDF into Sketch to compare, below are the sizes (from dev on right), everything is smaller than it should be
-  If it's not possible to get these exact, we should at least make some of the emphases better, like "Report successfully submitted" should stand out more

![Screen Shot 2021-01-20 at 5.57.32 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/c62ed303-8efa-49d8-b277-2ea011113cb4)

## Type size updates
After seeing how it's printing, I do think we can revise some of the sizes I suggested originally to be smaller and save space
- **CHANGES**: 
- "Thank you for submitting..." and "What to expect" headers can all be 20px, 28px leading (get rid of larger 24px size)
- Numbers and subheads under "What to expect" like "1. We review your report" should be 14px instead of 16px
- Body copy can stay 12px but could have tighter leading (16px instead of 18px)
![Screen Shot 2021-01-21 at 12.46.36 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/abfd6e0d-4439-4fae-a653-cab45b8ea351)

## DOJ header
- is it possible to make it like it is in the mockup? Centered and on two lines, with "civilrights.justice.gov" below?
- Could also remove the "Civil Rights Division" since the line below says "Thank you for submitting a report to the civil rights division"

### Options:
![Screen Shot 2021-01-21 at 12.13.03 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/6dbce824-2dc8-407a-bdee-2a0759fc4339)
![Screen Shot 2021-01-21 at 12.13.33 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/1d9f9355-b926-472c-a9c1-ee851c051740)

### Currently
![Screen Shot 2021-01-21 at 12.15.04 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/1d475f58-023e-4bba-bfd9-984253bc369d)

## Box around confirmation number is wonky
Is it possible to center the icon and type?

### Currently
![Screen Shot 2021-01-21 at 12.54.20 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/61970493-aefa-42be-a236-ab3c93d8e76f)

### Should be
![Screen Shot 2021-01-21 at 12.55.00 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/5d8714b8-24d5-4bc6-abce-6b73af19eb40)

## Page margins and text alignment
- Can we make the margins for the page bigger so the paragraphs aren't as long?
- Text under subheads should align with subhead, not the number
- Numbers in circles are not centered
- Short dividers under headers are missing 
- Can we make a line break between "Thank you for submitting a report" and "to the Civil Rights Division"?

### Comparison (mockup on left)
![Screen Shot 2021-01-21 at 1.00.05 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/87bacc3f-19f4-458e-ac62-9b17726220e2)

![Screen Shot 2021-01-21 at 1.00.44 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/d65b6f0e-0ae0-4689-af0b-6e3e4fa1c35e)

## Spacing for report information is too tight, makes something look broken
- Is it possible to get rid of some of the repeat headers? Like "You Name" twice?

### Currently
![Screen Shot 2021-01-21 at 1.02.14 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/b2bcd4a2-f0a0-4d3f-b011-784d753fbb84)

### Should be more like
![Screen Shot 2021-01-21 at 1.03.28 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/2540e399-2258-4c59-b754-b8b1a1d0fc3d)

**Comment by cantsin** [comment] 2021-01-25 23:41
Re: `Is it possible to get rid of some of the repeat headers? Like "You Name" twice?`

This question has been asked before but unfortunately changing this is not easy. I know this repetition makes the information harder to parse. I've adjusted the spacing again, hopefully it's somewhat better now.

**Comment by blaughman** [comment] 2021-02-02 17:39
@timoballard @ilodidoj @Jkrzy @randyabramson I noticed a random quotation mark on the printout.  Other than that, this looks good.
![image.png](https://images.zenhubusercontent.com/5d2390b2c408a2441fc2874d/1a2b5cfe-0e96-4215-989e-e2312a7e8320)

**Comment by timoballard** [comment] 2021-02-02 17:42
Good eye @blaughman! We can get that cleaned up before cutting the staging release today

**Comment by blaughman** [comment] 2021-02-02 19:57
Function works as intended in Chrome and Edge.  Moving to UAT.

**Closed** 2021-02-09 21:46 UTC
