### ISSUE TITLE
As a CRT user, I want to know who created a proform record

### ISSUE THREAD

**Issue by Jacklynn** [18F/crt-portal#427] opened 2020-03-31 18:52 UTC
## Narrative

As a CRT intake specialist, I would like to see who created the complaint so that I can understand if the originator for the complaint was internal CRT members or the general public

## Assumptions
- When a complaint is created via the online portal, then the 'created by' is displayed as a 'Public User' 

## Acceptance Criteria

1. Given that I'm on the complaint details page of a 'new' complaint 
When I'm at the Activity section
Then I see:
  - Email of the user (originator) of the complaint 
  - Timestamp when the complaint was created
  - An entry into the activity log - 'New complaint created'

2. Given that I'm on the proform 
When I select an intake format and submit a complaint
Then in the activity panel of the new complaint, I see a new entry showing the intake format of the complaint 

## Mock ups

![image.png](https://images.zenhubusercontent.com/5b34455c5b51b10bd4dd59d6/03b498bc-676a-41f8-840d-cc81f5f2c313)

**Comment by Jkrzy** [comment] 2020-04-13 14:23
Implementation issue I'd love to get @LindsayYoung and @hbillings input on...

Our [activity stream implementation](https://django-activity-stream.readthedocs.io/en/latest/) requires that `Actor` be a model instance from the database. 

Therefore, to capture creation from a `Public User` in the activity stream, we'll need a create a `User` to represent non-authenticated folks submitting via the website. 

I saw we ran into this issue before with `Report.author` and addressed it by using a `CharField`, which unfortunately isn't possible w/ activity stream :sad:

A few implementation options that came to mind...
- Creating a shared user record --`User.objects.get_or_create(username='Public User', is_active=False)`
  - Updating `author` to be a `ForeignKey`
- **Not** creating an entry in the activity stream for `AnonymousUsers`

Any strong feelings/thoughts?

**Comment by LindsayYoung** [comment] 2020-04-13 16:40
Yea, I think there could be some downsides to making and managing dummy accounts. If we were to do that, I would want to review and probably tighten some of our permissions structures. 

Option 3 might be "faking" the log since we have the information.  So, formatting the author with submission date and time, and  "created this record from intake_type" as the last thing on every activity stream box.

**Comment by Jkrzy** [comment] 2020-04-13 20:11
Option 3 feels reasonable and preferable to trying to handle what amounts to a shared user account. I'll work up a PR. Thanks Lindsay!

**Comment by blaughman** [comment] 2020-04-16 16:16
Function works as intended.  Moving to UAT.

**Closed** 2020-05-05 23:41 UTC
Labels: Feedback, release 5-5-20
