### ISSUE TITLE
[View all table] Status filter should allow you select multiple statuses at a time

### ISSUE THREAD

**Issue by Jacklynn** [18F/crt-portal#390] opened 2020-03-23 23:36 UTC
## Narrative
As a CRT user, I need to view all records that haven't been closed so I can take action on them.

## Acceptance Criteria

Given I am on the view all table 
when I am looking at the filter area
then I should see "New" "Open" and "Closed" as persistent filters with a checkbox beside each option

Given I am on the view all table
when I see the "New" "Open" and "Closed" persistent filters with a checkbox
then I should see "New" and "Open" checkboxes selected as the default value

Given I am on the view all table
when the "New" and "Open" checkboxes are selected as the default value
then only the records that haven't been closed are seen in the view all table

Given I am on the view all table
when I click the "Clear All Filters" link
then I see all records on the view all table.

## Problem
Currently the status filter only lets you filter by a single status at a time
![Screen Shot 2020-03-23 at 8.41.12 AM.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/77eb03e7-5f17-4d65-8506-747fe2691f2b)

### Expected
Being able to select multiple statuses to filter by, if a section wanted to see all the new and open, for example. 
https://gsa.invisionapp.com/share/53XK51LUWT4#/screens/420265438_1-View_All_Updated

- By default, New and Open checkboxes are checked
![Screen Shot 2020-07-02 at 6.18.03 PM.png](https://images.zenhubusercontent.com/5b34455c5b51b10bd4dd59d6/72a3ea6a-10fa-4079-ad99-21cb18bfb74c)

The status checkboxes are located above all other filters
![image.png](https://images.zenhubusercontent.com/5d2390b2c408a2441fc2874d/266f37f4-a50f-4108-8a9f-b760521bac61)

**Comment by Jacklynn** [comment] 2020-05-22 22:06
@lalitha-jonnalagadda

**Comment by hakhalid11** [comment] 2020-07-28 21:09
@blaughman I finished the functionality for this card however for default loading of status I had to tweak some stuff. Let me know your feedback and if it my solution works for this card.

So on page load I added in default statuses to new and open like the below screenshot

![image.png](https://images.zenhubusercontent.com/5efb8164bf9ea016ca6016f2/6ef6d77e-8f13-4c2f-a849-865a96402c4c)

However when a user clears the status filters and page refreshes there is no way for me to know if the page refresh is from clear all filters or from first page load.

To fix this issue I had to create a pseudo status that only stays on the front end but is used to denote if statuses have been cleared or not. So in the same scenario if a user clicks clear all filters the URL will have a no_status=false in it (We are not tied to no_status as the parameter name, We can change it if need be).

![image.png](https://images.zenhubusercontent.com/5efb8164bf9ea016ca6016f2/4b558dd6-525a-4c59-b4dc-9cc867e6f1bf)
![image.png](https://images.zenhubusercontent.com/5efb8164bf9ea016ca6016f2/5139c9b0-467c-449f-9479-0ea807838bd4)

I think this is the best solution to this problem and I have submitted a pull request for this card.

**Comment by lalitha-jonnalagadda** [comment] 2020-07-28 21:34
Ah! This is a good one that doesn't seem to have an AC. @hakhalid11 - you want to know the behavior when some one clicks the 'Clear filters' button. In this case, technically when you hit the clear all button, then no records will be shown as all statuses have been unchecked. So the question for @blaughman would be - What should(if any) should happen to the complaint list when the user clicks 'clear all filters'. We have two options:

- Display all complaints irrespective of the status - so show 'New', 'Open' and 'Closed' complaints OR
- Display no records and let the user make a selection in the filters first

FWIW - the current version of the view all table lists **'ALL'** records when filters are cleared.

**Comment by blaughman** [comment] 2020-07-29 12:54
@hakhalid11 @lalitha-jonnalagadda I think we should replicate the current experience and display all records when the filters are cleared.

**Comment by blaughman** [comment] 2020-08-04 19:59
Function works as intended.  Moving to UAT.

**Comment by blaughman** [comment] 2020-08-19 12:08
Deployed to Prod on 8/18/20.

**Closed by blaughman** 2020-08-19 12:08 UTC
Labels: Must, Release 8-11-20
