### ISSUE TITLE
[Bulk actions] Assign multiple records to a single assignee at once

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#575] opened 2020-06-08 19:22 UTC
## Narrative
As a CRT user, I want to assign multiple records to a single assignee at one time so that I don't have to process each individual record and I will save time.

## Acceptance Criteria
1) Given I am on the view all table
when I look in the header of the table
then I see a 'square' icon to the left of the text 'Incoming records' 

2) Given I am on the view all table
when I click on the 'square' icon
then the 15 displayed records matching my selected filters are automatically selected 
AND
when I click on the 'square' icon once all displayed records are selected
then all records will be unselected.

3) Given I am on the view all table
when I select a checkbox for any or all records
then I see a 'Bulk Actions' button appear in the header to the right of 'Incoming records'

4) Given I have selected records in the view all table
when I click the 'Bulk Actions' button
then I am taken to a new page called 'Bulk Actions"

5) Given I am on the Bulk Actions page
when I look at the top of the page I see the complaint intake level chrome which includes 'Back to All' button and 'Add New Record' button
AND
I see a "Bulk Actions" label centered at the top of the page
AND
then I see a message indicating "You have selected x records for bulk action.  Who do you want to assign these records to?"

6) Given I am on the bulk actions page
when I look to the left side of the page
then I see an 'Assigned to' field with type ahead capabilities
AND
I see a button below labeled 'Apply Changes'

7) Given I am on the bulk actions page
when I add an assignee to the 'Assigned to' field
AND I click 'Apply Changes'
then I see a confirmation message indicating, "You have assigned x records to y user"
AND
the activity log is updated for each impacted record.

8) Given I am on the bulk actions page
when I have assigned all records to y user
AND 
I click 'Back to All'
then I click 'Back to All' to be returned to my previously filtered data.

## Assumptions
- The 'Assignee' box will operate in the same manner as it does on the complaint detail page.
- Other icons/functions will be added to the menu bar going forward.
- A column of checkboxes will take the place of the column for status on the view all table.
- The 'status' column will replace the 'Routed' column once card 621 merges.
- A selection over an amount of 500 records will trigger a timeout error.
- The activity log is updated with the action taken for each affected record.  (Bulk Action?)

**Comment by ilodidoj** [comment] 2020-09-03 14:10
What happen once user select the icon for 'Assign to User' function? UI mocks for modal of selecting assignee or how this should work in terms of UI?

**Comment by blaughman** [comment] 2020-09-03 15:14
@cantsin @Jkrzy @ilodidoj @hakhalid11 @randyabramson  I took a stab at this story.  If you have a moment, please look this over and let me know if there are any questions or concerns.  Thanks.

**Comment by randyabramson** [comment] 2020-09-03 16:28
@blaughman - wondering if some of these new icons will overlap with the 'quick view' carrot that we were talking about?

**Comment by randyabramson** [comment] 2020-09-03 16:34
@blaughman assuming you can only 'bulk assign' on what is currently in view, which is 15 entries. So, the limit you can bulk assign at once is 15, correct?

**Comment by randyabramson** [comment] 2020-09-03 16:49
* Notes for meeting with Bill:

* Do we need the 'action' icon and menu at this point? Can we just get away with the assign to user icon appearing when complaints are selected? I'm thinking we are talking about doing this now because we will add more functions down the road, right?

* If we use the action icon, can it be greyed out until a user selects at least one record?

* I'm not sure what the 'Assignee table' is, In development?
 
* On 'assignee table', shouldn't the button say 'assign' and not Update Changes?

* I think the screen grab of the 'all actions' menu would be helpful here.

**Comment by randyabramson** [comment] 2020-09-03 19:22
Notes:

1. AC for 'are you sure?'
2. AC for '15 records will be impacted' message + 'TBD records will be effected'
3. Icons at top or TEXT?
3. Possibility for future 'un-do' feature

**Comment by cantsin** [comment] 2020-09-03 23:05
Note that we are adding a caret (`>`) for quickview, so we'll need to figure out where the checkboxes live, otherwise it's going to be easy to accidentally expand a row instead of selecting a row.

**Comment by randyabramson** [comment] 2020-09-04 11:01
Worked on these mocks last night...reviewing with Bill today[https://app.zenhub.com/files/183258764/bd5dc135-2454-4b7b-ba7d-abaa7767d2af/download](https://app.zenhub.com/files/183258764/bd5dc135-2454-4b7b-ba7d-abaa7767d2af/download)

**Comment by randyabramson** [comment] 2020-09-04 12:03
@cantsin Yes...I had the same concern! Is it even possible to have the carrot and check box side by side? If so, are we confident that there would be excessive user error where users are checking/expanding unintentionally?

**Comment by randyabramson** [comment] 2020-09-09 20:17
Version 2.0 of the mocks/user flow here:[https://app.zenhub.com/files/183258764/628a6672-92bb-43c4-97be-447160d95547/download](https://app.zenhub.com/files/183258764/628a6672-92bb-43c4-97be-447160d95547/download)

**Comment by randyabramson** [comment] 2020-09-10 17:10
V3 of mocks here. I included a 'coder's choice' for a Bulk Actions drop down or Bulk Assign button. Either is fine for us. Bulk Actions Drop Down is good for future state, but adds ACs, etc.

[Uploading... bulk-actions-v3.docx ]

**Comment by randyabramson** [comment] 2020-09-10 17:12
BTW - We ran the above mocks by two service folks today and they were very happy with the mocks/flow.

**Comment by cantsin** [comment] 2020-09-21 18:15
@blaughman @randyabramson 

Some notes/questions:

- What should the activity log say for each report? Should it follow the generic `Assigned to "james"` format or, perhaps, `Bulk assigned to "james"`? Or, `Bulk assigned to "james" by "bill"`? 

- I am also adding a special logging event so that we can track bulk assigns (in the case of inadvertent confirmation, errors, etc). This will be available through the cloud.gov log console. @Jkrzy should I add something else here?

- When submitting (posting) form data, the usual web behavior is to redirect to another page. I am following this standard here -- in other words, if the user has chosen any action on the bulk assign page, they are redirected back to the filter page (whether they choose "cancel", "back to all", "assign" or "assign all"). I think this makes the UX a bit smoother, but I'm open to alternatives.

Thoughts?

**Comment by blaughman** [comment] 2020-09-21 18:31
@cantsin @randyabramson 
My thoughts:
1) I think following the generic format is fine for this function "Assigned to James..."'
2) Adding this event is great for allowing us to backtrack on records affected by bulk actions.  This also allows us to keep the activity generic from the first bullet you mentioned.
3) This behavior makes complete sense and would operate in a manner I would expect.

Thanks again for the great work.  I would like to see if Randy agrees on my assumptions.

**Comment by randyabramson** [comment] 2020-09-21 18:43
@cantsin @blaughman 

All of the above is good by me. My only questions is if there is value in denoting that something was part of a bulk assign in the logs. It sounds like adding the event in cloud.gov is helpful. Just throwing out the idea that it might be helpful to sort bulk assigns in the logs as well.

@cantsin what's your advice here?

**Comment by cantsin** [comment] 2020-09-21 21:56
@randyabramson we should log as much as possible imo :sweat_smile: (whilst ensuring that no PII is logged)

Currently we have activity logs for each report individually, so it's a bit hard to do "global" activity logs, which is where cloud.gov comes in -- by default cloud.gov collates logs at a application level instead. 

Happy to add more logging where-ever desired: on the application level or the report level. I don't think we have any other granularity here (@Jkrzy please correct me if I'm wrong).

Does this help?

**Comment by randyabramson** [comment] 2020-09-22 00:50
Thanks @cantsin 

It doesn't sound like there is much value as assigning something as part of a 'bulk assign' in the logs and will it will be repetitive with the labeling on Cloud.gov, so let's keep everything as @blaughman stated.

Thanks!

**Comment by blaughman** [comment] 2020-09-30 15:18
Function works as intended in Chrome and Edge.  Moving to UAT.

**Closed** 2020-10-07 01:14 UTC
