### ISSUE TITLE
Form Letter for Repeat Writers

### ISSUE THREAD

**Issue by danielhyi** [18F/crt-portal#650] opened 2020-07-23 00:18 UTC
Drafting form letter to upload to respond to repeat writers. 

In the 'Contact Complainant' menu of form letters please add the following:

CRT - Constant Writer 
[https://app.zenhub.com/files/183258764/70b15d7a-dc96-444b-8f66-57dc592bf431/download](https://app.zenhub.com/files/183258764/70b15d7a-dc96-444b-8f66-57dc592bf431/download)

CRT - Constant Writer (Spanish)
[https://app.zenhub.com/files/183258764/2019acca-f4cb-40c3-93eb-f48884650a73/download](https://app.zenhub.com/files/183258764/2019acca-f4cb-40c3-93eb-f48884650a73/download)

**Comment by blaughman** [comment] 2021-03-08 14:17
Function works as intended in Chrome and Edge.  Moving to UAT.

**Closed** 2021-03-10 01:49 UTC
