### ISSUE TITLE
Assign newly created record to SPL

### ISSUE THREAD

**Issue by UchMok** [18F/crt-portal#92] opened 2019-08-06 19:42 UTC
## Narrative
As a DOJ CRT user, I want special litigation-related complaints to route to SPL so that they can readily address and assess the violation.

## Background
The Special Litigation Section enforces violations affecting the following areas: 1) the rights of people in state or local institutions, including: jails, prisons, juvenile detention facilities, and health care facilities for persons with disabilities; 2) the rights of individuals with disabilities to receive services in their communities, rather than in institutions; 3) the rights of people who interact with state or local police or sheriffs' departments; 4) the rights of youth involved in the juvenile justice system; 5) the rights of people to have safe access to reproductive health care clinics; and 6) the rights of people to practice their religion while confined to state and local institutions.

## Assumptions
- Conditional logic questions for workplace are developed

## Acceptance criteria
- Given a complainant is submitting a complaint

|WHEN Primary Issue is|(AND)WHEN Conditional logic selection is|(AND) WHEN Protected Class is|THEN 'Routed column' in the View all table as|
|---------------|:-----------------|:--------------------|:-----------------|
|'Mistreated by police, law enforcement or correctional staff| In prison or correctional facility|Any Protected class other than Disability|SPL|
|Discriminated against in any other commercial or public place| Healthcare facility|Any Protected class other than Disability|SPL|

##### Exception

|WHEN Primary Issue is|(AND)WHEN Conditional logic selection is|(AND) WHEN Protected Class is|THEN 'Routed column' in the View all table as|
|---------------|:-----------------|:--------------------|:-----------------|
|'Mistreated by police, law enforcement or correctional staff| In prison or correctional facility|Disability|DRS|
|'Mistreated by police, law enforcement or correctional staff| Outside a prison or correctional facility|Any Protected class other than Disability|CRM|
|'Mistreated by police, law enforcement or correctional staff| Outside prison or correctional facility|Disability|DRS|
|Discriminated against in any other commercial or public place| Anything other thanHealthcare facility|Any Protected class other than Disability|HCE|

## Mockups / Wireframes

https://app.zenhub.com/workspaces/doj-crt-form-design-flows-5d7a67fa86a8cd0001581ea0/issues/18f/crt-django/47

Content Source of Truth:
https://docs.google.com/document/d/1bxSRc9CQOHjQhTaYkHncE4tykUEFeC6RzFtP5IQk0Ic/edit?ts=5de6f69e

## Sign Off
Story Sign off
- [x] PO
- [x] SPL
UAT Sign off
- [ ] PO

**Comment by UchMok** [comment] 2019-08-20 17:10
@blaughman can you follow up with SPL on the question in this user story?

**Comment by blaughman** [comment] 2019-08-22 16:10
[CRIPA ISSUES - UPDATED.pdf](https://github.com/18F/crt-portal/files/3530987/CRIPA.ISSUES.-.UPDATED.pdf)

**Comment by lalitha-jonnalagadda** [comment] 2019-11-29 18:00
@blaughman and @UchMok - This card is closed. is this supposed to be closed or  closed by accident?

**Comment by lalitha-jonnalagadda** [comment] 2020-01-08 16:12
Updated the AC's to reflect the second SPL routing logic and exceptions.

**Comment by lalitha-jonnalagadda** [comment] 2020-01-30 15:10
Did a quick desk check and one of the exceptions isn't passing: 

|WHEN Primary Issue is|(AND)WHEN Conditional logic selection is|(AND) WHEN Protected Class is|THEN 'Routed column' in the View all table as|
|---------------|:-----------------|:--------------------|:-----------------|
|'Mistreated by police, law enforcement or correctional staff| Outside a prison or correctional facility|Any Protected class other than Disability|CRM|

Looks like this is routing to ADM - https://crt-portal-django-dev.app.cloud.gov/form/view/208/?next=%3Fper_page%3D15%26sort%3D-create_date%26page%3D1

**Comment by LindsayYoung** [comment] 2020-01-30 18:36
Updated the CRM card. Good catch.

(For the listed exceptions, we generally,  just make sure they don't go to the subject of the card since we don't always know if the final routing for the exceptions is done yet.)

**Comment by blaughman** [comment] 2020-02-04 16:10
Function works as intended.  Moving to UAT.

**Comment by lalitha-jonnalagadda** [comment] 2020-02-10 16:14
Showcased during deep-dive on 2/6.

**Closed by lalitha-jonnalagadda** 2020-02-10 16:14 UTC
Labels: Story
