### ISSUE TITLE
Set focus when opening modal

### ISSUE THREAD

**Issue by Jkrzy** [18F/crt-portal#614] opened 2020-07-01 13:20 UTC
When opening the modal for `contacting complainant`, or any other modal, we should set the focus inside of the modal. 

When navigating via keyboard a user should be able to immediately interact with the modal after opening without having to tab through the remainder of the page.

### Implementation notes
I think we could do this right in modals.js's `openModal` function.

**Comment by blaughman** [comment] 2020-07-07 18:42
Function works as intended.

**Comment by blaughman** [comment] 2020-07-15 16:26
Deployed 7/14/20 closing card.

**Closed by blaughman** 2020-07-15 16:26 UTC
Labels: Release 7-14-20
