### ISSUE TITLE
Filter by record number - View all table

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#192] opened 2019-12-04 17:41 UTC
## Narrative
As a DOJ CRT user, I want to be able to filter complaints by complainant ID so that I can only view a subset of the complaints I prefer to take relevant action on. 

## Background
All sections at DOJ, receive about 93K complaints annually. With this kind of volume, it's difficult to locate and look up complaints. Filtering by name will allow the intake specialists to look up a list of all complaints by a complainant. 
 
## Acceptance Criteria

1) Given that I'm on the view all table
When I'm at the Filter by record number 
Then I see free form text box to enter a complaint ID
AND
I see a 'Filter Results' option

2)  Given that I'm on the view all table
When I don't select any filter option
Then I see all complaints as the default view

3) Given that I'm on the view all table
When I enter a complaint ID or any portion of the complaint ID in the  'Complaint ID' filters and click the 'Filter Results' button
Then I see the view all table filters to display all records matching the ID 
AND
I see a tag/label with the filtered criteria by the filtered data

4) Given that I filtered the results by a Complaint ID
When I click 'X' on the tag/label 
Then I see the view all table to display all complaints 

5) Given that I filtered data by contact name AND there are no records for that section
Then I see a message warning me about why there are no records showing
AND 
back and forward pagination arrows are disabled

6) Given that I've applied a filter and have reach the end of all the pages for a given filter (ex: less than 15 or on the final page of pagination)
Then I see a message confirming that I've reached the end of records and to change filters to see more. 

## Mockups
![Viewall-Contact Name.png](https://images.zenhubusercontent.com/5b34455c5b51b10bd4dd59d6/c889baa2-3edc-489e-9708-ed09046b62f1)

No records for a filter
![Filter-no records.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/dc577451-6e77-4cd6-97b6-d82799db4341)

Records with less than 15 filter
![Filter-less than 15.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/df3414e1-0e7b-4847-ae8b-304420903eef)

## Sign off
- [x] PO
### UAT sign off 
- [x] PO
- [x] Product design
- [ ] a11y

**Comment by blaughman** [comment] 2020-04-23 14:56
Function works as intended in Chrome, Edge and IE 11.  Moving to UAT.

**Comment by Jacklynn** [comment] 2020-04-28 17:18
@LindsayYoung would we want it to be more forgiving at all? Like being able to find search if you don't have the hyphen? I'm sure most people will copy and paste, just wondering.

**Comment by Jacklynn** [comment] 2020-04-28 17:23
A11y:
The filter reads "remove public id" (_pronounced ih-d, like Freud_) on a screen reader. Can it read the same thing as what's shown, "Complaint ID"  

The filter label reads I.D. correctly, for what it's worth.

**Closed** 2020-05-05 23:41 UTC
Labels: Story, release 5-5-20
