### ISSUE TITLE
Assign newly submitted record to IER

### ISSUE THREAD

**Issue by UchMok** [18F/crt-portal#73] opened 2019-07-23 14:05 UTC
## Narrative
As a DOJ CRT user, I want employment-related complaints to route to ELS so that they can readily address and assess the violation.

## Background
The Immigrant and Employee Rights Section (IER), enforces the anti-discrimination provision of the Immigration and Nationality Act (INA).
This law prohibits the following four practices:

1.  citizenship status discrimination in hiring, firing, or recruitment or referral for a fee
2.  national origin discrimination in hiring, firing, or recruitment or referral for a fee
3.  unfair documentary practices during the employment eligibility verification, Form I-9 and E-Verify
4.  retaliation or intimidation - an employer may not adversely effect an employee for filing with IER

## Assumptions
- Workplace conditional logic questions are developed #195
## Out of scope
- Routing to EEOC

## Acceptance criteria
- Given a complainant is submitting a complaint

|WHEN Primary Issue is|THEN 'Routed column' in the View all table as|THEN 'Routed column' in the View all table as
|---------------|:--------------------|:-----------------|
|Workplace discrimination or other employment-related problem|Immigration/Citizenship AND/OR National Origin AND/OR Language|IER|

##### Exception

**All responses with hate crime or human trafficking go to CRM**

|WHEN Primary Issue is|THEN 'Routed column' in the View all table as|(AND) WHEN Protected Class is|THEN 'Routed column' in the View all table as
|---------------|--------------------|-----------------|---------
|Workplace discrimination or other employment-related problem|Anything other than Immigration/Citizenship AND/OR National Origin AND/OR Language |ELS

## Mockups / Wireframes

https://app.zenhub.com/workspaces/doj-crt-form-design-flows-5d7a67fa86a8cd0001581ea0/issues/18f/crt-django/47

Content Source of Truth:
https://docs.google.com/document/d/1bxSRc9CQOHjQhTaYkHncE4tykUEFeC6RzFtP5IQk0Ic/edit?ts=5de6f69e

## Questions
- 
## Sign Off
Story Sign off
- [x] IER
- [x] PO
UAT Sign off
- [ ] PO

**Comment by LindsayYoung** [comment] 2019-12-23 18:26
Noting we wanted to double check on language, would workplace discrimination on language also go to IER?

**Comment by lalitha-jonnalagadda** [comment] 2019-12-26 14:48
@LindsayYoung - Checked with Jenny on language and yes, workplace discrimination on language will go to IER as well. I updated the AC's.

**Comment by blaughman** [comment] 2020-01-06 17:17
Function works as intended in IE 11 and Chrome.  Moving to UAT.

**Comment by LindsayYoung** [comment] 2020-01-07 23:21
@lalitha-jonnalagadda wanted to flag that we are seeing an additional exception since we completed this ticket. I wanted to confirm that workplace as primary complaint + disability will go to DRS
As documented in:
https://github.com/18F/crt-portal/issues/74

The DRS ticket doesn't have this, but that card is not ready yet so I made a note:
https://app.zenhub.com/workspaces/doj-crt-intake-scrum-board-5d03bf56c1c8a35d482eca0f/issues/18f/crt-portal/72

cc @el-mapache

**Comment by lalitha-jonnalagadda** [comment] 2020-01-10 19:55
Thanks for the heads up @LindsayYoung . I updated the DRS card with routing workplace+disability scenario and hate crime exception. Closing this card.

**Closed by lalitha-jonnalagadda** 2020-01-10 19:55 UTC
Labels: Story
