### ISSUE TITLE
Tell DOJ CRT what happened (free form)

### ISSUE THREAD

**Issue by UchMok** [18F/crt-portal#69] opened 2019-07-23 13:55 UTC
## Narrative
As a Public User
I want to tell DOJ CRT what incident took place in free form
So That I can provide details and fully express what I believe happened to me in my own words and potentially obtain relief

## Background
The violation summary allows DOJ CRT to determine whether a complaint has merit. Historically, CRT has received violation summaries that are not helpful in determining merit, because they are too verbose (+30 pages) or vague.

A lot of users used to rely on attachments to explain their incident and tell CRT to 'see attached'. This field will direct them to 'use their words' to fully describe their problem.

This user story will allow the user to expand on the discriminatory event beyond the structured form categories

## Assumptions
- user will be able to sufficiently explain themselves in 500 words or less (character limit)
- users will know how many words they have remaining to describe their problem
- violation summary is optional

## Out of Scope
- no spell check
- formatting options

## Acceptance criteria 

1)
Given I'm a public user filling out the complaint intake form
When I am on the second step of that wizard
Then I view that
- that second step is called 'Details' and is filled in
- I am on a page called 'Please provide details on what happened' (refer to [Mockup](https://app.zenhub.com/workspaces/doj-crt-form-design-flows-5d7a67fa86a8cd0001581ea0/issues/18f/crt-django/56) for full content and spacing expectations

AND

- I view a text box, where I'm allowed to describe what happened
AND
- I view a word counter below the box that says I have '500 words remaining'
AND
I view options to move forward/back on this form

2) 
Given I'm on the second step, Details, of the complaint intake form
When I want to describe my problem in 350 words
Then I can write 350 words in the text box
AND view that the counter says '150 words remaining'

3) 
Given I'm on the second step, Details, of the complaint intake form
When I want to describe my problem in 501 words
Then I'm only allowed to write up to 500 words
AND
I see an alert that says, "500 word limit reached" (see Mockup for styles)

4) 
Given I'm on the second step, Details, of the complaint intake form
When I've written a summary of my problem in 500 word or less
OR
When I've written *nothing* in the text box
Then I am able to click 'Next' and proceed to the next part of the form

5) 
Given I'm on the second step, Details, of the complaint intake form
When I've attempted to copy and paste in a complaint of 1000 words
Then I view the first 500 words of my copy-and-paste
AND
I see an alert that says, "500 word limit reached" (see Mockup for styles)

## Mockups / Wireframes
![All Path - Freeform.jpg](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/257559ea-41ed-473b-a973-a55970ac5522)
![All Path - Freeform.jpg](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/516f9b1a-4529-4fc4-9df1-5256a609151e)

## Technical Notes
Made the character count 7,000, that will be the fallback if someone disables the javascript or or otherwise tries to get around counting spaces. That many characters would allow someone to write `Onomatopoeia. ` 500 times so it would be unlikely someone who stuck to 500 words would be incorrectly flagged.

**Comment by alexsoble** [comment] 2019-09-23 19:14
The story says ... "When I am on the 5th step of that wizard", but I believe this should be the second step, not the 5th.

**Comment by alexsoble** [comment] 2019-09-26 16:30
I will own this feature.

— @LindsayYoung, since I'll be OOO on Friday and Monday, maybe you can help push it forward while I'm OOO!

— @ilodidoj ... excited to pair with you on this story.

**Comment by alexsoble** [comment] 2019-09-26 19:20
Link to source-of-truth design board: https://app.zenhub.com/workspaces/doj-crt-form-design-flows-5d7a67fa86a8cd0001581ea0/issues/18f/crt-django/56.

**Comment by LindsayYoung** [comment] 2019-09-27 15:32
Work started here https://github.com/usdoj-crt/crt-portal/pull/74

**Comment by alexsoble** [comment] 2019-10-01 14:48
I'll be code-reviewing the functionality only, will then open a new PR to address styling.

**Comment by Jacklynn** [comment] 2019-10-08 17:05
@alexsoble @LindsayYoung 

Here are some things I found using voiceover/screen reader tools check (didn't check for other things yet)
- Add label to free form field, It’s reads “[edit text],[blank], main” on voice over
Suggest label as the same as the title folks are given: Please describe what happened in your own words
- Read out characters remaining. Suggesting using the [last example on this page](http://pauljadam.com/demos/aria-atomic-relevant.html) where it’s read out ‘polite’ then ‘assertive’ if you get closer to the word limit. (Alerts can set to different levels depending on how important they are). 
-- More documentation on alerts: https://developer.paciellogroup.com/blog/2012/06/html5-accessibility-chops-aria-rolealert-browser-support/
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_alert_role
- Alert warning that character max has been reached doesn’t read out, would expect it to read out when seen.
-- Maybe you could do something like Example 2: Scaled feedback on this page https://www.w3.org/WAI/tutorials/forms/notifications/# (maybe this works for the example below too)
- Remove the space between the quotes in the blank alt tag (DOJ label-- it’s reading as unlabeled instead of skipped, sorry I thought there was a space but it’s just the monospaced coding font that tripped me up.

**Comment by Jacklynn** [comment] 2019-10-08 20:49
* Adding bypass blocks to standard-layout pages so users can skip to main content. This would affect all the pages. ref https://www.w3.org/TR/WCAG20-TECHS/G1

**Comment by alexsoble** [comment] 2019-10-10 16:13
Fixes for a11y issues here: https://github.com/usdoj-crt/crt-portal/pull/90

**Comment by Jacklynn** [comment] 2019-10-10 23:51
(let me know if I should capture this on another story) 
- Terri mentioned page titles and I noticed that all our HTML titles are `<title>U.S. Department of Justice - Civil Rights Division</title>` and we could make them more tied to where the person is in the process. Best practice is to have the unique information first. 
Maybe we could have the pattern.... [step] + "Contact the Civil Rights Division" so `Details - Contact the Civil Rights Division`

ref: https://www.w3.org/WAI/test-evaluate/preliminary/#title

**Comment by lalitha-jonnalagadda** [comment] 2019-10-11 18:17
@Jacklynn for 👆🏼(title changes) let's make it a new story so we can move this one to dev done and we can work on the changes as a new entry.

**Comment by alexsoble** [comment] 2019-10-11 18:21
I like @lalitha-jonnalagadda's suggestion above!

@Jacklynn, when you have a chance to check out the new screen-reader functionality in VoiceOver — if the functionality looks good, would you mind moving this card over to the Dev Done column? From there we'll go to UAT! 

If there are still remaining issues with the screen-reader experience, we'll address those before moving to Dev Done.

Thank you for your VoiceOver help!!

**Comment by Jacklynn** [comment] 2019-10-15 17:15
@lalitha-jonnalagadda I think that's a great idea, I thought the comments were kind of muddled. I created a card with these here: https://app.zenhub.com/workspaces/doj-crt-intake-scrum-board-5d03bf56c1c8a35d482eca0f/issues/18f/crt-portal/156

**Comment by blaughman** [comment] 2019-10-18 15:18
I tested the freeform page in IE 11 and it worked as intended.

**Comment by Jacklynn** [comment] 2019-11-13 00:00
@blaughman @lalitha-jonnalagadda @UchMok From the deep dive we heard compelling value statements for having this be a Required (not optional) field in order. Was this considered before moving to "Customer Sign off"? Is it something we're just going to monitor?

We had explicit feedback from HCE & IER, but haven't heard from others.

**Comment by lalitha-jonnalagadda** [comment] 2019-11-25 15:54
Closing this card as we finished review with the deep dive group.

**Closed by lalitha-jonnalagadda** 2019-11-25 15:54 UTC
Labels: Story
