### ISSUE TITLE
External page message when a user goes to a non-doj website

### ISSUE THREAD

**Issue by Jacklynn** [18F/crt-portal#610] opened 2020-06-29 23:51 UTC
Issue:
DOJ policy says users should be informed they're leaving a DOJ website.

Example of current experience:
![Screen Shot 2020-06-24 at 4.09.38 PM.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/94f464cb-b488-4162-912e-363647bf90c9)

**Comment by Jacklynn** [comment] 2020-06-30 16:36
@lalitha-jonnalagadda I think we need to work on the design of this still. I also feel like the language is off-putting

**Comment by lalitha-jonnalagadda** [comment] 2020-06-30 21:36
@Jacklynn - Card #532 has 3 design options and from a similar implementation on other justice.gov interactions, design from option A on that card would work.

**Comment by blaughman** [comment] 2020-07-13 15:40
Function works as intended in Edge and Chrome.  Moving to UAT.

**Comment by blaughman** [comment] 2020-07-13 16:47
@cantsin @harikrishnagit @Jacklynn I tested on justice.gov for the time it takes for a redirection to occur, and the end result is 5 seconds.  https://www.justice.gov/usao/social-media-directory

**Comment by Jacklynn** [comment] 2020-07-13 19:00
![External link version C Copy 3](https://user-images.githubusercontent.com/2560618/87342430-17e86700-c500-11ea-8c70-46c13e6bc141.jpg)

- Proposing updating time to **20 seconds** before auto-redirect. 
- Adding "continue" button if users are ready before hand (do we have this spanish translated? 🥺
- Make sure title/heading reads out when the modal opens. ? On the [example](https://www.w3.org/TR/wai-aria-practices-1.1/examples/dialog-modal/dialog.html) I found, “modal title” and then “Address”. So ours would be….“You are now leaving the DOJ website, Back”

_(How I calculated the time:
- Avg reading speed is 200-400 wpm, the dialog has 57 words
-  I calculated time for the low end of the reading speed, 200, for 57 words (=about 17seconds)
- I added 3 seconds (recommended by internet)_

**Comment by cantsin** [comment] 2020-07-20 21:08
@blaughman I think this one is a duplicate of https://app.zenhub.com/workspaces/doj-crt-intake-scrum-board-5d03bf56c1c8a35d482eca0f/issues/18f/crt-portal/532 -- there's nothing we need to do here, afaics. (But please correct me if I'm wrong!)

**Comment by lalitha-jonnalagadda** [comment] 2020-07-21 17:05
@blaughman closing this card as it is a duplicate to #532

**Closed by lalitha-jonnalagadda** 2020-07-21 17:05 UTC
