### ISSUE TITLE
CRT user ability to remove attached files from the complaint detail page

### ISSUE THREAD

**Issue by timoballard** [18F/crt-portal#885] opened 2021-02-17 13:28 UTC
## Narrative
As a CRT user, I want to remove attached files from the complaint detail page.

## Acceptance Criteria
1) Given I am on the complaint detail page
when I look below the 'New comment' card
then I see a card labeled 'Attachments'
AND a list of attached files for this complaint
AND a trash-2 icon to the right of each attached file.

2) Given I am on the complaint detail page, 'Attachments' card
when I click on a particular attached file from the list
then a system dialogue appears allowing me to download the file to my local workstation.

3) Given I am on the complaint detail page
when I click on the trash icon next to an attachment
then the attachment is removed from the record
AND the activity log is updated.

### Assumptions
1. The Dialogue box asks me to confirm that I want to delete the attachment (yes/no)
2. Deleted attachment actions are recorded in the activity log (include the file name that was deleted and the user name of the person who deleted it)

**Comment by blaughman** [comment] 2021-02-17 14:53
@timoballard @ilodidoj @randyabramson @emilycryan Would it make sense to click to confirm the remove function?  I'm thinking the "Are you sure you want to remove this file?"

**Comment by emilycryan** [comment] 2021-02-17 16:26
@blaughman I'm always for confirmation during the delete process. It should definitely be part of the flow. 

cc @randyabramson @timoballard @ilodidoj

**Comment by timoballard** [comment] 2021-02-19 20:59
As a part of this work, we should investigate adding the ability to cancel an in-flight upload.

**Comment by randyabramson** [comment] 2021-03-15 14:51
@timoballard @blaughman 

I am not seeing the trashcan on staging for https://crt-portal-django-stage.app.cloud.gov/form/view/665/

Am I missing something?

![no-trach.PNG](https://images.zenhubusercontent.com/5ef156d51dd4f26e61414bbf/5f163593-52a2-45d0-be19-7269e48fb054)

**Comment by blaughman** [comment] 2021-03-17 15:56
Function works as intended in both Chrome and Edge.  Moving to UAT.

**Comment by randyabramson** [comment] 2021-03-17 22:06
Worked as expected on Staging

**Comment by blaughman** [comment] 2021-03-18 15:59
Function works as intended.  File removed and activity log was updated.

**Closed** 2021-03-24 01:27 UTC
Labels: Pairing
