### ISSUE TITLE
Remove drop downs for name, record ID and summary filters

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#622] opened 2020-07-06 19:07 UTC
## Narrative
As a CRT user on the view all table, I would like the drop down menus removed and instead show the fields for "First Name," "Last Name," "Record ID," and "Summary" because I use these frequently and want to be more efficient.

## Acceptance Criteria
1) Given I am on the view all table
when I see the available filters
then I see the "First Name", "Last Name," "Record ID," and "Summary" are always shown and not drop downs

2) Given I am on the view all table
when I click on the box for "First Name", "Last Name", "Record ID", and "Summary"
then I can enter the information I am attempting to retrieve after clicking "Apply Filters"

3) Given that I'm on the view all table
When I'm at the Filter by first name
Then I see free form text box to enter a first name of a complainant
AND
I see a 'Apply Filters' option

4) Given that I'm on the view all table
When I enter a first name of a complainant in the 'first name' filter and click the 'Apply Filters' button
Then I see the view all table filters to display all records matching the first name
AND
I see a tag/label with the filtered criteria by the filtered data

5) Given that I'm on the view all table
When I'm at the Filter by last name
Then I see free form text box to enter a last name of a complainant
AND
I see a 'Apply Filters' option

6) Given that I'm on the view all table
When I enter the last name of a complainant in the 'last name' filter and click the 'Apply Filters' button
Then I see the view all table filters to display all records matching the last name
AND
I see a tag/label with the filtered criteria by the filtered data

7) Given that I'm on the view all table
When I'm at the Filter by Complaint ID
Then I see free form text box to enter a complaint ID number
AND
I see a 'Apply Filters' option

8) Given that I'm on the view all table
When I enter a complaint ID in the 'complaint ID' filter and click the 'Apply Filters' button
Then I see the view all table filters to display all records matching the complaint ID
AND
I see a tag/label with the filtered criteria by the filtered data

9) Given that I'm on the view all table
When I'm at the Filter by summary
Then I see free form text box to enter a word/phrase 
AND
I see a 'Apply Filters' option

10) Given that I'm on the view all table
When I enter a word/phrase in the 'summary' filter and click the 'Apply Filters' button
Then I see the view all table filters to display all records matching the word/phrase
AND
I see a tag/label with the filtered criteria by the filtered data

## Accessibility
-  For open fields
You can navigate to and use the element using keyboard only and it appears in the expected order
Element has appropriate contrast (including placeholder text)
Note: Don’t use placeholder text on the Public side, this is less user-friendly, assuming staff are both more forgiving and will be power users.
Field is labeled

## Mockup
![image.png](https://images.zenhubusercontent.com/5d2390b2c408a2441fc2874d/4b6d79ec-9b71-4bac-9a91-8d7e2cd8b9a8)

**Comment by harikrishnagit** [comment] 2020-08-04 21:06
@MattBowles8, Is the Incident Location drop down not a part of this ticket?

**Comment by blaughman** [comment] 2020-08-06 12:07
@harikrishnagit The incident location drop down is a separate ticket.  This card is only focusing on first name, last name, complaint ID and summary.

**Comment by blaughman** [comment] 2020-08-18 15:56
Function works as intended in Chrome and Edge.  Accessibility seems to work as intended as well.  Moving to UAT.

**Comment by blaughman** [comment] 2020-08-24 15:59
Filters work in both Chrome and Edge in Staging.

**Comment by blaughman** [comment] 2020-08-26 03:36
Deployed to Production on 8/25/20

**Closed by blaughman** 2020-08-26 03:36 UTC
Labels: Must, Release 8-25-20
