### ISSUE TITLE
Tell DOJ CRT my contact information [Physical Address] when I'm reporting on behalf of myself

### ISSUE THREAD

**Issue by UchMok** [18F/crt-portal#131] opened 2019-09-09 17:09 UTC
## Narrative
As a public user, I want to tell DOJ CRT where a potential civil rights violation occurred so that DOJ CRT can investigate my complaint. 

## Background
Sections correspond with complainants for further information that was provided initially or reach out for clarifications. These clarification happen over snail mail, requiring complainant's physical address. Of the volume of complaints that the CRT sections receive  roughly 99% mail correspondence in US, <1% international

## Out of scope

- Auto fill/predictive location/zip code look up
- Validation addresses against a location data source such as USPS API

## Assumptions

- We're only accepting incident locations in the US and US territories
- All address fields are mandatory

## Acceptance criteria
1) Given that I am filing a complaint 
when I'm on the 'Contact' page
then I see a section where I can enter my physical address 

3) Given I'm filling a complaint 
When I am on the Contact page
Then I see

|Field|Type|Optional/Required| Error Messages |
|------------|:-------------|:------------:|:-------------------:|
|Mailing Address 1|Free Form|Optional| Please enter the street address where this took place|
|Mailing Address 2|Free Form|Optional|
|City/Town|Free Form|Optional|Please enter the city or town where this took place|
|State|Type ahead Drop Down|Optional|Please enter the state where this took place|
|Zip|Free form|Optional|Please enter the zip where this took place|

- Follow default error handling methods to be followed

4) Given that I'm filing a complaint
When I'm on the contact page and click next without inputing information for more than one required field
Then I get an error message 'Please enter the required information to proceed'
AND
I'm not allowed to go to the next page

5. As a keyboard only user, i should be able to navigate to address fields by tabbing, it should show a clear focus around the highlighted field. I should be able to us any drop down components (ex: state selection) using keyboard only. 
 6. As a screen reader user, when the field is in focus, it should read out the field label ("Mailing address 1"). If using a combo box, I should be able to hear that it's a combo box, hear the options, and hear my selection. 

## Mockups / Wireframes
https://app.zenhub.com/workspaces/doj-crt-form-design-flows-5d7a67fa86a8cd0001581ea0/issues/18f/crt-django/40

![UPDATED Contact - Annotations Copy.jpg](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/412d0588-6def-417a-9ed3-0068eec8c662)

## Sign off:
Story sign off
- [x] PO 
UAT Sign off
- [ ] PO
- [ ] Product Design
- [ ] a11y

**Comment by UchMok** [comment] 2019-09-09 17:10
@Jacklynn Would it make sense to make Name optional, if physical address is going to be required or entered? cc @AvivaOskow

**Comment by Jacklynn** [comment] 2019-10-29 22:41
@UchMok CRT could substitute "Resident" for those without a name. An unofficial google search seems to tell me that USPS only requires the address, not a name. 
It would be nice of us to call out warnings like this in on the Submission review page though.

**Comment by lalitha-jonnalagadda** [comment] 2020-01-13 19:46
Validating physical address for accuracy is in scope for the thin slice.

**Comment by Jacklynn** [comment] 2020-02-14 23:02
@lalitha-jonnalagadda can you clarify what you mean by required? I thought, _if_ a user choses to add an address, they have to enter an valid address, but they don't have to enter an address at all.

**Comment by Jacklynn** [comment] 2020-02-14 23:08
Added a11y criteria assuming that it's a plain text fields. If they became interactive/automated, a screen reader user would have to know there was a suggested option and be able to select it with keyboard only.

@lalitha-jonnalagadda for what it's worth, USWDS has a standard address component that I expect we'd use. @AvivaOskow would have the latest designs/mocks

**Comment by LindsayYoung** [comment] 2020-02-18 19:50
Noting that the error messages aren't going to apply because they are are no longer required and the validation we do add will be in a separate ticket.

**Comment by blaughman** [comment] 2020-03-06 20:09
Function works as intended.  Moving to UAT.

**Comment by lalitha-jonnalagadda** [comment] 2020-03-09 15:36
Closing this card following our deep dive session on 3/5

**Closed by lalitha-jonnalagadda** 2020-03-09 15:36 UTC
Labels: Pairing, Story
