### ISSUE TITLE
Flag for 'section review'

### ISSUE THREAD

**Issue by randyabramson** [18F/crt-portal#822] opened 2020-12-08 11:05 UTC
### Objective: 
Align CTR resources to support 'actionable reports'

### Key Result: 
Identify 90% (or more) of the reports that start in the Portal, are reviewed by sections and go on to getting a DJ number in the ICM system

### User Story: 
As a product owner, I would like to be able to show management how many reports started in the Portal and were then flagged for 'section review' in each section.

### Acceptance Criteria:

1) Given that I am looking at an individual record
When I look in the 'actions' panel
Then I see a checkbox labeled 'Secondary Review'

2) Given that I am looking at an individual record
When I click inside the 'Secondary Review' box
Then I see a checkbox fill that box

3) Given that I am looking at an individual record
When I click inside the 'Secondary Review' box a second time
Then I see a checkbox disappear from that box

4) Given that I am looking at an individual record
When I click inside the 'Secondary Review' box AND click the APPLY CHANGES button
Then the 'section review' flag is recorded in our logs and in the activity panel

5) Given that I am looking at an individual record
When I click inside the 'Secondary Review' box AND click the APPLY CHANGES button
Then I see an updated status message in the top right that says 'Successfully flagged for Secondary Review'

### Assumptions
1. The above is for flagging individual reports. Bulk referrals will come in another ticket (if needed). Note that the 'section review' checkbox will not be present in the 'bulk action panel'.

2.  In some sort of report (could be the CSV export that we deliver to Anthony bi-weekly), we are able to see
- The report numbers that were flagged for section review
- The corresponding section that flagged the report(s)
- The corresponding date when the report was created (not flagged date)

## Technical Question(s)
- For AC 5, should we keep a simple validation message for this function and lump the specific validation to card 841?

**Comment by cantsin** [comment] 2020-12-08 20:50
We can add this checkbox to the CSV import, but I will have to think about how to figure out how to record the corresponding section that flagged the report.

**Comment by cantsin** [comment] 2020-12-08 20:51
Grabbing this one unless one of y'all wanted to do it @timoballard @Jkrzy

**Comment by cantsin** [comment] 2020-12-09 18:59
- Do we want to allow users to uncheck the `referred` flag?
- I'm making the following assumption (please correct me if I'm wrong) that any referred report will _not_ change sections thereafter. (If they do, I will have to record both the referral and the section at that time)

**Comment by randyabramson** [comment] 2020-12-09 19:10
@cantsin  - 

1. Yes, AC #3 says you can 'uncheck' the referred box
Given that I am looking at an individual record
When I click inside the 'referred' box a second time
Then I see a checkbox disappear from that box

2. Really good question. I think the chance of a section referring a report and then having it reassigned later is not impossible. With that said, I think we can record the referral and section both times and ask Anthony to de-dupe the results based on the report number, which will stay constant.

**Comment by cantsin** [comment] 2020-12-09 20:14
Thanks! I'm trying to determine if we should store every referral (or un-referral? de-referal?) that the user makes. Based on what I understand, I think we should keep track only the current referral (or not). 

To be a bit more specific, we'll add two pieces of information to the report: `referral` and `referred_section`. If the user checks referred, we store the current section as `referred_section`. If the user unchecks, we clear out both. If the report is subsequently transferred to another section, the referral (and `referred_section`) remains (alternatively, we can clear out both fields). To re-refer, the user would have to uncheck and then re-check `referral`. 

How does that sound?

**Comment by randyabramson** [comment] 2020-12-10 13:50
@cantsin Yes...the above makes sense. Again, I get that there's an edge case possibility that one report might be referred by two sections...but we will ask Anthony's group to de-dupe based on report number.

Also, 'date created' is already in the report, so I think we are good on that requirement.

Thanks for these questions and sorting it out with me.

**Comment by cantsin** [comment] 2020-12-10 16:57
Thanks! This has been a fruitful discussion. One small thing, I don't think we should allow more than one referral to a report -- either the report is referred or it's not. I think this makes the data model simpler (among other things, I'm not sure how we would track "other" referrals).

**Comment by randyabramson** [comment] 2020-12-10 21:15
I think I'm following you @cantsin.

I agree that a report is either referred or not. 

And I think we are saying the same thing on this scenario:

==

June 2020 - Report 5553 is referred by VOT
--> In export, we see Report 5553 marked as 'referred' and referred by section VOT

July 2020 - Report 5553 is changed to section HCE and still marked as 'referred'
--> In export, we see Report 5553 marked as 'referred' and referred by section HCE


==

Are we on the same page?

**Comment by randyabramson** [comment] 2020-12-11 19:06
@cantsin - apologies, but we had a change on the label name for the 'referred' box to 'section review.'

I made the changes above in the ACs. Apologies about this!

Let me know if you have any questions.

Randy

**Comment by cantsin** [comment] 2020-12-11 22:32
No worries re: label name. Easy to do.

Re: your example, I think 5553 should remain as referred to VOT, even if transferred to HCE? Otherwise we can just use the currently assigned section when doing CSV extracts?

**Comment by randyabramson** [comment] 2020-12-11 23:01
@cantsin  - you are right...thanks for helping me think that through --- it would be referred (now section review) for both HCE and VOT and we can de-dupe later.

Thanks again! Have a great weekend.

**Comment by cantsin** [comment] 2020-12-14 19:25
Looks like USWDS forces a checkbox to the _left_ for usability reasons. 

![2020-12-14_11-24.png](https://images.zenhubusercontent.com/5eb05c8e896abe15ccf6dfa3/2ae84ac6-00d9-4a2b-a364-085c1f8395f4)

It's not easy to flip the label and checkbox. Maybe we should have a dropdown instead?

**Comment by blaughman** [comment] 2020-12-23 18:05
Function works as intended in Chrome and Edge.  Moving to UAT.

**Comment by randyabramson** [comment] 2020-12-23 18:10
@blaughman let's remember that we need to make sure that these actions are recorded in the export. @ilodidoj is there any wat to test against that on Dev or Staging or do we need to wait for the live environment to test?

**Comment by ilodidoj** [comment] 2020-12-23 18:33
@randyabramson @blaughman i just checked in DEV export the two fields are part of the report data extract export. ![image.png](https://images.zenhubusercontent.com/5d374c9d0efb727bd5a01afd/92ecbe98-ca33-408e-b5e1-179e032d168a)

**Comment by randyabramson** [comment] 2020-12-23 18:37
Changing this to Sprint 35 so that it stays on our radar.

**Comment by randyabramson** [comment] 2020-12-23 18:39
Awesome! Thank you @ilodidoj

**Comment by blaughman** [comment] 2020-12-29 18:36
Function confirmed on staging prior to production release.

**Closed** 2020-12-29 21:48 UTC
