### ISSUE TITLE
Filter by reported issue

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#623] opened 2020-07-06 19:22 UTC
## Narrative
As a CRT user I want to filter by any publicly submitted information so that I can view all relevant records for any business need I may have.

## Acceptance Criteria
1)  Given I am on the view all table 
when I look in the filter area's first horizontal line
then I see the filters 'Contact FN', 'Contact LN', 'ID', and 'CRT summary' with two action buttons 'Apply Filters' and 'more filters'

2) Given I am on the view all table
when I look in the filter area's second horizontal line
then I see the filters 'Personal Description', 'Date', 'Classification', 'Assignee', and 'Incident Location'

3) Given I am on the view all table
when I click on the 'more filters' button
then a third line of filters appears with the filters 'Primary Issue', 'Reported Reason', 'Relevant Details', 'Hate Crime', and 'Servicemember' as dropdown boxes

4) Given I am on the view all table
when I select the dropdown box 'Primary Issue'
then I see the following selection options 
- [ ] Workplace Discrimination
- [ ] Housing Discrimination
- [ ] Education Discrimination
- [ ] Voting Discrimination
- [ ] Police / Correctional Misconduct
- [ ] Commercial / Public Discrimination
- [ ] Something Else

5) Given I am on the view all table
when I select the dropdown box 'Reported Reason'
then I see the following selection options with a checkbox beside each option (more than 1 can be selected)
- [ ] Age
- [ ] Disability
- [ ] Family / Marital / Parental Status
- [ ] Gender Identity
- [ ] Genetic Information
- [ ] Immigration / Citizenship Status
- [ ] Language
- [ ] Military Status
- [ ] National Origin
- [ ] Pregnancy
- [ ] Race / Color
- [ ] Religion
- [ ] Sex
- [ ] Sexual Orientation

4) Given I am on the view all table
when I select the dropdown box 'Relevant Details'
then I see the following selection options
- [ ] Place of Worship
- [ ] Commercial / Retail Building
- [ ] Healthcare Facility
- [ ] Financial Institution
- [ ] Public Space

4) Given I am on the view all table
when I select the dropdown box 'Hate Crime'
then I see the following selection options
- Yes

5) Given I am on the view all table
when I select the dropdown box 'Servicemember'
then I see the following selection options
- Yes

6) Given I am on the view all table
when I select the dropdown box 'Intake Type'
then I see the following selection options
- [ ] Web
- [ ] Phone
- [ ] Fax
- [ ] Letter

## Mockup
![image.png](https://images.zenhubusercontent.com/5d2390b2c408a2441fc2874d/1cee6e59-8294-4fc3-a985-4116d2725c01)

**Comment by cantsin** [comment] 2020-09-25 15:57
Few notes.

- `Primary Issue` verbiage is a bit long. Can we shorten the wording? Currently I have to embiggen this dropdown, looks like this (note that some lines still wrap over): 

![2020-09-25_08-53.png](https://images.zenhubusercontent.com/5eb05c8e896abe15ccf6dfa3/e9f78dbd-8a42-4ee4-b290-7c70bccd93a7) 

- For `Relevant Details`, I have a slightly different dropdown list (which comes from extant code). 
  - Place of worship or about a place of worship
  - Commercial or retail building
  - Healthcare facility
  - Financial institution
  - Public space
  - Other *(note that this option is not on the above list)*

- For `Intake Type`, I also have `Email` as an option.

Current screenshot:

![2020-09-25_08-41.png](https://images.zenhubusercontent.com/5eb05c8e896abe15ccf6dfa3/3cb38682-52d6-473c-9179-baefccb44ee6)

**Comment by blaughman** [comment] 2020-09-30 15:12
Function works as intended on Chrome and Edge.  Moving to UAT.

**Closed** 2020-10-07 00:32 UTC
