### ISSUE TITLE
[form letter] If no name (or not first name) use gender neutral salutation

### ISSUE THREAD

**Issue by Jacklynn** [18F/crt-portal#593] opened 2020-06-13 00:17 UTC
We wanted to move away from "Dear sir/madam" for the DOJ correspondence but it didn't make it into the first version.

Logic expected: 
Provided first and last name: `Dear John Doe`
Provided first name: `Dear John`
If no first name: `Thank you for your report`
If no first or last name: `Thank you for your report`

**Comment by blaughman** [comment] 2020-06-18 13:02
Function works as intended.  Moving to UAT.

**Comment by lalitha-jonnalagadda** [comment] 2020-07-01 21:11
Deployed on 6/30.

**Closed by lalitha-jonnalagadda** 2020-07-01 21:11 UTC
Labels: Release 6-30-20
