### ISSUE TITLE
View Complainant physical address on record detail page

### ISSUE THREAD

**Issue by UchMok** [18F/crt-portal#162] opened 2019-10-28 19:31 UTC
## Narrative
As a CRT User,
I want to view additional details of a complaint record
so that I can confirm if the complaint has merit

## Background
The complaint details allows DOJ CRT to determine whether they have jurisdiction to act over a complaint. 

## Assumptions
- Modular boxes are not collapsible or expandable

## Acceptance criteria
1) Given I am viewing a complaint on the view all complaints table
When I click on a complaint (row)
 Then I am directed to that complaint's record page

2) Given I've clicked on a complaint in the view all table
When I am viewing the 'complaint details' section
Then I see an address section
AND
I see the following information in the address section: 
- [ ] Mailing address 1 &2
- [ ] City
- [ ] State
- [ ] Zip

3) A user should be able to navigate through this page using a keyboard following a tab order that matches what's visually displayed (through the three links/buttons)

4) As a screen reader/low vision user....
 - [ ] I'm not sure how it's built, but I would expect to be able to associate data with the label (Using a table or maybe they're grouped) -- appears to be working this way now
- [ ] be able to resize page to 200% without needing bi-directional scrolling (overflow works)
- [x] Proper contrast ratios for all text & informative icons and buttons that aren't disabled (should be built into the design)
 

## Mockups

https://docs.google.com/document/d/1-HLdb21JA6_EuMHZTOi7KXFWWV4mT2Af54Tzzijl2E8/edit?ts=5e41ce91#heading=h.jcwe8b7ixsay

## Sign off
- [x] PO
UAT sign off
- [ ] PO
- [ ] Product Design
- [ ] a11y

**Comment by Jacklynn** [comment] 2020-02-14 23:11
Removed some of the a11y criteria that weren't relevant (like buttons)

**Comment by blaughman** [comment] 2020-03-26 14:19
Function works as intended.  Moving to UAT.

**Comment by lalitha-jonnalagadda** [comment] 2020-04-01 14:17
Showcased during deep dive on 3/19. Closing this card

**Closed by lalitha-jonnalagadda** 2020-04-01 14:17 UTC
Labels: Pairing, Story
