### ISSUE TITLE
Filter by personal description field

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#364] opened 2020-03-16 14:28 UTC
## Narrative
As a DOJ CRT user, I want to be able to filter complaints by personal description as described by the complainant so that I can only view a subset of the complaints I prefer to take relevant action on. 

## Background
All sections at DOJ, receive about 93K complaints annually. With this kind of volume, it's difficult to locate and look up complaints. Filtering by name will allow the intake specialists to look up a list of all complaints by a complainant. 

## Acceptance Criteria

1) Given that I'm on the view all table
When I'm at the Filter by personal description 
Then I see free form text box to enter a word or phrase from the personal description
AND
I see a 'Filter Results' option

2) Given that I'm on the view all table
When I enter a word/phrase in the  'personal description' filters and click the 'Filter Results' button
Then I see the view all table filters to display all records matching the location
AND
I see a tag/label with the filtered criteria by the filtered data

## Sign off
- [x] PO
### UAT sign off 
- [x] PO
- [ ] Product design
- [ ] a11y

**Comment by blaughman** [comment] 2020-05-11 14:52
Function works as intended in Chrome, Edge and IE 11.  Awaiting product design confirmation from @Jacklynn before moving to UAT.

**Comment by Jacklynn** [comment] 2020-05-11 15:49
Working for me!

**Closed** 2020-05-18 23:52 UTC
Labels: release 5-19-20
