### ISSUE TITLE
Edit 'reported complaint' section on complaint details page

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#465] opened 2020-04-22 22:38 UTC
## Narrative
As an intake specialist, I would like to edit the 'Reported Complaint' section on a complaint after its created so that I can correct or update the complaint based on feedback from the complainant.  

## Background
Upon receiving a complaint, sections often contact the complainant for additional information, which would require the intake specialists to have the ability to edit the original complaint to add new information. At time, complainants reach out to the sections to update their contact information so sections have the most recent data

## Assumptions
- All changes/edits will be captured in the activity log
- All fields in the reported complaint section can be edited at once
- Complainant's personal description MUST not be editable. 

## Out of scope
- Editing personal description

## Acceptance Criteria
1. Given that I'm on the complaint details page
When I am in the reported complaint section 
Then I see a pencil icon labelled 'edit' 
AND 
When I click on the 'edit' icon
Then I see the proform view with the following sections 

- Primary Issue
- Incident Location
- Personal Characteristics
- Incident date
- Relevant Details
- Service member question 

AND 
I see an option to edit all fields as well as a 'Save' or 'Cancel' option 

2. Given that I clicked on the 'edit' option 
When start typing new information 
Then I see the previous information replaced with the new information  
AND
I'm able to save my edits by clicking on the 'Save' button

3. Given that I clicked on the 'edit' option and make edits
When I click on the 'Cancel' button
Then all prior information is preserved

4. Given that I edited reported complaint information on a complaint
When I check the activity panel for that complaint
Then I see a log for the edits on the complaint 

5. a11y ( @Jacklynn please help!)

## Sign off
- [x] PO
UAT 
- [x] PO
- [ ] Product Design
- [ ] a11y

**Comment by lalitha-jonnalagadda** [comment] 2020-05-08 16:37
Notes from desk checks during stand up on 5/8: 

- When an intake specialist edits the primary issue on a complaint details page, the expected behaviour is:
 - The answers to relevant details questions prior to the edits will be shown (as drop downs )along with the new relevant detail questions
 - The answers to relevant details questions prior to the edits will be set to 'none' by default
 - The activity log will capture relevant details selections before and after the edit to

**Comment by blaughman** [comment] 2020-05-18 21:33
Function works as intended.  Awaiting product design before moving to UAT.

**Closed** 2020-05-18 23:52 UTC
Labels: Must, Story, release 5-19-20
