### ISSUE TITLE
Add 'service animal text to other 'primary concern' boxes

### ISSUE THREAD

**Issue by randyabramson** [18F/crt-portal#882] opened 2021-02-15 19:26 UTC

**Comment by emilycryan** [comment] 2021-02-16 14:57
The proposed content changes/updates: https://gsa.invisionapp.com/share/9K1073D152X7#/444766516_PrimaryIssue-ServiceAnimalOptions

**Comment by randyabramson** [comment] 2021-03-02 01:26
@emilycryan let me know if we can move this into ready for dev.

We should also brainstorm on how we'd measure for success on this one.

**Comment by emilycryan** [comment] 2021-03-02 13:29
@randyabramson If the text is approved, then it's ready for dev. NOTE: In a couple of places, the other bullets may have been rewritten in order to accommodate the placement and for language consistency across the groups. So all bullets need to be reviewed during dev to make sure it all makes sense.

**Comment by randyabramson** [comment] 2021-03-03 01:50
@emilycryan this looks right to me. Maybe we can clear the copy to the Deep Dive group this week as well. @blaughman any thoughts on other folk that might want to get a look at this before we go live? Maybe just send an FYI to Dan, @emilycryan 

Also, 2 grammar things:

1. Can we drop the periods at the end of bullets on this page? 
2. Also, dropping the one of the commas in the service animal bullets looks cleaner to me, but if I'm wrong grammatically, let me know:

Denied an accommodation for a disability, including not being allowed to have a service animal, in the work place

vs.

Denied an accommodation for a disability, including not being allowed to have a service animal in the work place

**Comment by emilycryan** [comment] 2021-03-05 18:12
@randyabramson @blaughman Here is the updated service animal language (includes "assistance animal" within housing) 

https://gsa.invisionapp.com/share/9K1073D152X7#/screens

**Comment by timoballard** [comment] 2021-03-17 14:37
@blaughman @randyabramson @emilycryan - do we have translations for these new items?

**Comment by randyabramson** [comment] 2021-03-17 14:43
@timoballard - they were included in the translation request coming from the FBI by 3/26. Can we go ahead with English for now and add the other languages in the next sprint? @blaughman can you connect with Marta on the Spanish translations?

**Comment by blaughman** [comment] 2021-03-17 14:43
@timoballard @randyabramson @emilycryan I'm checking with Marta about the translations.

**Comment by timoballard** [comment] 2021-03-17 14:46
Sounds good

**Comment by blaughman** [comment] 2021-03-18 11:48
@timoballard @ilodidoj @randyabramson Service animal translations are attached.[https://app.zenhub.com/files/183258764/679655b6-7818-4357-b27f-a5009868c6d4/download](https://app.zenhub.com/files/183258764/679655b6-7818-4357-b27f-a5009868c6d4/download)

**Comment by blaughman** [comment] 2021-03-25 13:21
Both English and Spanish versions appear as intended in Dev.  Moving to UAT.

**Comment by randyabramson** [comment] 2021-03-31 13:12
Both English and Spanish versions appear as intended on staging

**Comment by randyabramson** [comment] 2021-04-06 21:23
Text appears as expected on PROD

**Closed** 2021-04-06 21:24 UTC
Labels: Tech Task
