### ISSUE TITLE
Tell DOJ CRT when the discrimination took place

### ISSUE THREAD

**Issue by UchMok** [18F/crt-portal#70] opened 2019-07-23 13:56 UTC
## Narrative
As a complainant, I want to tell DOJ CRT the date the incident happened so that they can determine whether my complaint can be acted upon or not. 

## Background
The **last date of occurrence** is a very important part of CRT's analysis of incoming complaints. Some statutes enforced by CRT have time limitations and incidents that occur outside of that time frame may not be eligible for relief.

At most, sections need to know the month and year of occurrence.

## Assumptions
- Day is optional

## Out of scope
- Recurring incident questions (#239)

## Acceptance criteria

1. Given I'm filing a complaint and am on the 'Protected Classes' page
When I click 'Next'
 - [ ] Then I am on a new page called 'Date'
AND
 - [ ] View a page called 'When did this last happen?' w/ subtext (refer to latest mockup)
AND
 - [ ] I view three text entry boxes that allow me to enter the Month, Day (optional) and Year of my incident
AND
 - [ ] I view 'back' and 'next' buttons

2. Given I'm on the 'Date' page
When I click 'back'
 - [ ] I'm redirected back to the 'Protected Classes' page

3. Given I'm on the 'Date' page and have entered
 - Month but not year
 - Year but not month
 -  Neither year nor month
When I click 'Next'
 - [ ] I'm not allowed to move to the next page, because I have not entered an Incident Month and Year.
AND
 - [ ] I view an error message telling me to do so: `Please enter a month` and/or `Please enter a year`

4. Given I'm on the 'Date' page
When I enter Incident Year and Incident Month and Incident Day 
Then
 - [ ] I can only enter numeric
 - [ ] number limit for year is 4
 - [ ] number limit for day is 2 and less than 31
 - [ ] number limit for month is 2 and less than 13
 - [ ] I can only enter a collective date that is NOT in the future

5. Given I'm on the 'Date' page and have entered Incident Year and Incident Month and optionally, Incident Day 
When I click 'Next'
Then I am directed to the 'Details' page

## Questions
-  Is anything lost by not asking for the date range? I don't want to ask for something unnecessarily but I'm wondering if it's helpful to CRT (and therefore public) users.
- Can this be a month/year picker vs manual entry? 

## Mockups / Wireframes
![When.jpg](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/60214ded-c292-4e43-9fb1-ca4721cbb1db)

Content Source of Truth - https://docs.google.com/document/d/1bxSRc9CQOHjQhTaYkHncE4tykUEFeC6RzFtP5IQk0Ic/edit#

## Sign off
- [x] PO
UAT Sign off
- [ ] PO

**Comment by lalitha-jonnalagadda** [comment] 2019-12-04 19:48
Incident date and the duration for the incident occurrence. Date is important for CRT to determine jurisdiction.

**Comment by Jacklynn** [comment] 2019-12-19 00:16
What do you think of these versions? (1) is an update where we're only asking for latest date (which might be hard to understand) and (2) is what we had before and have shown to users.

![Screen Shot 2019-12-18 at 4.15.06 PM.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/db06f886-e3ad-4aef-a22b-6c548ba49123)

**Comment by Jacklynn** [comment] 2019-12-23 16:51
I kept iterating on this and I think this is even clearer. I got some feedback on this from my crit group as well. We were asking for the date range before and a question i have is **"Is anything lost by not asking for the date range?"** I don't want to ask something of users unnecessarily, but if it's helpful to CRT/Public users we can add it back in.

![School Path 3C Copy 4.jpg](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/69c44509-a064-47fd-95f8-5e58b4292337)

**Comment by Jacklynn** [comment] 2019-12-31 18:27
Bill/Jacklynn:
- Date matters more and less to different sections. CRM is 5 years, Employment is ~180 days. 
-- Maybe even Month is optional? 
-- Alerts for shorter timeframe, helping those folks.
- "Ongoing" is helpful because it lets folks know that there is more wiggle room in terms of the deadline. (plus subject matter)
- Using `~` to indicate in-exact dates

Q: Can we build around the pathway they're coming from:
_EX:  if Employment, THEN require date._

**Comment by lalitha-jonnalagadda** [comment] 2020-01-02 18:36
@Jacklynn @UchMok - is the 'When' aka 'Date' page after location page or protected classes page? I think its after the protected class page and before the details page. If that is true, then we might need to update the mock and AC.

**Comment by Jacklynn** [comment] 2020-01-02 22:30
^ was asked in slack, but yes, it's before the freeform details page

**Comment by Jacklynn** [comment] 2020-01-03 23:52
I updated the mock to make the headings more consistent.
I also updated the M/D/Y part to match the styles Aviva created before the holidays: 
![Hierarchy Patterns.jpg](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/84205df7-1be7-4544-b242-c8766f4c15fc)

**Comment by LindsayYoung** [comment] 2020-01-08 21:26
https://github.com/usdoj-crt/crt-portal/pull/237

**Comment by LindsayYoung** [comment] 2020-01-14 15:47
FYI: this is pretty close to being done there are just some CSS tweaks

**Comment by lalitha-jonnalagadda** [comment] 2020-01-16 16:18
I know this one is not up for desk check just yet, but I was doing a walkthrough with EOS on the potential routing and I realized that the placement of the 'when' page is off. It should be *after* the protected classes page, but is now before the protected classes page on dev. CC @LindsayYoung @el-mapache

**Comment by el-mapache** [comment] 2020-01-16 16:21
@lalitha-jonnalagadda Cool, I'll fix it

**Comment by blaughman** [comment] 2020-01-17 17:39
Function works as intended in IE11 and Chrome.  Moving to UAT.

**Comment by lalitha-jonnalagadda** [comment] 2020-01-17 20:43
Moving this card back to dev done as we need to incorporate the following AC:

- Given that I am on the 'date' page
When I enter a year before '1900'
Then I see an error message - 'Please enter a year after 1900' 

CC @Jacklynn @AvivaOskow - Please change the copy of the error message as you see fit

**Comment by Jacklynn** [comment] 2020-01-18 00:46
That works for me @lalitha-jonnalagadda

**Comment by lalitha-jonnalagadda** [comment] 2020-01-21 18:59
Notes from the desk check during stand up:
- Error messages when no data is entered are mushed up
  - Copy for error message when year is past 1900 needs to be revised

**Comment by blaughman** [comment] 2020-01-22 20:17
Function works as intended. Moving to UAT.

**Comment by lalitha-jonnalagadda** [comment] 2020-02-10 16:17
Showcased during deep-dive on 2/6.

**Closed by lalitha-jonnalagadda** 2020-02-10 16:17 UTC
Labels: Story
