### ISSUE TITLE
Bulk printing success message must reflect number of selected reports

### ISSUE THREAD

**Issue by Jkrzy** [18F/crt-portal#783] opened 2020-11-17 14:31 UTC
Origin: https://github.com/usdoj-crt/crt-portal/pull/742#pullrequestreview-531771199

Upon printing reports the application renders a success message containing the number of selected reports. 

Currently, when you select Print first 100 reports the generated success message says

> Selected correspondent, issue, description for 15 reports

This message should reflect and confirm the user's actions on the previous page. 

"Printed `<fields>` for `<report count>` reports"

**Comment by blaughman** [comment] 2020-11-20 18:47
Function works as intended.  Moving to UAT.

**Closed** 2020-12-01 22:21 UTC
