### ISSUE TITLE
Text hover links on dark backgrounds not enough contrast

### ISSUE THREAD

**Issue by Jacklynn** [18F/crt-portal#619] opened 2020-07-06 15:55 UTC
**Issue:**
On hover, the text links on a dark background don't have enough contrast: 
![Screen Shot 2020-07-06 at 8.43.59 AM.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/3d60d131-1552-4a44-b335-d87cdaa5763f)

Also expected the icons" to change colors and be part of the clickable area.

There are the links from the landing page:
- please call 9-1-1 or local police.
- contact the FBI (plus icon)
- Availability of Language Assistance Services (plus icon)
- Footer links (About the division, etc)

**Proposed:** 
Changing the hover color for the icon and text to be  `'blue-warm-30v'` `#81AEFC` for the **hover** state for dark backgrounds only. (On light backgrounds, the hover for text should be blue-50, #2378C3)

Example:
![Screen Shot 2020-07-07 at 4.39.27 PM.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/9ce17dd5-27ef-471e-87d0-35e1fe2392fc)

**Comment by Jacklynn** [comment] 2020-07-07 20:16
I actually noticed this is all links on a dark background on this page. The FBI, call 911, and and the footer links

**Comment by Jacklynn** [comment] 2020-07-07 20:27
@AvivaOskow for final color.

**Comment by AvivaOskow** [comment] 2020-07-07 20:54
Final color edited above in description!

@harikrishnagit I'm not sure if you've used the USWDS color token system before, but instead of just adding this color as a hex code, we should be pulling it directly from the USWDS. If you don't know about this, @cantsin or @hbillings can you explain?

_(Also, I'll need to update the guide with the new sass variable for this one. I only had $theme-link-hover-color defined before, and now that one should just be for hover on light backgrounds, while this new one should be for dark backgrounds.)_

**Comment by harikrishnagit** [comment] 2020-07-07 20:57
I'll need help using USWDS scheme for colors. Looks like @cantsin is busy, can @hbillings help me in a pairing session?

**Comment by hbillings** [comment] 2020-07-08 20:07
@harikrishnagit This reference will be your best friend for USWDS colors: https://designsystem.digital.gov/design-tokens/color/system-tokens/

We have a bunch of theme colors defined in `static/sass/_uswds-theme-color.scss`.

To use them, you'll need to use USWDS' custom `color()` function. In the Sass code, you'll want to do something like this, probably in `typography.scss`:
```
a.your-class-for-light-link,
a.your-class-for-light-link:hover {
  color: color('blue-warm-30v'); // since this isn't in our theme color sheet, we can use the USWDS directly. If this were a theme variable, we would do something like color($theme-color-base-light)
}
```

Does that help? Let me know if you have other questions!

**Comment by blaughman** [comment] 2020-07-13 13:27
All hover states work as intended except for the 'please call 911...'
'

**Comment by harikrishnagit** [comment] 2020-07-13 14:56
@hbillings thanks for the link and tips. It helped. 
@blaughman I'll check it out.

**Comment by blaughman** [comment] 2020-07-13 15:39
@harikrishnagit @hbillings I tested this on staging and it is working as intended.  My previous testing was in the dev site.  This is good to go.

**Comment by cantsin** [comment] 2020-07-13 15:41
Hmm, do we have a regression on develop, then?

**Comment by Jacklynn** [comment] 2020-07-13 19:22
@blaughman I don't see it working in staging or dev with the new color

And this affects the following links:
- please call 9-1-1 or local police.
- contact the FBI (plus icon)
- Availability of Language Assistance Services (plus icon)
- Other footer links (About the division, etc - 15 total including the phone numbers)

**Comment by hbillings** [comment] 2020-07-13 20:28
I just took a look through the staging and dev sites and I don't see the classes added in [575](https://github.com/usdoj-crt/crt-portal/pull/575) showing up on either one. I've suspected for a while that we might have some weird caching issues going on somewhere, because this is not the first time that CSS has just disappeared on its way to being deployed.

I'll also note that 575 does not contain the necessary code to change the icon colors -- we need new SVGs for that, and that PR deals only with text colors.

**Comment by Jacklynn** [comment] 2020-07-13 21:55
@hbillings that's helpful to know about the icons, for some reason I thought svg icon colors could be changed

**Comment by cantsin** [comment] 2020-07-14 17:31
Update: staging _and_ dev now have the new colors. 

Do we want to add a new SVG icon for the hover element only? I'm leaning towards no, but I defer to design.

**Comment by Jacklynn** [comment] 2020-07-15 00:57
Looks good to me! Thank you!
let's skip the icons because I think it would also include extra work to make it part of the clickable area.

**Comment by blaughman** [comment] 2020-07-15 16:33
Deployed 7/14/20 closing card.

**Closed by blaughman** 2020-07-15 16:33 UTC
Labels: Bug, Release 7-14-20
