### ISSUE TITLE
Filter by assignee

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#437] opened 2020-04-10 21:18 UTC
## Narrative
As a DOJ CRT user, I want to be able to filter complaints by assignee so that I can understand who is working on the complaint.

## Background
All sections at DOJ, receive about 93K complaints annually. With this kind of volume, it's difficult to locate and look up complaints. Filtering by name will allow the intake specialists to look up a list of all complaints by a complainant. 
 
## Acceptance Criteria

1) Given that I'm on the view all table
When I'm at the Filter by assignee
Then I see typeahead dropdown with assignee names
AND
I see a 'Filter Results' option

2) Given that I'm on the view all table
When I enter a assignee name or any portion of the name in the assignee name filters and click the 'Filter Results' button
Then I see the view all table filters to display all records matching the name 
AND
I see a tag/label with the filtered criteria by the filtered data

## Sign off
- [x] PO
### UAT sign off 
- [x] PO
- [ ] Product design
- [x] a11y

**Comment by LindsayYoung** [comment] 2020-04-10 21:58
Just an idea, but what about replacing the not-so helpful "logout button" with a "view my records" link so you can go straight to the records assigned to you?

**Comment by lalitha-jonnalagadda** [comment] 2020-04-10 22:13
That works for me. In terms of design and placement, I'm not sure if that would work. @Jacklynn - Thoughts?

**Comment by blaughman** [comment] 2020-04-28 13:12
Function works as intended in Chrome, Edge and IE 11.  Ready for deploy.

**Comment by Jacklynn** [comment] 2020-04-28 18:22
Product design:
- Q: Why is it using a drop down instead of the same type to select (I think this was mentioned in standup as working on, but my audio was cutting a little). I think the same problem of there being a lot of people to choose from are here too. 
-- I wasn't expecting all the dashes here either, but not an issue if it changes to type ahead. 

- overflow issue for long names:
![Screen Shot 2020-04-28 at 11.21.46 AM.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/2fb94061-0888-4474-9874-b97f08186204)
-- I would expect it to just make the whole tag longer and keep the same left/right padding.

**Comment by LindsayYoung** [comment] 2020-04-28 19:17
- typeahead select isn't ready for this page. We need css updates for that - we should make a ticket for that. 

- Nice catch on the over-flow that would be an issue for all long filter tags- we can make a ticket for that.

**Comment by LindsayYoung** [comment] 2020-04-28 20:38
I can't reproduce the overflow issue ![Screen Shot 2020-04-28 at 1.11.46 PM.png](https://images.zenhubusercontent.com/56f1892d6caf56c9d38e1ac3/5bdad113-ef13-4094-af51-bb729bceb98d)

**Comment by Jacklynn** [comment] 2020-04-28 22:21
It might just be a safari thing, Chrome is working ok too. (I use safari to test voiceover)

**Comment by Jacklynn** [comment] 2020-04-28 22:29
@LindsayYoung I just saw your other comment above about replacing the logout button. I think that would be super helpful for folks in the future too and would love to do that too!

This filter also solves for the use case where intake specialist let reviewers know what work is overdue for their response. So someone looking up things assigned to someone else.

**Closed** 2020-05-05 23:41 UTC
Labels: Story, release 5-5-20
