### ISSUE TITLE
Remove extra semi-colon on Privacy page

### ISSUE THREAD

**Issue by randyabramson** [18F/crt-portal#680] opened 2020-08-24 17:29 UTC
On https://civilrights.justice.gov/privacy-policy, please remove the ";" at the end of the first bullet in the 'you should also know section'

So, change: "Any information you provide to us through this form is voluntary; to

"Any information you provide to us through this form is voluntary"

**Comment by Jkrzy** [comment] 2020-08-26 14:16
@randyabramson, the rest of the list items there have periods at the end of the sentences.

OK to include one here?

**Comment by randyabramson** [comment] 2020-08-26 14:30
@Jkrzy - good pick up. Yes...for consistency, please add a 'period'

Thank you!

**Comment by blaughman** [comment] 2020-08-28 11:46
Fixed.  Moving to UAT.

**Comment by blaughman** [comment] 2020-09-04 15:59
Function is as intended on Chrome and Edge in Staging.

**Closed** 2020-09-11 01:35 UTC
Labels: Release 9-8-20, Small
