### ISSUE TITLE
As a CRT user, I should be able to filter by a date range

### ISSUE THREAD

**Issue by Jacklynn** [18F/crt-portal#310] opened 2020-02-13 00:23 UTC
## Narrative
As a CRT user, I want to filter complaints within a defined date range.  This will allow me to manage workloads and spot trends.  

## Acceptance Criteria
1) Given that I am on the view all table
when I select the drop down filter for "Date"
then I see 2 data fields under the title of 'Submission Date' where I can input a date range in from and to fields

2) Given that I'm on the view all table
When I enter when I enter a date (mm/dd/yyyy) in the from and to fields and click the 'Apply Filters' button
Then I see the view all table filters to display all records matching the specified date range.
AND
I see a tag/label with the filtered criteria by the filtered data

Out of scope - Today function
Out of scope - Incident Date

## Assumptions
- Users can search a "Start Date" and "End Date"
- "Start Date" and "End Date" should all be in MM/DD/YYYY format
- Submission date will have all 3 fields.  

## Mockup
![image.png](https://images.zenhubusercontent.com/5d2390b2c408a2441fc2874d/83beed79-cf3d-44a5-987d-dca6e93ecad6)

![Screen Shot 2020-02-12 at 4.24.14 PM.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/35639178-9000-4f83-87af-6b3ec1affa57)

## Accessibility
- For drop downs
You can navigate to and use the element using keyboard only and it appears in the expected order; Element shows keyboard focus
This means opening, selecting, and closing. It’s expected that you can close a drop down by using the esc key
Changes made are announced

- For open fields
You can navigate to and use the element using keyboard only and it appears in the expected order
Element has appropriate contrast (including placeholder text)
Note: Don’t use placeholder text on the Public side, this is less user-friend, assuming staff are both more forgiving and will be power users.
Field is labeled

**Comment by Jacklynn** [comment] 2020-07-08 01:38
This very forgiving date text box was shared in a a11y newsletter, if it helps development at all: https://fymmot.github.io/inclusive-dates/

**Comment by harikrishnagit** [comment] 2020-07-24 22:32
@Jacklynn , we need a discussion on the date elements. Incident and received dates are managed as text fields in the model. When we build the views, those get matched as individual text field, not as on date field. 

copying @cantsin , @hakhalid11 @MattBowles8

**Comment by cantsin** [comment] 2020-07-25 00:05
@harikrishnagit we can take these text elements and create a `datetime` object if need be -- see `Report.last_incident_date` for an example. 

Or were you asking how to query all `Report`s given a date range? If we want to be fancy, we can create a [model manager](https://docs.djangoproject.com/en/3.0/topics/db/managers/) to wrap the conversion for us (or straight up do a query search for day/year ranges, using `__gte` or `__lte` filters, the query will necessarily be manual).

Did we ever discuss how to do a date range search with these reports that have no `incident_day`?

Side note, USWDS has a date range picker now: https://designsystem.digital.gov/components/form-controls/#date-range-picker

**Comment by harikrishnagit** [comment] 2020-07-27 19:04
Thanks @cantsin. These options could work. We talked this morning, and Bill suggested to use report submit date, not incident date because incident may or may not have days. Also recommended to remove incident date section from query. 

The date range picker will be useful.

**Comment by harikrishnagit** [comment] 2020-08-06 12:14
date input field has changed  contain calendar widget. This is done to minimize user errors, typos. this widget corrects most common typos. This is done as per @cantsin's recommendation. The flip side is that  display is in mm/dd/yyyy and the active filter display is in different format (yyyy-mm-dd). 

@blaughman, @randyabramson , let me know what you think, and if you want to have a conversation

**Comment by blaughman** [comment] 2020-08-14 14:12
The Edge experience is not user friendly. Any chance we can tweak this? ![image.png](https://images.zenhubusercontent.com/5d2390b2c408a2441fc2874d/8e93ba74-432e-4766-a18e-5b1565a4f819)

**Comment by blaughman** [comment] 2020-08-18 15:47
Function works as intended.  Moving to UAT.

**Comment by blaughman** [comment] 2020-08-24 15:56
Date filter works  in both Chrome and Edge in Staging.

**Comment by blaughman** [comment] 2020-08-26 03:36
Deployed to Production on 8/25/20

**Closed by blaughman** 2020-08-26 03:36 UTC
Labels: Must, Release 8-25-20
