### ISSUE TITLE
Assign newly submitted record to CRM

### ISSUE THREAD

**Issue by UchMok** [18F/crt-portal#77] opened 2019-07-23 14:08 UTC
## Narrative
As a DOJ CRT user, I want criminal offense related complaints to route to CRM so that I can readily access and address the complaint

## Background
Hate crimes and human trafficking are very serious offenses and can present imminent physical danger to the victim(s).  The Criminal Section is responsible for enforcing the statutes protecting these victims.   

## Assumptions
- Assuming that 'Bias based violence and human trafficking' question is optional. 

## Out of Scope
- Changing sections

## Acceptance criteria

1) Given a complainant is on the primary issue page
When they select either option for the 'Hate crimes and human trafficking' question
Then in the view all table, I see that the record is marked with *CRM* in the 'Routed' column

2) If the primary complaint is `police` and it is `outside` a correctional facility and it id not in the `disability` protected class, it will be *CRM*

3) given that I'm using a screen reader, when I get to a cell in this column it should announce "C-R-M, Routed" ([cell content, column name]).

I expect this to work as intended already based on the other tables. Preference for keeping it consistent with what sighted people would see vs having it read the section name

## Mockups / Wireframes
 (no mockup needed. text changes from ADM > CRM)

**Comment by Jacklynn** [comment] 2019-12-05 00:57
@lalitha-jonnalagadda Doesn't the text just change from ADM to CRM? Does there need to be something else in the mock up?

**Comment by Jacklynn** [comment] 2019-12-10 17:13
I updated the table logic to reflect the difference between hate crimes and human trafficking

**Comment by dwechsle** [comment] 2020-01-08 16:14
if both hate crimes and trafficking options are selected, where should it be routed?

**Comment by blaughman** [comment] 2020-01-08 16:17
Selecting either of these options, or both options - should route the complaint to the Criminal Section.

**Comment by blaughman** [comment] 2020-01-08 19:49
In testing, the complaint had the first option checked, but it routed the complaint to ADM.

**Comment by ilodidoj** [comment] 2020-01-09 13:42
@blaughman if I read the logic for EOS, HCE and VOT section logic at the top, complaint record will be routed to those section when EOS, HCE and VOT logic is met and even if Hate Crime first option is selected.  If user select one item from primary reason and select both options from the Hate Crime and Trafficking or ONLY the  "Coerced or forced to do work or perform a commercial sex act" from Hate Crime and Trafficking option then only be routed to CRM section. In a nutshell  "Coerced or forced to do work or perform a commercial sex act" is the determining factor for CRM routing. Is this correct assumption?

**Comment by lalitha-jonnalagadda** [comment] 2020-01-10 15:18
Per @blaughman 's conversation with CRM, we will be routing a complaint to CRM when either the hate crime or human trafficking is selected by the user. This is a deviation from the previous logic we had for this card. I made adjustments to the AC's to reflect the change

Noting the previous logic here (in case we need to refer back to it for any reason) 

|When I select| AND When conditional logic question is|Then Routed column is marked|
|------------|:------------|:--------------|
|Any option for 'Hate crimes| School| EOS|
|Any option for 'Hate crimes| Commercial Location| HCE|
|Any option for 'Hate crimes|Home|HCE|
|Any option for 'Hate crimes|Voting| VOT|
|Any option for human trafficking|Any| CRM|

**Comment by LindsayYoung** [comment] 2020-01-10 16:32
I will make the changes now

**Comment by blaughman** [comment] 2020-01-13 16:49
Function works as intended.  Moving to UAT.

**Comment by LindsayYoung** [comment] 2020-01-30 18:23
Updated this card, based on the exception: https://app.zenhub.com/workspaces/doj-crt-intake-scrum-board-5d03bf56c1c8a35d482eca0f/issues/18f/crt-portal/92

**Comment by lalitha-jonnalagadda** [comment] 2020-02-10 16:15
Showcased during deep-dive on 2/6.

**Closed by lalitha-jonnalagadda** 2020-02-10 16:15 UTC
Labels: Story
