### ISSUE TITLE
Confirm that my complaint has been received by DOJ CRT

### ISSUE THREAD

**Issue by UchMok** [18F/crt-portal#79] opened 2019-07-23 14:19 UTC
## Narrative
As a public user, I want to see a confirmation that my complaint was submitted so that I can finish the submission process and retain the information for my records

## Out of scope
 - Print report
 - Email notifications to recipients
## Acceptance criteria

1. Given that I'm on the 'review complaint' page
When I click the submit complaint button
Then I see a  'Thank you for your submitting a report to the civil rights division ' confirmation page

2. Given that I'm on the confirmation page
When I scroll through the page
Then I see the following sections:
 - Confirmation that report was successfully submitted
 - Record number
 - What to expect
 - What you can do next
 - My full complaint/submission

3. Given that I am on the confirmation page
Then I no longer see the 'back' button or the 'navigation' bar 

4.  [a11y] Right now this is just text so the only special consideration I might have is using semantic headings only for page title (h1 Thank you...), h2s for (what to expect, what you can do next, and your submission). I don't think the others could be visual heading styles

## Mockups / Wireframes
https://app.zenhub.com/workspaces/doj-crt-form-design-flows-5d7a67fa86a8cd0001581ea0/issues/18f/crt-django/75

![Confirmation Copy.jpg](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/2f58b635-2ef6-4f0e-9ad0-914f22797753)

(submitted report design the same as Review page but without "edit" buttons)

## Technical Notes
We should be able to use the work from the review and submit page to fill out the information.

**Comment by Jacklynn** [comment] 2020-01-08 02:48
@lalitha-jonnalagadda @AvivaOskow @blaughman 

I had started playing around with some designs (which is mostly content) over the break and just finished them up more.

Happy, well informed user with a complete summary:
![All Path - Details Copy 3.jpg](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/c71f282c-8f76-48f6-a2e3-e516f5e443d8)

Very simple:
![All Path - Details Copy 2.jpg](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/e2afb6d0-ba9c-4b8d-9945-7075c4535b05)

**Comment by Jacklynn** [comment] 2020-01-13 19:52
Removing my assignee since I took a first pass at this. @AvivaOskow

**Comment by Jkrzy** [comment] 2020-03-04 16:08
Hi @Jacklynn, @lalitha-jonnalagadda -- is there a source I can access for the content/text in the mock-ups here?

**Comment by lalitha-jonnalagadda** [comment] 2020-03-04 16:12
@Jkrzy 

Here's the content source of truth for the confirmation page: https://docs.google.com/document/d/176VJ5xO17WeZhlrhtXUNuICAtKaW_yxofOh-qrk_jEY/edit

Master content source of truth: https://docs.google.com/document/d/1-HLdb21JA6_EuMHZTOi7KXFWWV4mT2Af54Tzzijl2E8/edit

**Comment by blaughman** [comment] 2020-03-12 12:40
Function works as intended.  Moving to UAT.

**Comment by lalitha-jonnalagadda** [comment] 2020-03-20 14:11
Showcased at deep dive on 3/19.

**Closed by lalitha-jonnalagadda** 2020-03-20 14:11 UTC
Labels: Story
