### ISSUE TITLE
Assign newly submitted record to EOS

### ISSUE THREAD

**Issue by UchMok** [18F/crt-portal#75] opened 2019-07-23 14:07 UTC
## Narrative
As a DOJ CRT user, I want housing-related complaints to route to EOS so that they can readily address and assess the violation.

## Background
The Educational Opportunities Section works to ensure that officials in elementary and secondary schools and institutions of higher education do not discriminate against students on the basis of sex, national origin, language barrier, religion, or disability.

## Out of scope 
- Redirecting to external agencies

## Acceptance criteria
- Given a complainant is submitting a complaint

|WHEN Primary Issue is|(AND)WHEN Conditional logic selection is|(AND) WHEN Protected Class is|THEN 'Routed column' in the View all table as|
|---------------|:-----------------|:-----------------|:-----------------|
|Discrimination at school, educational program or related to receiving education | Public|Any|EOS|
|Discrimination at school, educational program or related to receiving education | Private|Any other than Disability|EOS|

## Exceptions

|WHEN Primary Issue is|(AND)WHEN Conditional logic selection is|(AND) WHEN Protected Class is|THEN 'Routed column' in the View all table as|
|---------------|:-----------------|:-----------------|:-----------------|
|Discrimination at school, educational program or related to receiving education | Private|Disability|DRS|
|Discrimination at school, educational program or related to receiving education | Hate Crime and/or Human Trafficking checked||CRM|

## Sign Off
Story Sign off
- [x] PO
- [ ] EOS
UAT Sign off
- [ ] PO

**Comment by LindsayYoung** [comment] 2020-01-28 20:11
Added to the section assignment spreadsheet as 12/28/20 tab https://docs.google.com/spreadsheets/d/1Ba0617v1wqwf89vYkCQmpNGmi3yI-bfPgXSF8JPqkeQ/edit#gid=80818894

**Comment by blaughman** [comment] 2020-01-29 14:33
Function works as intended.  Moving to UAT.

**Comment by lalitha-jonnalagadda** [comment] 2020-02-10 16:16
Showcased during deep-dive on 2/6.

**Closed by lalitha-jonnalagadda** 2020-02-10 16:16 UTC
Labels: Story
