### ISSUE TITLE
Making other language pathways available before full translation

### ISSUE THREAD

**Issue by Jacklynn** [18F/crt-portal#546] opened 2020-05-26 19:30 UTC
## Background: 
Want to make other language access links available on from the new portal since those links are on the HTFC page today and one be there when the page is released. Only Spanish translation will be available at the time of full launch and other language translations are being handled separately. 

**Current:** 
![Screen Shot 2020-05-27 at 10.17.26 AM.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/d0de3138-1c6b-47a9-b095-69adf552e98b)

### Short term

![Screen Shot 2020-05-27 at 10.25.13 AM.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/ed77e932-7ab0-43ed-a19b-92878fc50bb5)

Proposing adding a link. I think Dan's suggestion of having the drop downs go to PDFs would be unexpected and might lead someone to believe that all of them do that, not knowing that Spanish is working (not that it's super likely that you'd just click through).

Note: PDFs are also not as accessible as in HTML webpage and should be avoided when possible. 

- [ ] Add link to the `Availability of Language Assistance Services` page: https://www.justice.gov/crt/availability-language-assistance-services
- [ ] Help icon svg (white): ![ic_help-circle.svg](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/d8ca89de-4425-4d50-930c-9ab599ea0960)
- This text is already translated to Spanish because it's another one of the options `Disponibilidad de servicios de asistencia lingüística` (Not that this is a great link title. I might have it say "Language services"  but that wouldn't be translated

### Medium term
Re-use privacy policy template to present the different options.
![Screen Shot 2020-06-10 at 4.59.51 PM.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/93162c77-927c-4795-9b8d-954a01e8e6a9)
Maybe move the language picker to the header

### Long term
Language drop down has all the languages and they're translated (in the header)
![Screen Shot 2020-05-27 at 10.47.24 AM.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/cc461921-6a4f-4651-a679-fb7e17380781)

**Comment by danielhyi** [comment] 2020-05-27 18:16
Thumbs up from me!

**Comment by Jacklynn** [comment] 2020-05-27 19:11
Also suggestion to have the link be something like "More Language services" and it be english only for the short term.

**Comment by Jacklynn** [comment] 2020-05-28 15:54
@lalitha-jonnalagadda @blaughman friendly bump on this card

**Comment by Jacklynn** [comment] 2020-05-28 16:16
NVM, Dan clarified that next sprint is ok.

**Comment by cantsin** [comment] 2020-06-01 21:16
To be clear, we only want to do the "short term" section here?

**Comment by lalitha-jonnalagadda** [comment] 2020-06-01 21:19
@cantsin - That is correct. For now, we just need the short term plan.

**Comment by Jkrzy** [comment] 2020-06-17 13:15
@Jacklynn, Do we have a source for the icon question-circle icon there?

**Comment by Jacklynn** [comment] 2020-06-17 17:58
![ic_help-circle.svg](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/edc6f0bf-6333-4f38-9e64-10a27ddb6c74)

^Attached! I _think_ it might have gotten uploaded already because I saw James use it on accident too (we expected another icon that we didn't actually send)

**Comment by Jacklynn** [comment] 2020-06-17 17:59
lol, the icon is white so it's just a clickable space...I'll slack you.

**Comment by blaughman** [comment] 2020-06-18 13:19
Function looks and works as intended.  Moving to UAT.

**Comment by lalitha-jonnalagadda** [comment] 2020-07-01 21:12
Deployed on 6/30.

**Closed by lalitha-jonnalagadda** 2020-07-01 21:12 UTC
Labels: Must, Release 6-30-20
