### ISSUE TITLE
Add EEOC Referral Letter

### ISSUE THREAD

**Issue by danielhyi** [18F/crt-portal#667] opened 2020-08-11 21:17 UTC
This letter is ready to go. In the contact complainant menu, please label this as:
CRT - EEOC Referral Letter

 [https://app.zenhub.com/files/183258764/8f652876-253a-4d2c-b1fd-9589f9fdc335/download](https://app.zenhub.com/files/183258764/8f652876-253a-4d2c-b1fd-9589f9fdc335/download)

Spanish Translation
Please label this as:
CRT - EEOC Referral Letter (Spanish)
[https://app.zenhub.com/files/183258764/b83e809c-51b1-4a58-ae9c-fbb761e1c5da/download](https://app.zenhub.com/files/183258764/b83e809c-51b1-4a58-ae9c-fbb761e1c5da/download)

**Comment by cantsin** [comment] 2020-12-28 21:32
Going to grab this one while waiting for SES access. Please let me know if anything else is higher priority.

**Comment by blaughman** [comment] 2020-12-29 18:50
Function works as intended in Chrome and Edge.  Moving to UAT.

**Closed** 2021-01-13 01:57 UTC
