### ISSUE TITLE
send a complaint to another section

### ISSUE THREAD

**Issue by alexsoble** [18F/crt-portal#30] opened 2019-07-10 16:26 UTC
send a complaint to another sectionThe section that has jurisdiction to take action on a complaint has ownershipUser can only route from single complaint detail page
Any user can do perform this action

**Comment by lalitha-jonnalagadda** [comment] 2019-12-04 20:11
Out of scope: 
 - no multi section assignment

**Comment by blaughman** [comment] 2020-02-10 15:22
Function works as intended.  Moving to UAT.

**Comment by lalitha-jonnalagadda** [comment] 2020-02-10 16:14
Showcased during deep-dive on 2/6.

**Closed by lalitha-jonnalagadda** 2020-02-10 16:14 UTC
Labels: Story
