### ISSUE TITLE
As a CRT user, I expect the mailing address 1&2 of the incident location to appear in the Single record view

### ISSUE THREAD

**Issue by Jacklynn** [18F/crt-portal#620] opened 2020-07-06 16:15 UTC
## Issue:
If a user enters an incident location address (via Public form or Pro form) I expect it to appear on the single record details page, similar to the Contact address. CRT staff might not be aware it was provided.

## Expected:
![Screen Shot 2020-07-06 at 9.14.38 AM.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/cb189f6b-c8c9-48fc-88e4-2a5a56bdc8c8)

![Screen Shot 2020-07-06 at 9.14.47 AM.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/61f5a843-9a07-49ea-8425-1c4ddee07e12)

**Comment by Jkrzy** [comment] 2020-08-07 18:52
We're not capturing location`zipcode` for reports but the rest is no problem!

**Comment by blaughman** [comment] 2020-08-10 16:14
Function works as intended in Chrome and Edge.  Moving to UAT.

**Comment by blaughman** [comment] 2020-08-24 18:26
Function works as intended in Staging.

**Comment by blaughman** [comment] 2020-08-26 03:37
Deployed to Production on 8/25/20

**Closed by blaughman** 2020-08-26 03:37 UTC
Labels: Release 8-25-20
