### ISSUE TITLE
Move Voting module under 'mistreated by police, correctional staff, or inmates' on Primary concern page

### ISSUE THREAD

**Issue by randyabramson** [18F/crt-portal#880] opened 2021-02-15 19:17 UTC

**Comment by blaughman** [comment] 2021-03-10 12:56
Function appears as requested on both the public side and the proform.  Moving to UAT.

**Comment by blaughman** [comment] 2021-03-15 15:09
@timoballard @ilodidoj @Jkrzy @randyabramson  Still showing errors on proform - errors to follow

**Comment by blaughman** [comment] 2021-03-15 15:09
These branching questions should be associated with the Employment selection
![image.png](https://images.zenhubusercontent.com/5d2390b2c408a2441fc2874d/1f637d83-756a-4ae2-8e45-3388297b2747)

**Comment by blaughman** [comment] 2021-03-15 15:10
This question should be associated with the Education selection

![image.png](https://images.zenhubusercontent.com/5d2390b2c408a2441fc2874d/2754f020-398e-49c6-91c6-82890ffd959a)

**Comment by blaughman** [comment] 2021-03-15 15:11
These branching questions should be associated with the Mistreated by Police... selection

![image.png](https://images.zenhubusercontent.com/5d2390b2c408a2441fc2874d/72933176-f9ad-4f43-bca8-c73b21d02354)

**Comment by timoballard** [comment] 2021-03-15 15:23
Thanks @blaughman - looking into this

**Comment by timoballard** [comment] 2021-03-16 18:26
Added [908](https://app.zenhub.com/workspaces/doj-crt-intake-scrum-board-5d03bf56c1c8a35d482eca0f/issues/18f/crt-portal/908) as a followup technical task based on our work here

**Comment by blaughman** [comment] 2021-03-16 20:04
Proform is good to go.  Moving to UAT.

**Comment by randyabramson** [comment] 2021-03-17 21:57
Working as expected on Staging. @blaughman would love your second set of eyes here.

**Comment by blaughman** [comment] 2021-03-18 15:57
Function works as intended in staging.

**Closed** 2021-03-24 01:26 UTC
