### ISSUE TITLE
View & get to where I can submit a general complaint (landing page)

### ISSUE THREAD

**Issue by alexsoble** [18F/crt-portal#32] opened 2019-07-10 16:26 UTC
## Narrative

As a public user, when I land on civilrights.justice.gov, I want to learn about DOJ CRT and my rights around filing a report so that I have the prerequisite information at hand to determine if CRT is the right place to file my report. 

## Background

DOJ CRT currently gets quite a few complaints that are unactionable. The root cause for this is majorly driven by the fact that the complainant doesn't have the prerequisite background information that helps them determine if CRT is the right place to address their needs or if they need to contact another agency with their concern. 

## Assumptions:

Path to the landing could be one of the following:
- When a complainant gets directly to - www.civilrights.justice.gov
- By clicking the 'How to Submit a report' button on the CRT page

## Acceptance Criteria

1. Given that I'm on the CRT website
When I click on the 'How to submit a report' link on the left nav bar
Then I'm taken to a new CRT landing page (as shown in the mock)

2. Given that I go to www.civilrights.justice.gov
When I scroll through the page, when I click the button to Submit a report
Then I'm taken to the form to create my report

#### [Content Source of Truth](https://docs.google.com/document/d/1f-H29XSuIVthe0fhA0meT8qoFXfRKWABJ5xr8SEgdgE/edit) 

![CRT Landing_EOD 5.12 Copy.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/e952ae0e-d88f-4262-be85-78481aeff528)

**Comment by cantsin** [comment] 2020-05-18 20:01
@AvivaOskow may I please have the assets (images) for the above? also any links and copy (text) if there's any. thanks!

I'm also thinking we'll want to split this issue up in smaller pieces. CC @LindsayYoung

**Comment by cantsin** [comment] 2020-05-19 15:58
@AvivaOskow where do these links go?

- about the division (menu item)
- your rights (menu item)
- report a violation (menu item)
- contact (menu item)
- FBI tip line (phone)
- call to submit a complaint (phone)
- or reach us by mail (email)

**Comment by Jacklynn** [comment] 2020-05-22 23:22
@cantsin 
The menu items are anchorlinks to the other sections of the page
about the division (menu item) --> We uphold
your rights (menu item) -->  Understanding your rights
report a violation (menu item) --> How to report

@AvivaOskow do we need the contact? i think was a future page? Unless you wanted it to go to https://www.justice.gov/contact-us which might be...surprising. 

I can confirm the others with Dan

**Comment by Jacklynn** [comment] 2020-05-22 23:33
For the external links to the legal aid organizations, can we add the "external link" icon? ![ic_external-link.svg](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/26f2ac9d-0e41-4a1d-a7bb-53dc51bb5d0f) It's the same from the new hate crimes page that Lindsay was working on

**Comment by Jacklynn** [comment] 2020-05-23 00:20
@lalitha-jonnalagadda I talked to Dan about this and there's a v5 content source of truth :|. Is this what was sent to Marta? https://docs.google.com/document/d/1f-H29XSuIVthe0fhA0meT8qoFXfRKWABJ5xr8SEgdgE/edit

It also has the the links specified.

**Comment by cantsin** [comment] 2020-05-26 17:54
@Jacklynn thank you for the V5 document! Question: should I adjust the landing wording to match this document instead of the mockups?

**Comment by Jacklynn** [comment] 2020-05-26 23:58
@cantsin yes let's go with V5 content

And I'm saying that with confidence only because I confirmed with @lalitha-jonnalagadda first that that's the version she sent for spanish translation

**Comment by AvivaOskow** [comment] 2020-05-28 01:19
# Hero images are [here](https://drive.google.com/drive/folders/136UVdUDA1W7avDA-iwBIVS9b9XiOdb6O)

**Comment by Jkrzy** [comment] 2020-05-28 19:59
I think we can call this first iteration complete since it's moved onto dev/staging and we're into revisions. Moving to dev-done

**Closed** 2020-06-03 14:01 UTC
Labels: Must, Story, release 6-2-20
