### ISSUE TITLE
Sort information when viewing all complaints

### ISSUE THREAD

**Issue by alexsoble** [18F/crt-portal#36] opened 2019-07-10 16:26 UTC
## Narrative

As a DOJ CRT user, I want to sort data when viewing all complaints so that I can view information in a way I prefer in order to make decisions and/or take action on complaint(s)

## Out of scope
- Filtering data 
- Search functionality
- Conditional/custom sorting - (Ex: sort ascending on column A AND THEN descending on column B)

## Assumption
- Default view - Sorted by Submitted column -  Date and Time

## Acceptance Criteria

1) Given that I'm on the view all table
When I click on the column header
Then I see data is sorted ascending/descending 

|Column|Sort order| 
|:-----------|:-----------|
|status|alphabetical|
|routed|alphabetical|
|submitted|date|
|contact name|sort by last name then first name|

## Mocks (draft)
![[LATEST] CRT view all - routed.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/8f3869de-11ec-4eed-8264-5d0f063905a0)

## SVGs
![sort-down.svg](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/70a41c44-900a-41b5-9066-265aa42933d5)![sort-up.svg](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/b64ca1fd-dc87-4a84-9410-c25cde16064d)

## Questions
- Will we preserve sort criteria from previous session? @LindsayYoung 
  - When the user uses a previous link with a sorted view all page, they will see the previously sorted page. If not, they will see the list sorted by submitted date 

## Technical note
We would want to do this by passing an arg to the IndexView

**Comment by LindsayYoung** [comment] 2019-11-18 19:01
Sorting 

row | notes
--|--
status | alphabetical
routed | alphabetical
submitted | date
contact name | sort by last name then first name
contact details |  This is several questions - sort by email to start?
summary | alphabetical
class |   alphabetical? (But this is a many to many field so I am not sure how straight forward this is) I don't see an arrow for this in the mocs, so maybe we aren't .

I would suggest always putting null results last. I can explain more if you want.

**Comment by LindsayYoung** [comment] 2019-11-18 22:48
Default sort is by the receipt date and time- represented by 'submitted'

**Comment by Jacklynn** [comment] 2019-11-19 18:04
Updated the mock and added the arrow SVG

**Comment by Jacklynn** [comment] 2019-12-03 22:01
I found this documentation on accessibility for sorting tables https://dequeuniversity.com/library/aria/tables/sf-table-sortable

**Comment by el-mapache** [comment] 2019-12-04 14:32
@Jacklynn I'm working on this currently! I took a look at the link you sent, and the table in their example is using JavaScript to sort. We are going to be sorting via an anchor tag and query parameters; can I assume that we only need to add a `title` attribute with a description of the sort to ensure accessibility?

**Comment by Jacklynn** [comment] 2019-12-05 05:56
@el-mapache I think you asked about this during the guild, and another option sounded like using an alt/aria label for the symbol or making the whole thing a button. 
Things to indicate...
- I'm in a sortable table 
- If I'm in a heading item, if it's in "ascending" or "descending" order.

**Comment by blaughman** [comment] 2019-12-09 14:01
The sorting worked as intended in IE 11.  Moving to UAT.

**Comment by lalitha-jonnalagadda** [comment] 2019-12-13 14:38
Reviewed with the deep dive group on 12/12 and this card can now be closed.

**Closed by lalitha-jonnalagadda** 2019-12-13 14:38 UTC
Labels: Story
