### ISSUE TITLE
Assign newly submitted record to DRS

### ISSUE THREAD

**Issue by UchMok** [18F/crt-portal#72] opened 2019-07-23 14:05 UTC
## Narrative
As a DOJ CRT user, I want disability-related complaints to route to DRS section so they can readily address and assess the violation. 

## Background
:add business context to help us better understand the story:

## Acceptance criteria

Given a complainant is submitting a complaint

|WHEN Primary Issue is|(AND)WHEN Conditional logic selection is|(AND) WHEN Protected Class is|THEN 'Routed column' in the View all table as|
|---------------|:-----------------|:--------------------|:-----------------|
|Discrimination at a school..|Private|Disability|DRS|
|Ability to vote was impacted|Any|Disability|DRS|
|Mistreated by police ..|Any| Disability| DRS|
|Public or Commercial| | Disability| DRS|
|Discriminated ..commercial location or public place| Healthcare facility | Disability| DRS|
|Something else| | Disability| DRS| 

## Exceptions
|WHEN Primary Issue is|(AND)WHEN Conditional logic selection is|(AND) WHEN Protected Class is|THEN 'Routed column' in the View all table as|
|---------------|:-----------------|:--------------------|:-----------------|
|Any|Hate Crime questions|Any|CRM|
|Discriminated ..commercial location or public place| Anything other than Healthcare facility | Disability| HCE|
|Workplace discrimination|Any|Disability|DRS|
|Housing Discrimination..|Any|Disability|HCE|
|Discriminated ..commercial location or public place| Healthcare facility | Anything other than Disability| SPL|

## Mockups / Wireframes
![image]()

## Technical Notes
- [ ]
- [ ]
- [ ]

**Comment by LindsayYoung** [comment] 2020-01-07 23:08
Noting that workplace + disability should also be DRS according to: https://app.zenhub.com/workspaces/doj-crt-intake-scrum-board-5d03bf56c1c8a35d482eca0f/issues/18f/crt-portal/74

**Comment by LindsayYoung** [comment] 2020-01-31 21:42
## Clarification 

I think the following line should be removed. It seems like it is contradicted by the next line. I just want to confirm- for Public or Commercial only 
healthcare complaints should go to DRS.

Public or Commercial |   | Disability | DRS
-- | -- | -- | --

## Noting changes to other section routing

Making the change to [workplace ELS routing](https://app.zenhub.com/workspaces/doj-crt-intake-scrum-board-5d03bf56c1c8a35d482eca0f/issues/18f/crt-portal/74) workplace discrimination will now go to ELS.

**Comment by LindsayYoung** [comment] 2020-02-03 22:38
Added blocked while we wait for clatificaion

**Comment by lalitha-jonnalagadda** [comment] 2020-02-04 16:28
I checked with @blaughman on the routing for 'Public and commercial' and we might need to change one scenario:

When primary issue is: Public/commercial
AND conditional logic is: Anything other than Healthcare facility
AND protected class is: Disability
THEN send to DRS
(we are now routing to HCE)

**Comment by blaughman** [comment] 2020-02-11 20:04
Function works as intended in IE11 and Chrome.  Moving to UAT.

**Comment by lalitha-jonnalagadda** [comment] 2020-03-09 15:33
Closing this card following our deep dive session on 3/5

**Closed by lalitha-jonnalagadda** 2020-03-09 15:33 UTC
Labels: Story
