### ISSUE TITLE
Adding a 'Send' link on the 'Contact Complainant' pop out screen

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#476] opened 2020-05-06 23:33 UTC
## Narrative
As a CRT user, I want a send button on the contact complainant modal so that I can email the complainant a form letter response.

## Acceptance Criteria
1) Given I am on the 'Contact Complainant' modal
when 'no template chosen' is the value in the drop down menu
then I see three greyed out, non-selectable boxes ('Copy' 'Print' and 'Send') and the 'Cancel' option at the bottom

2) Given I am on the 'Contact complainant' modal
when I select a form letter from the drop down menu
then the greyed out 'Copy' and 'Print' boxes become blue and can be selected
AND
the 'Send' button remains grey and unable to be selected until email has been integrated.

**Comment by blaughman** [comment] 2020-11-19 20:11
Function is as intended.  Moving to UAT.

**Comment by randyabramson** [comment] 2020-12-08 21:41
Verified on staging

**Comment by randyabramson** [comment] 2020-12-15 22:35
Verified in PROD - closing this out. Nice work, everyone!

**Closed** 2020-12-15 22:36 UTC
