### ISSUE TITLE
Leave a comment on a complaint

### ISSUE THREAD

**Issue by UchMok** [18F/crt-portal#6] opened 2019-06-25 18:20 UTC
## Narrative
As an **Intake specialist**	
I want to **leave a comment on a complaint**	
So that **I can explain why a complaint is in a certain status; leave investigation notes on a complaint; explain why I've routed that complaint to another section**

## Background
CRT intake specialists add notes to cases or concerns to aid in decision making and information sharing.  Appending comments directly to a record ensures all relevant information is in one place and should expedite the response time.

## Assumptions
- No character limit on comments section

## Out of Scope

- 'Edit comment' is out of scope
- Delete comment is out of scope" 

## Acceptance criteria 

1) Given that I am a CRT user and I am reviewing a public user submission assigned to my section
  When I select an individual record and arrive on the complaint details page
  Then I see  
- an area to create a comment 
- That I can comment on a single complaint
- upon submitting the comment, user should be able to view comment on single complaint detail page with the following metadata:
-- submitter name
-- date/time of submission

2) a11y requirements
- [ ] a user should be able to tab to the text box and "send" button
- [ ] visual focus should show around the text area and button
- [ ] Expect "new comment" label to be associated with the text box
- [ ] Button labeled "Send"
- [ ] users should have a confirmation that it worked. 

## Mockups / Wireframes

![Complaint details Copy.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/89f9d259-aedc-421b-9a6f-9fada9bc4f3c)

## Technical Notes
- [ ]
- [ ]
- [ ]

**Comment by Jacklynn** [comment] 2020-02-20 02:49
I didn't get feedback from Aviva before she left, but this looked good to Lalitha! https://docs.google.com/presentation/d/1FuuSg0bb9DDQx_EjRK-T_YZQ0gpcVgIz8-M6BQE-u4g/edit?ts=5e4d6788#slide=id.g7e678ba479_0_20

**Comment by blaughman** [comment] 2020-03-19 17:51
Function works as intended.  Moving to UAT.

**Comment by lalitha-jonnalagadda** [comment] 2020-03-20 14:10
Showcased at deep dive on 3/19.

**Closed by lalitha-jonnalagadda** 2020-03-20 14:10 UTC
Labels: Story
