### ISSUE TITLE
Rerouting Guide 

### ISSUE THREAD

**Issue by danielhyi** [18F/crt-portal#657] opened 2020-07-27 22:39 UTC
## Narrative
As a CRT intake specialist analyzing a complaint, I need a routing guide so that I know where to accurately reroute a complaint no matter the issue.

## Solution
A link to a rerouting guide on the complaint details page will aid intake specialists 

## Acceptance Criteria

1) Given I am on a complaint detail page
when I see the 'Actions' area
then I see an icon and the text 'Routing Guide' to the right of 'Section'

2) Given I am hovering over the icon or 'Routing Guide' text
when I click to select either the icon or 'Routing Guide' text
then I see a modal open with the routing guide chart.

3) Given I am viewing the routing guide chart
when I determine where I am going to route the complaint
then I close the routing guide by clicking the 'x' in the upper righthand corner of the modal
AND
I now see the complaint detail page I was working on.

Rerouting guide [here](https://docs.google.com/document/d/1ucxO2zw7E2megnBsDH92QrR8FtMWqmlb/edit). We sent it out to sections, but we want to find some way to make the info in the box readily available (or some other way to help intake  specialists know where to reroute) as they analyze reports in the system.

**Comment by blaughman** [comment] 2020-08-17 15:37
![image.png](https://images.zenhubusercontent.com/5d2390b2c408a2441fc2874d/3276e3bd-611f-4547-8eb1-cf429ccc9d4a)

**Comment by blaughman** [comment] 2020-08-18 15:36
![image.png](https://images.zenhubusercontent.com/5d2390b2c408a2441fc2874d/7262815e-dacf-46f5-a392-b03b515ce441)

This chart is what should be visible when you select either the icon or 'Routing Guide' text.

**Comment by Jkrzy** [comment] 2020-08-27 13:25
@blaughman, it looks like the last row of that chart might have gotten cut off in the screen shot.

Is there content after `Land Use/Zoning` ??

**Comment by blaughman** [comment] 2020-08-27 13:51
@Jkrzy There is a link for the document just below the 3rd AC.  Sorry, if it's a little incognito.

**Comment by Jkrzy** [comment] 2020-08-27 14:21
Ahh thanks @blaughman !!

This is much bigger than I thought from just looking at the screenshot :smile:

Is the intention for that _entire_ document to be replicated in a modal or just the first table with steps 1-3?

Given the length, folks will need to scroll to view all the content.

The final section `Questions` POC names are OK to include in github?

**Comment by blaughman** [comment] 2020-08-27 14:38
@Jkrzy I edited the document to remove some of the empty space.  That should bring it down to two pages, but it appears a scroll bar is needed.  Would it be possible to incorporate the full document but keep the POC names off of gitbhub?

**Comment by randyabramson** [comment] 2020-09-01 00:45
![close-button.png](https://images.zenhubusercontent.com/5ef156d51dd4f26e61414bbf/0ca19f7c-f95b-4fe3-a9fe-4587a485ff98)

@Jkrzy Any way to get a little more space between the bottom of the guide and the close button? See attached.

Also, if there was consensus around the text 'how to I reroute,' then let's leave it. If that is just placeholder copy, maybe 'rerouting guide' is a bit more direct.

**Comment by Jkrzy** [comment] 2020-09-01 15:25
For sure! I'll tweak the spacing now.

On the language, I don't believe there is consensus on any specific wording. But here's what they all look like...

I'll defer to you and @blaughman for a final decision.

* Bill had `Reassignment Help` in the original mock-up.
![Screen Shot 2020-09-01 at 11.23.44 AM.png](https://images.zenhubusercontent.com/5e55861e4853ae9aab609188/21f59db5-5cc0-40f1-b079-f15573014482)

* I proposed `How do I reroute?`
![Screen Shot 2020-09-01 at 11.23.28 AM.png](https://images.zenhubusercontent.com/5e55861e4853ae9aab609188/555a5d15-1c7c-426b-9951-92117220d597)

* You suggested: `rerouting guide`![Screen Shot 2020-09-01 at 11.23.57 AM.png](https://images.zenhubusercontent.com/5e55861e4853ae9aab609188/bfeb2886-37e1-436e-83e9-924b65334348)

**Comment by randyabramson** [comment] 2020-09-01 15:33
@Jkrzy --- @blaughman  and I spoke this morning..."rerouting guide" is the preferred language. Thanks so much for subbing that in!

**Comment by Jkrzy** [comment] 2020-09-01 15:41
Changes submitted! https://github.com/usdoj-crt/crt-portal/pull/656

**Comment by blaughman** [comment] 2020-09-04 15:40
Function works as intended on Chrome and Edge in Staging.

**Comment by blaughman** [comment] 2020-09-09 16:39
Released to Production on 9/8/20.

**Closed by blaughman** 2020-09-09 16:39 UTC
Labels: Release 9-8-20, Small
