### ISSUE TITLE
Change title of 'submission' page on form

### ISSUE THREAD

**Issue by randyabramson** [18F/crt-portal#881] opened 2021-02-15 19:22 UTC
Change name of final page of the form (once complainant clicks 'submit report').

The page is currently named 'Contact the civil rights division'

Please change to 'Submission complete'

**Comment by ilodidoj** [comment] 2021-03-16 16:36
@randyabramson we will need Spanish translation for 'Submission complete'.

**Comment by ilodidoj** [comment] 2021-03-16 17:25
@randyabramson we will be showing previous original Spanish translation until we have the translation for the 'Submission complete'.  This will help to track language other than english in the interim.

**Comment by blaughman** [comment] 2021-03-17 18:15
@timoballard @randyabramson I submitted this translation request as well.

**Comment by blaughman** [comment] 2021-03-17 18:28
@timoballard @ilodidoj @randyabramson 

Per Marta:

Envío completo

**Comment by timoballard** [comment] 2021-03-17 20:19
Added [909](https://app.zenhub.com/workspaces/doj-crt-intake-scrum-board-5d03bf56c1c8a35d482eca0f/issues/18f/crt-portal/909) to capture the translation work.

**Comment by blaughman** [comment] 2021-03-22 13:38
Text appears as intended in Dev.  Moving to UAT.

**Comment by randyabramson** [comment] 2021-04-06 21:09
I don[t see any reports completed in Spanish yet to verify the name change live, but I will continue to monitor

**Closed** 2021-04-06 21:11 UTC
