### ISSUE TITLE
Assign newly submitted record to HCE

### ISSUE THREAD

**Issue by UchMok** [18F/crt-portal#76] opened 2019-07-23 14:08 UTC
## Narrative
As a DOJ CRT user, I want housing-related complaints to route to HCE so that they can readily address and assess the violation.

## Background
The Housing and Civil Enforcement Section works to protect some of the most fundamental rights of individuals, including the right to access housing free from discrimination, the right to access credit on an equal basis, the right to patronize places of business that provide public accommodations and the right to practice one’s faith free from discrimination.

## Out of scope 
- Redirecting to external agencies

## Acceptance criteria
- Given a complainant is submitting a complaint

|WHEN Primary Issue is|(AND)WHEN Conditional logic selection is|(AND) WHEN Protected Class is|THEN 'Routed column' in the View all table as|
|---------------|:-----------------|:-----------------|:-----------------|
|Housing Discrimination or harassment| |Any other than Disability|HCE|
|Discriminated against in any other commercial or public place| Anything other than healthcare facility|Any other than Disability| HCE|

## Exceptions

|WHEN Primary Issue is|(AND)WHEN Conditional logic selection is|(AND) WHEN Protected Class is|THEN 'Routed column' in the View all table as|
|---------------|:-----------------|:-----------------|:-----------------|
|Housing Discrimination or harassment| |Disability|DRS|
|Discriminated against in any other commercial or public place| Anything other than healthcare facility| Disability|DRS|

## Sign Off
Story Sign off
- [x] PO
- [x] HCE
UAT Sign off
- [ ] PO

**Comment by blaughman** [comment] 2020-01-24 15:30
Function works as intended.  Moving to UAT.

**Comment by lalitha-jonnalagadda** [comment] 2020-02-10 16:17
Showcased during deep-dive on 2/6.

**Closed by lalitha-jonnalagadda** 2020-02-10 16:17 UTC
Labels: Story
