### ISSUE TITLE
Tell DOJ CRT where the discrimination took place (incident location)

### ISSUE THREAD

**Issue by UchMok** [18F/crt-portal#67] opened 2019-07-23 13:52 UTC
## Narrative
As a public user, I want to tell DOJ CRT where a potential civil rights violation occurred so that DOJ CRT can investigate my complaint. 

## Background
The location where the discrimination took place is vital to DOJ CRT users, _however this information is sometimes missing from submitted complaints_. This question can help ensure that complainants submit important informations so that their complaint is reviewed and processed more efficiently. 

The value to internal sections is that...some sections have personnel assigned to specific districts.  Others will use the discrimination location to reach out to the local FBI office for assistance with an investigation.  It also assists with establishing a pattern or practice of civil rights violations in a defined geographical area.

## Out of scope
- Including the conditional logic questions from the Categories page. This story focuses on the geographic details only
- Auto fill/predictive location/zip code look up. 

## Assumptions
- city and state will be required fields. 
- There is a possibility the discrimination location will be online.
- We're only accepting incident locations in the US and US territories

## Acceptance criteria
1) Given that I am filing a complaint 
when I'm on the 'Location' page
then I see that
- [ ] previous page is 'Primary issue' and
- [ ] next page is 'protected classes'

2) Given that I am filing a complaint 
when I'm on the 'Location' page
then I see 
- [ ] header - 'Where did this happen'
- [ ] help text under ' Where did this happen' header: "Providing details on where this occurred helps us properly review your issue and get it to the right people within the Civil Rights Division."

3) Given I'm filling a complaint 
When I am on the _Locations page_ 
Then I see

|Field|Type|Optional/Required| Error Messages |
|------------|:-------------|:------------:|:-------------------:|
|Location name|Free Form|Required|Please enter the name of the location where this took place|
|Mailing Address 1|Free Form|Optional|
|Mailing Address 2|Free Form|Optional|
|City/Town|Free Form|Required|Please enter the city or town where this took place|
|State|Type ahead Drop Down|Required|Please enter the state where this took place|

- Follow default error handling methods to be followed

4) Given that I'm filing a complaint
When I'm on the location page and click next without inputing information for more than one required field
Then I get an error message 'Please enter the required information to proceed'
AND
I'm not allowed to go to the next page

## Questions
- Should location name be required? What if it happened in a park? - _Have help text with examples for users to understand the location information they need to input_
- Could we make the location name help text have conditional logic as well? Ex: if you picked school as the category, update label to "School name"
- How do we handle complaints that are from an online location - _ @lalitha-jonnalagadda @blaughman   Check with DRS_
- Will we allow for special characters in location name and city/town? Would that affect sorting at all?
## Mockups / Wireframes
https://app.zenhub.com/workspaces/doj-crt-form-design-flows-5d7a67fa86a8cd0001581ea0/issues/18f/crt-django/71

![Screen Shot 2019-11-21 at 1.30.52 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/4641983b-372f-4ad8-bec4-4c5d8d6a273d)

## Sign off:
Story sign off
- [x] PO 
- [x] DRS?
UAT Sign off
- [x] PO

## Technical Notes
- [ ]
- [ ]
- [ ]

**Comment by UchMok** [comment] 2019-10-28 19:20
Optional fields for this story:
Location/establishment name

Required fields for this story:
City or Town
State
*ensure complainant enters AT LEAST city and town. Can enter more at their discretion?

Assumptions:
US and US territories only (Eg puerto rico) w/in CRT jurisdiction

**Comment by Jacklynn** [comment] 2019-10-29 22:42
DRS and EOS said that making the name required was important for their sections. EX: EOS felt like they couldn't do anything without a school name.

**Comment by AvivaOskow** [comment] 2019-11-18 22:05
## Most recent design:

![Screen Shot 2019-11-18 at 5.01.51 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/af3df4ff-0dba-44e6-9cd3-c61787eace56)

**Comment by AvivaOskow** [comment] 2019-11-18 22:06
If we go with the route of everything going to SPL or CRM instead of routing out for the thin slice, users could just continue with the form without an alert. If we are referring out, depending on what they choose, they can get an info box with what we recommend they do next.

**Comment by lalitha-jonnalagadda** [comment] 2019-11-19 02:33
The mocks above seem to be for #130 @AvivaOskow .

**Comment by lalitha-jonnalagadda** [comment] 2019-11-20 21:14
@blaughman and I had a chance to speak with Carmen from DRS this morning and she was 👍🏼to proceed with the location design as highlighted in the mock up. For the future, she felt that having a check box for online occurrences would help with data analysis in case they want to look up the volume of complaints related to websites.

**Comment by AvivaOskow** [comment] 2019-11-21 18:32
@lalitha-jonnalagadda @Jacklynn For the alert text, I made a suggestion in the content source of truth and did this in my mockups, but we are saying, "Please XYZ..." for the other alerts I believe? So I added that to mine, if we want to edit this story to match.

**Comment by Jacklynn** [comment] 2019-11-21 19:15
Thank you!  "please" works for me. 

I typically keep error messages more curt, but I think this context warrants some softness. Thanks for your attention to detail <3

**Comment by lalitha-jonnalagadda** [comment] 2019-11-21 19:48
Adjusted the AC to match the right alert message. @AvivaOskow can you please add the 'required' flag to location name, city and state in the mock ups

**Comment by Jacklynn** [comment] 2019-11-21 21:34
@lalitha-jonnalagadda I was able to sync with Aviva last and we'd like to try only indicating "optional" fields so the mock should be ok as is. If this pattern doesn't end up working we can change. 

I updated task board #/366 to help document this as well! For what it's worth it's an accepted alternate pattern: https://uxdesign.cc/form-field-required-vs-optional-9b4d7cdbf400

**Comment by lalitha-jonnalagadda** [comment] 2019-11-21 21:45
Ah! I missed the optional on the mailing address fields. Its probably because the previous mocks had required flag. This works. Thanks for the clarification. Moving this card to 'Ready for dev'.

**Comment by el-mapache** [comment] 2019-11-22 20:41
@lalitha-jonnalagadda @blaughman I notice that the table in the ticket has an optional `Zip` field, but the design mock does not. Which should we go with?

**Comment by lalitha-jonnalagadda** [comment] 2019-11-22 21:24
@el-mapache We don't need a zip code on this screen. My apologies that I didn't adjust the table in the AC's. I edited the table now.

**Comment by lalitha-jonnalagadda** [comment] 2019-11-25 18:39
Notes from the planning meeting: @Jacklynn and @AvivaOskow - Mailing address doesn't seem to be the right representation as this is the incident location and doesn't require a mailing address.

**Comment by el-mapache** [comment] 2019-11-26 13:07
@AvivaOskow Following the guidance in the annotated designs produces the following in the header of the location page (and every other page that uses the same template):

<img width="533" alt="Screen Shot 2019-11-25 at 4 33 20 PM" src="https://user-images.githubusercontent.com/1421848/69635959-8df89600-1023-11ea-9a41-87e03168ad14.png">

These are the styles that USWDS adds automatically to `h` and `p` elements when they are children of the `usa-prose` class. I wanted to double check this since it represents a departure from the current styles, and the design mocks don't seem to show serif fonts.

Thanks!

**Comment by LindsayYoung** [comment] 2019-12-02 21:29
Did a quick desk check with Jacquline and there wasn't usability concern about having the location and mailing address having the standard field length. This page is probably going to change and we can circle back on making some fields extra long when we come back for polishing.

**Comment by blaughman** [comment] 2019-12-03 13:39
This page worked as intended in IE 11.  Moving to UAT.

**Comment by lalitha-jonnalagadda** [comment] 2019-12-13 14:38
Reviewed with the deep dive group on 12/12 and this card can now be closed.

**Closed by lalitha-jonnalagadda** 2019-12-13 14:38 UTC
Labels: Story
