### ISSUE TITLE
Typeahead for assignee -view all page

### ISSUE THREAD

**Issue by LindsayYoung** [18F/crt-portal#470] opened 2020-04-29 15:58 UTC
On the view all table we currently have a select element for assignee because we need additional css work to add the typeahead to that page.

![Screen Shot 2020-04-24 at 7 13 21 PM](https://user-images.githubusercontent.com/4406333/80268981-be8b3d00-8660-11ea-9d64-1aba2f3aa8fb.png)

**Comment by cantsin** [comment] 2020-05-06 19:45
@LindsayYoung I don't quite understand this issue, can you please give some more context? Do we want to change assignee to a text input? And use autocomplete? (Is this related to the complaint_view_filters and/or accessible-autocomplete javascript files?)

**Comment by LindsayYoung** [comment] 2020-05-06 20:10
Great question! We want to change the input on the forms/view to match the input we already have on forms/id-of-form. We will be able to add some javascript that identifies the ID of the element that we want to do the type to select. 

Here is the existing implementation
https://github.com/usdoj-crt/crt-portal/blob/develop/crt_portal/cts_forms/templates/forms/complaint_view/show/index.html#L93-#L97

The reason that isn't implemented is that the css doesn't work on that page looks bad- as you can see.

**Comment by blaughman** [comment] 2020-05-11 14:50
Function works as intended in Chrome, Edge and IE 11.  Moving to UAT.

**Closed** 2020-05-18 23:53 UTC
Labels: release 5-19-20
