### ISSUE TITLE
Remove word 'basis' at end of AA trending topic letter

### ISSUE THREAD

**Issue by randyabramson** [18F/crt-portal#682] opened 2020-08-26 16:53 UTC
Please remove the word 'basis' at the end of the AA trending topic letter.

So, the bottom of the letter should read:
--

Sincerely,

U.S. Department of Justice
Civil Rights Division

**Comment by blaughman** [comment] 2020-08-28 19:24
Basis has been removed.  Moving to UAT.

**Comment by blaughman** [comment] 2020-09-02 00:23
Cleaned card of PII.

**Comment by blaughman** [comment] 2020-09-04 15:52
Function is as intended on Chrome and Edge in Staging.

**Closed** 2020-09-11 01:33 UTC
Labels: Release 9-8-20, Small
