### ISSUE TITLE
BulkActions must only write to the activity log when Report fields are modified

### ISSUE THREAD

**Issue by Jkrzy** [18F/crt-portal#759] opened 2020-10-23 13:41 UTC
Origin: https://github.com/usdoj-crt/crt-portal/pull/718#issuecomment-714744592

When using BulkActions, if one changes the section for a report which already has any combination of:
*  no one assigned
* is status=new 
* no primary classification 

BulkAction “resets” those fields, by attempting to set them to an empty string,  anyway along and creates associated entries in the activity log.

We should not attempt to overwrite fields that are already empty OR add activity log entries for such an attempt

**Comment by timoballard** [comment] 2020-11-06 21:21
@Jkrzy - is the activity stream the main (and perhaps only) concern here? Asking because the description suggests that we should prevent the no-op activity stream entries, but also prevent the associated update queries from including fields that aren't actually changing. 

After looking into this a bit, filtering the activity stream for no-ops is pretty straightforward, but reworking the actual database updates to exclude unchanging fields by report would be a little more involved due to it being a single update on the reports queryset

**Comment by Jkrzy** [comment] 2020-11-10 21:03
@timoballard, it's the primary concern for sure -- we shouldn't write an entry to the activity log unless there's an actual change being made. That includes avoiding non-meaningful changes like `Updated from "None" to ""`

**Comment by blaughman** [comment] 2020-11-13 16:16
Function works as intended.  Moving to UAT.

**Closed** 2020-12-01 22:32 UTC
Labels: Bug
