### ISSUE TITLE
Subject line for the form letter templates

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#570] opened 2020-06-04 20:04 UTC
## Narrative

As an intake specialist, I would like to have a standardized subject line so that I can include them as a part of the email responses 

## Assumptions

- Subject line will include:
  - ID
  - Section name?

## Acceptance Criteria

1) Given that I click the 'Contact Complainant' button on the complaint details page
When I'm on the response template pop up screen
Then I see
  - A template selection drop down
  - auto filled email subject line
  - Email template

2) Given that I'm on the response template pop up screen
When I'm on the email subject line
Then I see the subject in the following format 
  - _Response: Your Civil Rights Division Report - [123-ABC] from [Section name]_

## Sign off

**Comment by cantsin** [comment] 2020-06-17 20:43
As per discussion with @blaughman we are going to copy both subject line _and_ email body.

**Comment by Jkrzy** [comment] 2020-07-01 01:30
Major functionality for this completed by @cantsin and merged into develop!

Wanted to confirm one piece, should the Subject line be included in the `print` view in any way? If Yes, let's create a new card for that please.

**Comment by blaughman** [comment] 2020-07-07 18:50
Function works as intended.

**Comment by blaughman** [comment] 2020-07-15 16:25
Deployed 7/14/20 closing card.

**Closed by blaughman** 2020-07-15 16:25 UTC
Labels: Feedback, Release 7-14-20
