### ISSUE TITLE
CRT user ability to download attached files from the complaint detail page

### ISSUE THREAD

**Issue by timoballard** [18F/crt-portal#884] opened 2021-02-16 21:02 UTC
## Narrative
As a CRT user, I want to download attached files from the complaint detail page to my local workstation.

## Acceptance Criteria
1) Given I am on the complaint detail page
when I look below the Personal Description card
then I see a card labeled 'Attachments'
AND
a list of attached files for this complaint.

2) Given I am on the complaint details page, 'Attachments' card
when I click on a particular attached file from the list
then a system dialogue appears allowing me to download the file to my local workstation.

### Assumptions
1. We are assuming that there will be under 5 attachments max and we won't have a need for a scroll bar 
2. At some point, we might include file type icons for each file format (ex, pdf icon, etc.)
3. If my system does not have the proper viewers or players, I will get the appropriate system dialogue boxes prompting me to choose a viewer or player manually

**Comment by blaughman** [comment] 2021-03-08 14:19
Function works as intended in Chrome and Edge.  Moving to UAT.

**Closed** 2021-03-10 01:45 UTC
