### ISSUE TITLE
Global filter by section 

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#621] opened 2020-07-06 19:04 UTC
https://docs.google.com/document/d/1mKaZgthkNnSSDIyx-ZWbwqBH0PVdxrWTurwJZjkGUgk/edit

## Narrative
As a CRT user, I only want to see the work assigned to my section, so that I can know what records I need to take action on without filtering.  

## Acceptance Criteria
1. Given I am on the view all table
when I look at the header
then I see the section selected
and 
a drop down containing all sections in CRT with their own checkbox

2. Given I have selected my section from the drop box in the header and clicked the "Update View" button
when I access the portal anytime after I select a section
then the new selection will be my default setting until I change it again.

3. Given I want to see records for multiple sections
when I select a checkbox for more than one section and click the "Update View" button
then I see the records corresponding to the selected checkboxes
and my default view is that multiple view selection

4. Given that I filtered the results by a status
When I click 'X' on the tag/label
Then I see the view all table to display all complaints

5. Given that I filtered data by status AND there are no records for that section
Then I see a message warning me about why there are no records showing
AND
back and forward pagination arrows are disabled

6. Given that I've applied a filter and have reach the end of all the pages for a given filter (ex: less than 15 or on the final page of pagination)
Then I see a message confirming that I've reached the end of records and to change filters to see more.

## Assumptions
-  Filter is moved to the heading
-  Once selected, filter will persist after user leaves and returns to the table
-  CRT users can still see records assigned to other sections, if desired (multi-select sections from drop down menu)

##  Mockup

Link to the prototype: https://gsa.invisionapp.com/share/53XK51LUWT4#/screens/420265438_1-View_All_Updated

![image.png](https://images.zenhubusercontent.com/5d2390b2c408a2441fc2874d/006987a4-6d68-4cb6-9d4b-0b2f929510e4)

![Screen Recording 2020-07-22 at 5.43.37 PM.mov.gif](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/4ba015de-40a6-4ef2-baac-960e028aa623)

### Annotation details
**Text:**
- Using the style `CRT body Bold All caps` -- which is 
font-size: 16px;
color: #FFFFFF;
In all caps
- Based off the [USWDS basic header component.](https://designsystem.digital.gov/components/header/#basic) (let me know if you suggest an alternative path)

**Multi-select drop down:**
- The check boxes should follow the same spacing/design from the personal characteristics page (step 4). We just customized the USWDS check box list
- I'm open to what might make this easier or harder, but I expected it to fit the same drop down that the other filters have now. 

**Button**
- Button is our `regular button` style. Like the "next" button on the form.

## Accessibility
- For drop downs
You can navigate to and use the element using keyboard only and it appears in the expected order; Element shows keyboard focus
This means opening, selecting, and closing. It’s expected that you can close a drop down by using the esc key
-  For any checkboxes:
You can navigate to and use the element using keyboard only and it appears in the expected order; Element shows keyboard focus
Element has appropriate contrast, including on rollover
Check boxes show focus when navigating
Check boxes are labeled and indicate when checked and unchecked by a screen reader

**Comment by blaughman** [comment] 2020-07-06 19:05
[Uploading... image.png ]

**Comment by harikrishnagit** [comment] 2020-07-25 23:16
@Jacklynn , can you tell what is the sass name for CRT body Bold All caps? I'm having hard time finding it.

**Comment by hakhalid11** [comment] 2020-08-04 16:13
@blaughman I would like to change the design for the dropdown button from
![image.png](https://images.zenhubusercontent.com/5efb8164bf9ea016ca6016f2/e015e553-b66c-468f-a4b8-994dcd38f445)
To the following
![image.png](https://images.zenhubusercontent.com/5efb8164bf9ea016ca6016f2/9730451c-b5fa-499a-8657-6424346dfad9)
I think having your selection in the label for the button will make the button label logic quite complex, instead we can leave it as a standard label. The selected filters would still be visible at the active filter area.
![image.png](https://images.zenhubusercontent.com/5efb8164bf9ea016ca6016f2/74c260bc-b35e-4aed-9f78-be944d5aade1)

**Comment by Jacklynn** [comment] 2020-08-06 18:37
@harikrishnagit I am not sure which stiles have been implemented by @hbillings 
The details are for the font are in the AC's above. 

This was @AvivaOskow's updated suggestion: 
<img width="627" alt="Screen Shot 2020-08-06 at 11 35 57 AM" src="https://user-images.githubusercontent.com/2560618/89569055-07629e00-d7d9-11ea-9502-93f672c4808a.png">

I'm not sure how hard it is to change the location, and colors so let me know if you want to continue with the white version, but the styles for this are:
`CRT H2 Bold` - public sans, 22px, `text-transform: uppercase`; `bg-gold-20v`
the stroke is 4px

**Comment by hbillings** [comment] 2020-08-11 15:40
@hakhalid11 the best way to figure this out is to look in `typography.scss` and see if there are classnames that fit what you're looking for. If there's nothing that works there, the next step is to look at the mixins defined in `_uswds-theme-typography.scss` and see if there's something there that matches the font size you need to use, then use that mixin to write your own classname. Examples of doing this appear at the top of `typography.scss` with the heading classnames.

There is a utility class on line 78 of `typography.scss` that you can apply to any other text to turn it white.

**Comment by blaughman** [comment] 2020-08-26 16:07
Treat migration as a separate card.

**Comment by hakhalid11** [comment] 2020-09-18 19:49
@blaughman I'd like to omit the all checkbox selection that is shown in the section dropdown. It is becoming a blocking issue and I don't want to spend too much time on it, also it can be added in as an enhancement afterwords. Let me know if your thoughts on this.

**Comment by blaughman** [comment] 2020-09-18 19:57
@hakhalid11 If it helps get this across the finish line, please proceed as you see fit.  As long as this does not affect the overall function and performance, we can merge this and see how the end users feel.  Thanks.

**Comment by blaughman** [comment] 2020-09-30 15:07
Function works as intended in Chrome and Edge.  Moving to UAT.

**Closed** 2020-10-07 00:09 UTC
Labels: Must
