### ISSUE TITLE
View incoming cases as 'New'

### ISSUE THREAD

**Issue by alexsoble** [18F/crt-portal#25] opened 2019-07-10 16:26 UTC
View/Manage the status of a complaint know if an action (and what action) needs to be taken on a complaint

## Narrative
As a CRT User, 
I want to view all newly submitted public complaints  
so that the complaints can be processed accordingly. 

## Background
DOJ CRT labels an incoming case as 'new' if the complaint has been submitted by the complainant, but has not been analyzed by DOJ CRT staff.  The label designation allows DOJ CRT staff to determine daily workloads and allocate resources. 

Details on [mural](https://app.mural.co/t/gsa6/m/gsa6/1562611057486)

With representation from ADM, DRS, EOS, FCS, IER, SPL, VOT, we gathered the following feedback:
**New** : Record has just been submitted to CRT from the online portal or manual entry, but has not yet been opened by a CRT user; assigned to section
**Open** : Record is being processed by the section, this could mean different things for each section. #50
**Closed** #53 : Complaint was responded to or recommended for review; attempts to contact complainants unsuccessful; section decides to close or open DJ number

## Assumptions
- 'New' cases arrive both by the complaint portal and manual entry by a CRT User
- 'Open' cases are being worked on by the appropriate section and the status remains the same until the matter moves to 'Closed' status
- _Default status is 'New'. All statuses must be manually altered to set any other status_

## Out of Scope
- changing status
- sorting or filtering by status

## Question
- What order is the status column in the view all table? Is status still expected to be the first column in the table? -- we have it as the first item
- @Jacklynn for a new record - is it just the status that is in bold or is the entire line item set in bold --We have the entire line as bold

## Acceptance criteria

1) Given a complaint has been submitted via
-- online intake form by a Public user
-- manual creation by CRT user
When I view the 'View All Complaints' table
Then I view a column called 'Status' 

2) Given a  new complaint has been submitted via
-- online intake form by a Public user
-- manual creation by CRT user
When I view the 'View All Complaints' table
Then I view a new record in table
AND 
Status of the new record is marked as 'New' 

3) Given I am on the view all complaints table
When I view a record with a status of 'new'
Then I see that
- [ ]  the text of the ('New') status is visually represented in blue color

5) as a user with low vision or color blindness...
When I view a record with a status of 'new'
I should be able to hear the status of New using a screen reader because the table will read out the cell & corresponding table header (should be set up already). 
AND
- As someone who is color blind, I should be able to tell using text what the status is.  Color+text is used to indicated status, so this should work for those with color blindness or low vision as well. 

## Mockups / Wireframes
![[LATEST] CRT view all - new.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/b6081e19-1a18-43db-97b7-e2d7ea0b78f1)

Image with new tag hi-light design
![Screen Shot 2019-11-14 at 5.39.48 PM.png](https://images.zenhubusercontent.com/56f1892d6caf56c9d38e1ac3/1f57d0cb-33a8-4549-bd8d-af3bd8455d10)

### Styles across the row
`font-family: PublicSans-Bold;` 
font-size: 14px; (same size)
color: #2E2E2A; (bg-gray-warm-80) - normal font color

### Status column
**TAG**
![tagstyles.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/c59b17b6-1547-48bd-a017-0cb6b1cbe5ac)
background color: primary blue
4px padding
10px padding to the left and right
1.5rem border-radius

Other status colors:
Gold: #FFBE2E 'gold-20v'
Gray: #E6E6E2 'gray-warm-10'

**TEXT**
`text-transform: uppercase`
`font-family: PublicSans-Bold;`
`font-size: 14px;`
`color: #FFFFFF;`

### Story sign off
- [x] PO (Bill)
### UAT Sign off
- [ ] PO
- [ ] Sections

## Technical Notes
- [ ]
- [ ]
- [ ]

**Comment by Jacklynn** [comment] 2019-10-25 19:50
Updated mock and added details around some of the styles across the row and the column.

**Comment by lalitha-jonnalagadda** [comment] 2019-11-05 15:27
@Jacklynn Please add the latest mock here(where you removed the blue dot next to the 'New' status) so I can get this ready for dev.

**Comment by lalitha-jonnalagadda** [comment] 2019-11-12 19:55
Updated the AC's to go with the latest mocks. This story can be moved to 'Ready for Dev'. 

@blaughman please sign off on the story if you don't have any further questions after our discussion during story time.

**Comment by blaughman** [comment] 2019-11-12 20:44
This looks good to me.

**Comment by LindsayYoung** [comment] 2019-11-13 19:30
Wanted to confirm the statuses will be:
 - New
 - Under review
 - Closed

Got that from:
https://app.zenhub.com/workspaces/doj-crt-intake-scrum-board-5d03bf56c1c8a35d482eca0f/issues/18f/crt-portal/58

**Comment by LindsayYoung** [comment] 2019-11-13 19:37
Ok, the assumptions say `new`, `open` and `closed`. Just wanted to verify we should ignore the text in the mocks.

**Comment by blaughman** [comment] 2019-11-13 19:41
Correct.  New Open and Closed are the three possible categories for status.

**Comment by Jacklynn** [comment] 2019-11-14 21:46
Other status colors:
Gold: #FFBE2E 'gold-20v'
Gray: #E6E6E2 'gray-warm-10'

**Comment by LindsayYoung** [comment] 2019-11-14 22:46
@Jacklynn just wanted to confirm the design pairing feedback to update the ACs does this look right to you?

```
.status-new {
  color: $white !important;
  background-color: $blue-warm-vivid-70;
  padding: 4px;
  padding-left: 10px;
  padding-right: 10px;
  border-radius: 8.5rem;
}
```

![Screen Shot 2019-11-14 at 5.39.48 PM.png](https://images.zenhubusercontent.com/56f1892d6caf56c9d38e1ac3/1f57d0cb-33a8-4549-bd8d-af3bd8455d10)

**Comment by LindsayYoung** [comment] 2019-11-18 16:01
See the new stuff: https://crt-portal-django-dev.app.cloud.gov/form/view

**Comment by blaughman** [comment] 2019-11-18 16:09
@LindsayYoung @lalitha-jonnalagadda Tested in IE 11 and it works as intended.  Approved and moving to UAT.

**Comment by Jacklynn** [comment] 2019-11-18 16:55
Looks good to me. @AvivaOskow how's the height look to you? But I think we could adjust any of the styling when we get to open/closed too, to move this card forward

**Comment by Jacklynn** [comment] 2019-11-18 17:39
@LindsayYoung @alexsoble I noticed that on voice over it the cell spells out "N-E-W" instead of reading "new" as a word. 

I suspect it would read correctly if you used `text-transform: uppercase;` to style `new` instead of typing it out in all uppercase. It might cause VO to read it as an abbreviation

**Comment by LindsayYoung** [comment] 2019-11-18 17:41
Thanks, @Jacklynn I can make a pr for that.

**Comment by lalitha-jonnalagadda** [comment] 2019-12-11 15:57
Completed independent UAT review.

**Closed by lalitha-jonnalagadda** 2019-12-11 15:57 UTC
Labels: Story
