### ISSUE TITLE
Tell CRT team if concern involved physical harm

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#160] opened 2019-10-21 15:13 UTC
## Narrative
As a Public user,
I want to Tell DOJ CRT if I experienced any physical harm
so that the appropriate DOJ CRT section can handle my complaint and direct me to the right reporting source. 

## Background
DOJ CRT sections enforce different statutes based upon subject matter. The questions asked in this section of the form gather 'statute-like' information that can help the system and CRT sections/ADM determine/confirm whether the record is in the correct jurisdiction.

This question crosses across all sections. its a criminal assignment question which will allow us to route the question accordingly to CRM.  

## Assumptions
- 'What Happened' page is already developed
- This is an optional question

## Out of scope
- routing logic
- redirecting the user to FBI site
- link to the local FBI page when the user selects 'yes' to the physical harm question

## Acceptance criteria

1) Given I am on the online portal and have entered (or not entered) my Contact information on step 1
When I click Next
Then I see that 
- [ ]  I am on the 'Primary Issue' page 
AND
- [ ]  'Protected Class' is the next page
AND
 - [ ] title of the page is 'What is your primary reason for contacting the Civil Rights Division?' 
AND 
- [ ] I see a section labelled - 'Hate crimes and human trafficking' 
AND 
- [ ] I see  'Next' and 'Back' buttons

2) Given that I'm on the primary issue page
When I'm on the 'Hate crimes and human trafficking' section
Then I see a subhead that says 'Hate crimes and human trafficking are considered criminal cases and go through a different process for investigation than other civil rights cases. If we determine your situation falls into these categories after submitting your concern, we will direct you to next steps.'
AND
that I have two options to make a selection from
  - Physical harm or threats of violence based on race, color, 
national origin, religion, gender, sexual orientation, 
gender identity, or disability
  - Coerced or forced to do work or perform a commercial sex act
AND 
I see that this question is optional 
AND
I'm able to click next and proceed to the protected class page

4) A11y - This should be a generic check box interaction. 
As a screen reader user, when I get to this question, I hear the question and options.
AND 
I can tell when something is and isn't selected
AND 
I can navigate & select using keyboard only
[documentation](https://www.w3.org/TR/2016/WD-wai-aria-practices-1.1-20160317/examples/radio/radio.html)

5) As a user with motor impairments, the touch target size is greater than 48px — so I can click on the text to also select the radio button of my choice. 

## Mockups

Link to source-of-truth: 
https://app.zenhub.com/workspaces/doj-crt-form-design-flows-5d7a67fa86a8cd0001581ea0/issues/18f/crt-django/72
Content
https://docs.google.com/document/d/1bxSRc9CQOHjQhTaYkHncE4tykUEFeC6RzFtP5IQk0Ic/edit#

### Story sign off 
- [ ] CRM
### UAT sign off
- [ ] Product owner
- [ ] CRM

**Comment by lalitha-jonnalagadda** [comment] 2019-10-28 18:35
@Jacklynn Can you please add a11y acceptance criteria to this card?

**Comment by lalitha-jonnalagadda** [comment] 2019-10-28 18:49
@blaughman  to review the content about contacting the FBI when 'Yes' is selected for the physical harm question.

**Comment by Jacklynn** [comment] 2019-10-28 21:25
@lalitha-jonnalagadda I added some around the radio button and touch target sizes, although I expect this be mostly the default behavior of the components 
-- I also added that the error message should be announced for screen readers as an AC

**Comment by lalitha-jonnalagadda** [comment] 2019-10-29 19:52
Notes from review:

- Need updated error and alert messages from @AvivaOskow 
- Updated source of truth  mock ups from @AvivaOskow
- @lalitha-jonnalagadda to include an AC on a user selecting 'No' 
- @lalitha-jonnalagadda to update step 2 from 'Category' to 'Primary issue' - confirm with @Jacklynn

**Comment by AvivaOskow** [comment] 2019-10-29 21:14
@UchMok @lalitha-jonnalagadda @Jacklynn I think because both of the questions on this page are required and will show an error message if the user doesn't select answers to both, I think we need to add our "Required" tag to the design, since that is the pattern we are showing on other pages. This would have to be the same for protected class then as well...

**Comment by Jacklynn** [comment] 2019-10-29 21:22
@AvivaOskow this is also tracked here: https://app.zenhub.com/workspaces/doj-crt-intake-task-board-5d03c11f75b7f25d4d009a09/issues/18f/civil-rights-complaints/366

We wanted to call out Contact as optional because it's unexpected and something folks might feel particularly nervous about, and is currently the starting page. We might want to just indicate "optional" if we think they'll be less optional than required fields.

**Comment by LindsayYoung** [comment] 2019-11-08 17:59
If the person chooses "yes" does the form allow them to proceed to the next page?

**Comment by lalitha-jonnalagadda** [comment] 2019-11-12 19:59
@LindsayYoung - if the user chooses 'Yes', then they should be able to click next and proceed to the next page.

**Comment by blaughman** [comment] 2019-11-13 16:52
I just spoke with Paige Fitzgerald  regarding our latest iteration of this question.

**Comment by lalitha-jonnalagadda** [comment] 2019-11-14 22:37
Moving this card into 'Analyzing' section as we work on the copy of the alert message.

**Comment by AvivaOskow** [comment] 2019-12-02 18:00
Most recent design, signed off with team at end of standup
![Screen Shot 2019-12-02 at 12.59.33 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/c82e863e-050b-4d74-9a87-1dc3f7a4ded3)

**Comment by Jacklynn** [comment] 2019-12-10 17:27
Added "optional" text to text source-of-truth, in the mock above.

**Comment by blaughman** [comment] 2019-12-19 14:05
Function works as intended.  Moving to UAT.

**Closed** 2020-01-10 19:39 UTC
Labels: Story
