### ISSUE TITLE
View 'incident location' in the View All table

### ISSUE THREAD

**Issue by Jacklynn** [18F/crt-portal#154] opened 2019-10-08 23:08 UTC
## Narrative
As a CRT user, 
I want to know where a potential civil rights violation occurred 
So that 
- my section can assign a reviewer who might work on specific regions
- to help find patterns in an area
- and to help identify records (John Smith from CA, not MO)

## Background
The incident location is vital to CRT users. Some sections have personnel assigned to specific districts. Others will use the discrimination location to reach out to the local FBI office for assistance with an investigation. It also assists with establishing a pattern or practice of civil rights violations in a defined geographical area. 

Today, sections are also using the jurisdiction as the section number in the DJ # set. 

## Assumptions
- Location name, City/town & state are required fields so the field will not be blank
- There is a possibility the discrimination location will be online in which case, location name will be a website. 

## Out of scope
- Editing
- Search and Filter

## Acceptance criteria
1) Given a Complainant has submitted a complaint w/ a violation summary via the online portal
When I'm on the 'View All' table
Then I see
- a column to the right of 'Contact details' and to the left of 'Violation Summary' called 'Incident Location'
AND
- city/town and state details in that column
AND 
- State is represented as a two letter state abbreviation (and is read out as an abbreviation for screen readers)

2) Given that I'm on the view all table and I see the incident location column,
When I click on the column name to **sort**
Then I see location name is sorted alphabetically by City/town (ascending/descending) AND state  (ascending/descending) 
-- As a screen reader user, I know that the header is a sortable item and how the column is currently sort. *One suggestion from the voiceover tech talk today (Adam was there!) was to use alt text or an aria label for the icon for this, reach out to the guild for more details.*

## Mockups / Wireframes
![Viewall-without names (1).png](https://images.zenhubusercontent.com/5b34455c5b51b10bd4dd59d6/4008a051-48be-49b8-b1d6-191c340c1d8c)

### Design updates
- [ ] remove vertical lines and boarders. Suggesting only have lines after each record, as in the mock. IF the last record, no line.  stroke color: `#EBEBEB` token: 'gray-cool-10'  
- [ ] add zebra stripping (background color for rows) starting with the first row. Suggesting background color: `#f9f9f9` token: 'gray-2'

## Questions
-  @blaughman What if they include other information, like the Company name, would you want to show that? This was something DRS named as helpful. That might make sorting more difficult. _We will just have state and city/town for now_
- Having multiple pieces of information in one cell (Name & Location) might be harder to sorting, do we want to continue with this pattern? _we will only sort by city and state_

## Technical Notes
- [ ]
- [ ]
- [ ]

**Comment by Jacklynn** [comment] 2019-10-08 23:18
## Narrative
As a CRT user, 
I want to...know where a potential civil rights violation occurred so that 
- my section can assign a reviewer who might work on specific regions
- to help find patterns in an area
- and to help identity records (John Smith from CA, not MO)

## Background
The incident location is vital to CRT users. Some sections have personnel assigned to specific districts. Others will use the discrimination location to reach out to the local FBI office for assistance with an investigation. It also assists with establishing a pattern or practice of civil rights violations in a defined geographical area. 

Today, sections are also using the jurisdiction as the section number in the DJ # set.

## Assumptions
- City & state are required fields so the field will not be blank
- The discrimination location will be a column on the view all table located to the right of the Free form text
- There is a possibility the discrimination location will be online.

## Out of scope
- Editing
- Filtering & sorting

## Acceptance criteria
1)
Given a Complainant has submitted a complaint w/ a discrimination location via the online portal
When I log in to view the 'View All complaints' table
Then I view a column to the right of 'Contact details' and to the left of 'Violation Summary' called 'Incident Location'
AND
I view the full city name and abbreviated state separated by a comma.
`Springfield, MO`

## Mockups / Wireframes
![[LATEST] CRT view all (1).png](https://images.zenhubusercontent.com/5d2390b2c408a2441fc2874d/8259db84-e167-46ae-a287-53f9ec5868df)

## Questions
-  @blaughman What if they include other information, like the Company name, would you want to show that? This was something DRS named as helpful. That might make sorting more difficult. 
- For online complaints...Would you want to see the URL? Or would you expect the public user to include the company HQ location? 
- Having multiple pieces of information in one cell (Name & Location) might be harder to sorting, do we want to continue with this pattern?

I outline some of the different scenarios that the display could look like:
![[LATEST] CRT view all - location.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/8ecdbd1b-efa6-42e9-8146-896ecb457e76)


## Technical Notes
- [ ]
- [ ]
- [ ]

**Comment by blaughman** [comment] 2019-11-14 14:12
A couple of my thoughts 1)  If other information is included (like company name) CRT users should have to look that up on the details page - we can't possibly include all submitted info on the table 2)  I think the URL would be helpful - having the public user look up the company HQ would put quite a burden on that user and I feel CRT would have to vet the information anyway.  3)  As for sorting, City/State are the most important.  I will choose functionality over inclusiveness for this column.

**Comment by lalitha-jonnalagadda** [comment] 2019-12-03 21:08
@Jacklynn - Please add a11y AC's to this card so its ready for dev

**Comment by Jacklynn** [comment] 2019-12-05 17:24
Added! Can I suggest sprinkling some style changes in this one as well? I'll add them in the design section, but they can be removed if needed

**Comment by el-mapache** [comment] 2019-12-06 23:12
@Jacklynn @AvivaOskow What is the width on this new table? I'd like to just go ahead and implement that part of the design in this ticket! I'm running into spacing issues with the current grid width 😬

**Comment by Jacklynn** [comment] 2019-12-06 23:21
We've been working off 1368px, but @AvivaOskow maybe able to say more how that works with the grid. It's a tad bigger than the widescreen grid:

(the table size in purple)
![widescreen](https://user-images.githubusercontent.com/2560618/70363104-f45b9080-183b-11ea-905e-d1a1a1a4010a.png)

**Comment by el-mapache** [comment] 2019-12-06 23:32
Ah gotcha! I'll use the `widescreen` modifier for now then, that gives us plenty of space to work with!

**Comment by blaughman** [comment] 2019-12-10 15:50
Function works as intended in IE 11.  Moving to UAT.

**Comment by lalitha-jonnalagadda** [comment] 2019-12-13 14:39
Reviewed with the deep dive group on 12/12 and this card can now be closed.

**Closed by lalitha-jonnalagadda** 2019-12-13 14:39 UTC
Labels: Story
