### ISSUE TITLE
bulk change rules

### ISSUE THREAD

**Issue by cantsin** [18F/crt-portal#758] opened 2020-10-21 20:57 UTC
Bulk Change Rules
Randy Abramson, Bill Laughman
10/21/20

    1. Bulk Section Change
        a. When selected
            i. Status goes to NEW
            ii. Assigned goes to ‘no one’

                • Required: when section is changed that Status automatically goes to NEW and is GREYED OUT and assigned to goes to GREYED OUT. ALSO Primary Classification goes to 'No value' and Judicial District are also GREYED OUT.
                • We understand that if users select one of the other fields first and THEN Section change, that it might be hard to change fields/grey them out on the fly. We are open to a page refresh whenever the Section change action is initiated. We also are open to helper language on the right side to assist with function expectation.

    2. Status change
        a. Should play nicely with all other interactions except Section Change (mentioned above)

    3. Primary Classification
        a. Plays nicely with Status and Assigned to
        b. If section is changed, the classification field should reset to 'No value'

    4. Judicial District
        a. Plays nicely with Status and Assigned to
        b. If section is changed, the classification field gets greyed out

    5. CRT Summary and Comment remain the same as they are now

    6. Cap number of reports that can be bulk changed at 500. If 501+ records are selected, take away second red button that says “Apply changes…”. Messaging can say “Maximum records for bulk change is capped at 500. Please return to the View All Table and adjust your filters.”

**Comment by randyabramson** [comment] 2020-10-22 17:40
@cantsin @ilodidoj @blaughman @Jkrzy 

**Background**
Per our chat today, Bill and I understand that the change of section will trigger a number of fields to become disabled and display 'locked in' values (see below for behavior). 

Note that we realize that if a user makes other selections BEFORE changing the section that some of the changes in the various drop downs might be hard to dynamically change. Still, the change in section needs to follow the following rules and we hope that the helper language/training will set expectations.

**Rules**
When the user changes the section:

* Status is greyed out and has a value of new
* Primary Classification is greyed out and cleared of any value
* Judicial District is greyed out and current value stays the same
* Assigned to is greyed out and cleared of any value
* Summary is available 
* Comment is available and required

**Helper language**
Below is the helper language present to the right of the action panel that is visible when the user hits the bulk action page. We can ask Aviva to help on design but please don't wait for that work.

===

Please know that any change to SECTION will make the following fields uneditable:
* Status
* Primary Classification
* Judicial District
* Assigned To

If you need to edit these fields, please press the 'Back to All' button to the left. If you have additional questions, please contact randy.abramson@usdoj.gov or bill.laughman@usdoj.gov

===

Note: if drop downs cannot be dynamically reset when the user changes section (example: user fills in SPECIALISTX for "Assign to" and then changes section, then the 'Assign to' field still says SPECIALISTX), then change the helper language to:

==

Please know that any change to SECTION will make the following fields uneditable:
* Status
* Primary Classification
* Judicial District
* Assigned To

If you made changes to any of these fields before changing SECTION, the changes will not apply.

If you need to edit these fields, please press the 'Back to All' button to the left. If you have additional questions, please contact randy.abramson@usdoj.gov or bill.laughman@usdoj.gov

**Comment by randyabramson** [comment] 2020-10-23 15:24
@cantsin 

Two things I'd like to see changed:

1. Don't make 'multiple' an active choice on SECTION. The header can remain, but it should not be selectable.
2. Please change the helper text from "...press the 'Back to All' button to the left" to "press the 'Back to All' button"
- Nice to have - if the we can make the 'Back to All" text clickable , that would be great...the text in that case would be ' 'return to the 'Back to All' table'

@blaughman is going to bang on this function until noon today and will confirm it can move forward.

cc: @Jkrzy

**Comment by randyabramson** [comment] 2020-10-23 17:24
@cantsin this is working as expected on CHROME and EDGE.

If you can get to the below, we can move this forward.

1. Don't make 'multiple' an active choice on SECTION. The header can remain, but it should not be selectable.

2. Please change the helper text from "...press the 'Back to All' button to the left" to "press the 'Back to All' button"

* Nice to have - if the we can make the 'Back to All" text clickable , that would be great...the text in that case would be ' 'return to the 'Back to All' table'

cc: @blaughman

**Comment by blaughman** [comment] 2020-10-23 17:36
@cantsin @randyabramson In my testing, it doesn't appear that 'Primary Classification' is resetting to no value when the records are reassigned to another section.

**Comment by cantsin** [comment] 2020-10-23 17:51
@blaughman i can't replicate, is there something i need to do beforehand? what i did: change two records to have the same primary classification (both different sections), then i reassigned section for both. classification is reset as expected.

**Comment by blaughman** [comment] 2020-10-23 18:16
My mistake.  I was testing in staging when I noticed the behavior.  James let me know this is only in Dev at the moment.  This works as intended.  Moving to UAT.

**Comment by randyabramson** [comment] 2020-10-23 18:20
Woo hoo!!!

**Comment by cantsin** [comment] 2020-10-23 18:47
PR is up for these changes (1 and 2 above, I also added the link)

**Closed** 2020-10-30 00:21 UTC
Labels: Release 10-29-2020
