### ISSUE TITLE
Filter by location name  - View all page

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#217] opened 2019-12-11 16:10 UTC
## Narrative
As a DOJ CRT user, I want to be able to filter complaints by location name so that I can only view a subset of the complaints I prefer to take relevant action on. 

## Background
All sections at DOJ, receive about 93K complaints annually. With this kind of volume, it's difficult to locate and look up complaints. Filtering by name will allow the intake specialists to look up a list of all complaints by a complainant. 

## Acceptance Criteria

1) Given that I'm on the view all table
When I'm at the Filter by location name 
Then I see free form text box to enter a location name
AND
I see a 'Filter Results' option

2) Given that I'm on the view all table
When I enter a location name or any portion of the location name in the  'location name' filters and click the 'Filter Results' button
Then I see the view all table filters to display all records matching the location
AND
I see a tag/label with the filtered criteria by the filtered data

## Sign off
- [x] PO
### UAT sign off 
- [x] PO
- [x] Product design
- [x] a11y

**Comment by blaughman** [comment] 2020-05-11 14:55
@lalitha-jonnalagadda @LindsayYoung

**Comment by lalitha-jonnalagadda** [comment] 2020-05-11 15:23
@blaughman - Location name is a part of the incident location filter. if you click the drop down for incident location, you will see location name filter.

**Comment by blaughman** [comment] 2020-05-11 15:28
@lalitha-jonnalagadda Thanks.  Function works as intended in Chrome, Edge and IE 11.  Awaiting approval from product design @Jacklynn before moving to UAT.

**Comment by Jacklynn** [comment] 2020-05-11 15:57
🎉🎉🎉 tested with VO+Safari too

**Closed** 2020-05-18 23:53 UTC
Labels: Story, release 5-19-20
