### ISSUE TITLE
Landing page buttons using the wrong roll over color

### ISSUE THREAD

**Issue by Jacklynn** [18F/crt-portal#643] opened 2020-07-21 19:23 UTC
**Issue:**
The roll over color on the landing page is not consistent with the rest of the form (ex: `Next` buttons)

the roll over color for the `blue-50` `#2378C3` for...
- [ ] Start a report
- [ ] Submit a report

That way it will make it consistent with buttons later in the form.

**Comment by blaughman** [comment] 2020-08-18 15:58
Color appears consistent with the rest of the form.  Moving to UAT.

**Comment by blaughman** [comment] 2020-08-24 18:24
Function works as intended in Staging.

**Closed** 2020-08-26 15:09 UTC
Labels: Release 8-25-20, Small
