### ISSUE TITLE
Enhancement - Filter reports for one day's time

### ISSUE THREAD

**Issue by randyabramson** [18F/crt-portal#753] opened 2020-10-19 20:56 UTC
### User Story: 
I am a product owner that wants to be able to filter reports in the Complaint Portal for 24 hours worth of time so that I can better understand the types of reports that come in on a given day.

### Backstory: 
If I enter a date range of just one day ([starting on 10/5/2020 and ending on 10/5/2020](https://crt-portal-django-prod.app.cloud.gov/form/view/?status=new&status=open&create_date_start=2020-10-05&create_date_end=2020-10-05&no_status=false)), the system does not return any results.

Per James: " this particular query doesn't "understand" the beginning of the day (12:00 am) or the end of the day (11:59 pm). so effectively with this query, we are looking for reports that were created exactly at 2020-10-05:00:00:00 which is not what the user expects."

### Acceptance Criteria: 
Given I am on the Complaint Portal /form/view page
When I select any combination of filters AND a date range that starts and ends on the same day
Then I see results that start with 12:00 AM and ends with 11:59 PM 

Assumptions: I assume times are recorded in EST?

**Comment by Jkrzy** [comment] 2020-10-21 14:45
Work around, increment the `create_date_end` by 1 to capture a single day.

example:

`create_date_start=2020-07-20` AND `create_date_end=2020-07-21`

https://crt-portal-django-dev.app.cloud.gov/form/view/?create_date_start=2020-07-20&create_date_end=2020-07-21

**Comment by ilodidoj** [comment] 2020-10-21 14:58
Thanks @Jkrzy . I mentioned this yesterday, the feature by date already support this.  But 24 hours is different than One Day, are we talking about 24 hours from any point of time or this card is just for a single day report which ever date we pick? Not clear to me from the card.

**Comment by ilodidoj** [comment] 2020-10-21 14:59
Current today
 range ![image.png](https://images.zenhubusercontent.com/5d374c9d0efb727bd5a01afd/53a59e82-66ef-4e87-b1c0-5edb97ea9647)

**Comment by randyabramson** [comment] 2020-10-21 15:02
@ilodidoj  @Jkrzy 

I think we are interested in just getting the reports for a given day.

So, if I select start date of 10/21 and end date of 10/21, you would see all records entered from 12:00 AM ET - 11:59 PM ET.

Dos this make sense?

**Comment by randyabramson** [comment] 2020-10-21 15:07
@ilodidoj if I am reading your note correctly, in the current world, the 'one day' report can come up if I set the end date of 10/22. But wouldn't that include reports coming in on 10/22? Again, I think the above example I give above is more intuitive.

**Comment by ilodidoj** [comment] 2020-10-21 15:10
@randyabramson Agreed, your current example clearly define the scope of the card, i.e. this is a filter for a given single day (any day) not just today.

**Comment by blaughman** [comment] 2020-11-02 19:23
Function works as intended.  Moving to UAT.

**Closed** 2020-11-17 22:33 UTC
