### ISSUE TITLE
[Placeholder] Translate Landing Page, Form, Error Pages and Privacy Policy to Traditional Chinese

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#206] opened 2019-12-04 18:53 UTC
## Narrative
As a public user, I want to access the complaint portal in Traditional Chinese so that I can submit a complaint in my native language. 

## Background
The Language Working Group (LWG) requested the portal be translated to Traditional Chinese to increase language access.

**Comment by blaughman** [comment] 2021-03-31 20:18
[https://app.zenhub.com/files/183258764/44adbcca-7392-4d37-8d70-d8729a0d278e/download](https://app.zenhub.com/files/183258764/44adbcca-7392-4d37-8d70-d8729a0d278e/download)

**Comment by blaughman** [comment] 2021-04-15 14:25
Front-end pages appear as intended.  Content assessment still required.  Moving to UAT.

**Closed** 2021-05-07 14:05 UTC
