### ISSUE TITLE
Redirecting to human trafficking hotline - pop up message

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#532] opened 2020-05-20 15:54 UTC
## Narrative

As a public user, when I click on the 'National Human Trafficking Hotline', I would like to know that I am being redirected to a different site so that I am assured of my action

## Acceptance Criteria

1. Given that I'm on the hate crimes question
When I click on the 'Get help from the National Human Trafficking Hotline'
Then I see a pop up screen that reminds me that I'm leaving the DOJ site with the following copy

**You are now leaving the Department of Justice website. 
The Department of Justice does not endorse the organizations or views represented by this site and takes no responsibility for, and exercises no control over, the accuracy, accessibility, copyright or trademark compliance or legality of the material contained on this site.**

- Spanish Translation

**Está saliendo del sitio web del Departamento de Justicia.
El Departamento de Justicia no respalda las organizaciones o los puntos de vista representados por este sitio y no se responsabiliza ni ejerce control sobre la precisión, la accesibilidad, el cumplimiento con los derechos de autor o marca registrada o la legalidad del material contenido en este sitio.**

##### Example Implementation
- https://www.justice.gov/crt/webinars#ier%20webinars

## Mockups
![External link version C Copy 3.jpg](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/3abde423-20d0-4ce5-a05c-32cd4481842b)

**Comment by blaughman** [comment] 2020-05-20 16:09
Per Uchenna, we should convey that we will not keep any information that the public user submitted prior to the redirection.

**Comment by Jacklynn** [comment] 2020-05-20 21:17
Entry point:
![Future state Copy.jpg](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/a383c96d-f8aa-449c-a7a3-f677f0820422)

Options:
![Screen Shot 2020-05-20 at 2.13.25 PM.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/246def6f-c197-49df-b1a1-7beb839a2e1a)

**A:** same as 404 error layout, no bail out
**B:** Same as A with a bail out to not get transferred
**C:** Pop up version. 

I don't have strong feelings about the text.

**Comment by lalitha-jonnalagadda** [comment] 2020-05-20 21:27
@Jacklynn I like the interaction in Option C with the copy in option B. I would like the dev team to comment on the implementation and lift with option C vs others.

**Comment by Jacklynn** [comment] 2020-05-22 02:30
I posted this late to Lalitha, but here are some other thoughts after more reflective time...

**D:**   If this is truly the future or referrals…I would do something more like this. A full, obvious stop in the process. It is kind of unusual to start something like a form that makes you leave and you’re not sure what why. 
![Screen Shot 2020-05-21 at 7.22.20 PM.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/4e8f50fe-eba6-468b-bde7-2afa67d98fcb)

In [previous research on routing](https://docs.google.com/presentation/d/1k3CaTR6dhKB48qhGFohIp2_G2-YNQQO4KzGxU-EnABg/edit#slide=id.g5134b89622_0_304), people preferred a full stop over giving them the option to continue with the division despite our recommendation. 

**E:** Popup version that might be easier to implement
![Screen Shot 2020-05-21 at 7.25.27 PM.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/1227b378-e5a0-4e27-875d-a58415f04414)

**Comment by cantsin** [comment] 2020-06-30 23:47
We already have a modal implementation for form letters that we can re-use, so I don't see a problem with having a modal here. I think it's more a question of the text here?

**Comment by cantsin** [comment] 2020-07-01 00:10
@Jacklynn `D` might be a bit problematic since we have wizard form functionality, but I can look into making this work too.

**Comment by Jacklynn** [comment] 2020-07-01 01:19
@cantsin I think D can be a longer term solution. It will be nice when we have more referrals to not confuse users by having multiple pathways.

This is the example content I sent to Dan:
![External link version C Copy.jpg](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/a35bc4e7-d94d-4454-8753-84cade1ba604)

This has the **already approved content** from DOJ (the italic paragraph). We'll likely need to go with this one, according to Dan
![External link version C Copy 3.jpg](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/e7dff7e2-c1fe-48d1-840a-41b65166f563)

@lalitha-jonnalagadda do we want it to automatically go to the new page? I assume **yes**, but a way to bail out if you change your mind. I had back/next buttons before.
@cantsin If it's not a lot of trouble, it would be nice for the dialog to match more the front end in terms of padding (as mocked). The form letter dialog has less padding because it's expecting more actions within.

**Comment by lalitha-jonnalagadda** [comment] 2020-07-06 15:07
@cantsin - I added the Spanish translation for this copy in the AC's above.

**Comment by Jacklynn** [comment] 2020-07-06 16:37
I uploaded the mock in the the main section with annotations based on Aviva's latest style guide, if you need more detail, please let me know!

**Comment by cantsin** [comment] 2020-07-13 14:19
@blaughman I have confirmed this works in IE11/Edge but would appreciate a second set of :eyes: to make sure this feature works as advertised on these web browsers. Thanks!

**Comment by blaughman** [comment] 2020-07-13 15:09
@cantsin I tested in Edge and Chrome, but did not get the pop up message.  I directed me to the NHTH without any type of notice of the redirection.  I'm happy to hop on a zoom to demonstrate, if needed.  Should I try a hard refresh of the browser?

**Comment by blaughman** [comment] 2020-07-13 15:12
@cantsin Sorry, I was in dev when testing.  This works as intended in both Chrome and Edge in staging.  Sorry again.  Keep up your great work.

**Comment by cantsin** [comment] 2020-07-13 15:15
phew :cold_sweat: 

thanks for the confirmation! appreciate it.

**Comment by blaughman** [comment] 2020-07-13 16:48
@cantsin @harikrishnagit @Jacklynn I will add the note here as well.  Testing on justice.gov for external redirection time is 5 seconds.  https://www.justice.gov/usao/social-media-directory

**Comment by Jacklynn** [comment] 2020-07-13 21:08
### Updating from design/dev time:

![External link version C Copy 3](https://user-images.githubusercontent.com/2560618/87342430-17e86700-c500-11ea-8c70-46c13e6bc141.jpg)

- Proposing not an auto-redirect since there is a "Continue" button. 
- Adding "continue" button if users are ready before hand (do we have this spanish translated? 🥺
- Make sure title/heading reads out when the modal opens. ? On the [example](https://www.w3.org/TR/wai-aria-practices-1.1/examples/dialog-modal/dialog.html) I found, “modal title” and then “Address”. So ours would be….“You are now leaving the DOJ website, ...”

_How I calculated the time:_
- Avg reading speed is 200-400 wpm, the dialog has 57 words
-  I calculated time for the low end of the reading speed, 200, for 57 words (=about 17seconds)
- I added 3 seconds (recommended by best-practices search)

**Comment by cantsin** [comment] 2020-07-13 22:57
Note: need spanish translation for "You will be automatically redirected to:"

**Comment by Jacklynn** [comment] 2020-07-15 18:17
@cantsin can you make the desktop size breakpoint can we make it 50%? The long line lengths would be hard to read now. 
![Screen Shot 2020-07-15 at 11.15.30 AM.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/d740d956-85f8-4b50-a96b-1f084049e0eb)

**Closed** 2020-07-20 16:44 UTC
Labels: Must, Release 7-14-20
